Repository kiegroup/kogito-operator, pull requests merged in 2019-10, with the labels that each got.

#69 Bump to 0.5.0
  .circleci/config.yml
  README.md
  deploy/crds/app_v1alpha1_kogitoapp_crd-0.1.0.yaml
  deploy/crds/app_v1alpha1_kogitoapp_crd-0.3.0.yaml
  deploy/crds/app_v1alpha1_kogitoapp_crd.yaml
  deploy/olm-catalog/kogito-cloud-operator/0.5.0/app_v1alpha1_kogitoapp_crd.yaml
  deploy/olm-catalog/kogito-cloud-operator/0.5.0/app_v1alpha1_kogitodataindex_crd.yaml
  deploy/olm-catalog/kogito-cloud-operator/0.5.0/kogito-cloud-operator.v0.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-cloud-operator/kogito-cloud-operator.package.yaml
  deploy/operator.yaml
  hack/go-build.sh
  hack/go-vet.sh
  pkg/controller/kogitoapp/resource/build_config.go
  version/version.go
Labels: ready :rocket:

#68 [KOGITO-290] - Creating Prometheus annotations from image labels
  README.md
  deploy/examples/onboarding-example.yaml
  docs/img/prometheus_graph.png
  docs/img/prometheus_target.png
  pkg/controller/kogitoapp/resource/create_resources.go
  pkg/controller/kogitoapp/resource/deployment_config.go
  pkg/controller/kogitoapp/resource/deployment_config_test.go
  pkg/controller/kogitoapp/resource/image_metadata.go
  pkg/controller/kogitoapp/resource/image_metadata_test.go
  pkg/controller/kogitoapp/resource/manage_resources.go
  pkg/controller/kogitoapp/resource/manage_resources_test.go
  pkg/controller/kogitoapp/resource/meta.go
  pkg/controller/kogitoapp/resource/meta_test.go
  pkg/controller/kogitoapp/resource/service.go
  pkg/controller/kogitoapp/resource/service_test.go
Labels: ready :rocket:

#71 Small documentation review for OperatorHub
  README.md
  docs/img/catalog-kogito-operator.png
  docs/img/installed-kogito-operator.png
Labels: needs review :mag:

#73 [KOGITO-130] - Fixing makefile e2e parameters
  Makefile
  hack/run-e2e.sh
Labels: ready :rocket:

#74 [KOGITO-376] - Removing 'LastSavedKogitoApp' to avoid marshall problems
  .circleci/config.yml
  cmd/kogito/command/context/config.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/deploy/deploy_service_test.go
Labels: ready :rocket:

#75 [KOGITO-379] - Fixing labels for multi backslash
  deploy/olm-catalog/kogito-cloud-operator/0.5.0/kogito-cloud-operator.v0.5.0.clusterserviceversion.yaml
  pkg/controller/kogitoapp/resource/image_metadata.go
  pkg/controller/kogitoapp/resource/image_metadata_test.go
Labels: ready :rocket:

#77 [KOGITO-376] - Moving config initialization out of read functions
  cmd/kogito/command/context/config.go
  cmd/kogito/command/context/root.go
  deploy/olm-catalog/kogito-cloud-operator/0.5.0/kogito-cloud-operator.v0.5.0.clusterserviceversion.yaml
Labels: ready :rocket:

#79 [KOGITO-410] Small script to create operatorhub assets
  Makefile
  README.md
  deploy/olm-catalog/kogito-cloud-operator/0.5.0/kogito-cloud-operator.v0.5.0.clusterserviceversion.yaml
  hack/pr-operatorhub.sh
Labels: ready :rocket:

#78 [KOGITO-184] Script for Kogito CLI release
  Makefile
  hack/go-build-cli.sh
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod
  vendor/github.com/magiconair/properties/go.mod
  vendor/github.com/mitchellh/go-homedir/go.mod
  vendor/github.com/mitchellh/mapstructure/go.mod
  vendor/go.opencensus.io/go.mod
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/go.sum
Labels: ready :rocket:

#80 [KOGITO-415] Fixing resources limits values for OCP 4.2
  deploy/examples/onboarding-example.yaml
  deploy/olm-catalog/kogito-cloud-operator/0.5.0/kogito-cloud-operator.v0.5.0.clusterserviceversion.yaml
  pkg/controller/kogitoapp/resource/build_config_s2i.go
  pkg/controller/kogitoapp/resource/build_config_s2i_test.go
  pkg/controller/kogitoapp/resource/manage_resources_test.go
  pkg/controller/kogitoapp/shared/utils.go
  pkg/controller/kogitoapp/shared/utils_test.go
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod
  vendor/github.com/magiconair/properties/go.mod
  vendor/github.com/mitchellh/go-homedir/go.mod
  vendor/github.com/mitchellh/mapstructure/go.mod
  vendor/go.opencensus.io/go.mod
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/go.sum
Labels: needs review :mag:

#72 [KOGITO-372] Code refactoring for CR update logic with operator-utils
  cmd/kogito/command/project/use_project_test.go
  deploy/crds/app_v1alpha1_kogitoapp_crd.yaml
  deploy/olm-catalog/kogito-cloud-operator/0.5.0/app_v1alpha1_kogitoapp_crd.yaml
  go.mod
  go.sum
  pkg/apis/app/v1alpha1/kogitoapp_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/client/openshift/buildconfig.go
  pkg/controller/kogitoapp/kogitoapp_controller.go
  pkg/controller/kogitoapp/kogitoapp_controller_test.go
  pkg/controller/kogitoapp/resource/build_config_s2i.go
  pkg/controller/kogitoapp/resource/deployed_resources.go
  pkg/controller/kogitoapp/resource/deployed_resources_test.go
  pkg/controller/kogitoapp/resource/manage_resources.go
  pkg/controller/kogitoapp/resource/manage_resources_test.go
  pkg/controller/kogitoapp/resource/requested_resources.go
  pkg/controller/kogitoapp/resource/requested_resources_test.go
  pkg/controller/kogitoapp/resource/resource_comparator.go
  pkg/controller/kogitoapp/resource/resource_comparator_test.go
  pkg/controller/kogitoapp/resource/resources.go
  pkg/controller/kogitoapp/resource/route.go
  pkg/controller/kogitoapp/resource/service.go
  pkg/controller/kogitoapp/resource/service_test.go
  pkg/controller/kogitoapp/status/manage_status.go
  pkg/controller/kogitoapp/status/manage_status_test.go
  pkg/util/arrays.go
  pkg/util/arrays_test.go
  pkg/util/env_var.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/defaults.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/map.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/types.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/utils.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/read/reader.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/types.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/hooks/update_hooks.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/writer.go
  vendor/modules.txt
Labels: on hold :hand:

#82 [KOGITO-414] - Saving project in use every time if -p flag is used
  .circleci/config.yml
  cmd/kogito/command/context/config.go
  cmd/kogito/command/deploy/delete_service.go
  cmd/kogito/command/deploy/delete_service_test.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/data_index_test.go
  cmd/kogito/command/install/kogito_operator.go
  cmd/kogito/command/install/kogito_operator_test.go
  cmd/kogito/command/project/delete_project.go
  cmd/kogito/command/project/delete_project_test.go
  cmd/kogito/command/project/new_project_test.go
  cmd/kogito/command/project/use_project_test.go
  cmd/kogito/command/shared/command_checks.go
  cmd/kogito/command/shared/install_operator_test.go
  cmd/kogito/command/shared/resource_checks.go
  cmd/kogito/command/shared/resource_checks_test.go
  hack/go-test.sh
Labels: ready :rocket:

#84 Reorganized a bit the README
  .gitignore
  README.md
Labels: ready :rocket:

#83 [KOGITO-287] - Injecting proto files into DataIndex ConfigMap
  pkg/controller/kogitoapp/resource/deployment_config.go
  pkg/controller/kogitoapp/resource/deployment_config_test.go
  pkg/controller/kogitoapp/resource/route.go
  pkg/controller/kogitoapp/resource/service.go
  pkg/controller/kogitoapp/resource/service_test.go
  pkg/controller/kogitodataindex/kogitodataindex_controller.go
  pkg/controller/kogitodataindex/resource/kogitoapp.go
  pkg/controller/kogitodataindex/resource/manage_resources.go
  pkg/controller/kogitodataindex/resource/manage_resources_test.go
  pkg/controller/kogitodataindex/resource/testdata/onboarding-dockerimage-json
  pkg/resource/configmap.go
  pkg/resource/configmap_test.go
  pkg/resource/image_metadata.go
  pkg/resource/image_metadata_test.go
  pkg/resource/log.go
  pkg/resource/testdata/base64-onboarding-proto
  pkg/test/io.go
  pkg/util/hash.go
  pkg/util/hash_test.go
Labels: ready :rocket:

#87 KOGITO-470: Kogito CLI cannot find operator template files when trying to install it into the namespace
  hack/go-build-cli.sh
Labels: ready :rocket:

#88 Kogito-476: Corrected default image name for data index service
  pkg/controller/kogitodataindex/resource/defaults.go
Labels: ready :rocket:

#86 [KOGITO-478] Add possibility to run e2e tests with external image
  Makefile
  hack/run-e2e.sh
Labels: needs review :mag:

#89 [KOGITO-419] - Increasing the default native build memory limit
  README.md
  deploy/olm-catalog/kogito-cloud-operator/0.6.0/kogito-cloud-operator.v0.6.0.clusterserviceversion.yaml
  go.sum
  pkg/controller/kogitoapp/resource/build_config_s2i.go
Labels: needs review :mag:

#90 [KOGITO-477] Setting default port to 8080 to match image
  README.md
  pkg/controller/kogitodataindex/resource/defaults.go
Labels: needs review :mag:

#92 [KOGITO-485] Small patch for the Kogito CLI 0.5.1 release
  cmd/kogito/command/context/root.go
  cmd/kogito/version/version.go
Labels: ready :rocket:

#93 [KOGITO-485] - Cherry pick from 0.5.1
  cmd/kogito/command/context/root.go
  cmd/kogito/version/version.go
Labels: needs review :mag:

#94 [KOGITO-341] - Checking if the Kogito Operator is in the hub before r…
  cmd/kogito/command/install/kogito_operator.go
  cmd/kogito/command/project/new_project.go
  cmd/kogito/command/shared/install_operator.go
  cmd/kogito/command/shared/install_operator_test.go
  cmd/kogito/command/shared/operatorhub.go
  cmd/kogito/command/shared/resource_checks.go
  go.mod
  go.sum
  pkg/client/client.go
  pkg/client/meta/meta.go
  vendor/github.com/operator-framework/operator-marketplace/LICENSE
  vendor/github.com/operator-framework/operator-marketplace/pkg/apis/operators/shared/doc.go
  vendor/github.com/operator-framework/operator-marketplace/pkg/apis/operators/shared/phase.go
  vendor/github.com/operator-framework/operator-marketplace/pkg/apis/operators/shared/phase_types.go
  vendor/github.com/operator-framework/operator-marketplace/pkg/apis/operators/shared/shared.go
  vendor/github.com/operator-framework/operator-marketplace/pkg/apis/operators/shared/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/operator-marketplace/pkg/apis/operators/v1/doc.go
  vendor/github.com/operator-framework/operator-marketplace/pkg/apis/operators/v1/operatorsource_types.go
  vendor/github.com/operator-framework/operator-marketplace/pkg/apis/operators/v1/register.go
  vendor/github.com/operator-framework/operator-marketplace/pkg/apis/operators/v1/zz_generated.deepcopy.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/scheme/scheme.go
Labels: needs review :mag:

#97 [KOGITO-498] - Kogito CLI to read from KUBECONFIG before the home dir
  pkg/client/client.go
  pkg/client/client_test.go
Labels: ready :rocket:
