Repository kiegroup/kogito-operator, pull requests merged in 2020-05, with the labels that each got.

#327 [KOGITO-1852]: Update check for internal registry
  Jenkinsfile
  Jenkinsfile.nightly
  test/framework/kubernetes.go
  test/framework/operator.go
Labels: bdd-tests 🧪, needs review :mag:

#328 [KOGITO-2012] - Impossible to configure external Kafka for Data index using kafka-instance CLI parameter
  cmd/kogito/command/install/data_index.go
  pkg/infrastructure/services/deployer.go
  pkg/infrastructure/services/deployer_test.go
Labels: ready :rocket:

#334 [KOGITO-2077] Use buildah instead of podman
  Jenkinsfile
  Jenkinsfile.nightly
Labels: needs review :mag:

#335 [KOGITO-2010] Review scenario tags and add a tags dictionary
  README.md
  test/features/deploy_quarkus_service.feature
  test/features/deploy_service_resources.feature
  test/features/deploy_springboot_service.feature
  test/features/install_jobs_service.feature
Labels: bdd-tests 🧪, ready :rocket:

#338 [KOGITO-615] - Operator error report "Status: True" when error on kog…
  pkg/apis/app/v1alpha1/conditions.go
  pkg/apis/app/v1alpha1/conditions_test.go
Labels: needs review :mag:

#341 [KOGITO-2159] Nightly run only smoke tests
  Jenkinsfile.nightly
Labels: ready :rocket:

#333 KOGITO-1700 - Add optional configuration of Infinispan in BDD
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  pkg/client/client.go
  pkg/client/meta/meta.go
  test/features/kogito_service_performance.feature
  test/framework/infinispan.go
  test/framework/kogitoapp.go
  test/framework/kubernetes.go
  test/framework/openshift_resources.go
  test/steps/infinispan.go
  test/steps/kogitoapp.go
  test/steps/kogitodataindex.go
  test/steps/utils.go
Labels: ready :rocket:

#247 [KOGITO-256] -Kogito CLI to upload source files from local machine to…
  README.md
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/error/kogitoapp_errors.go
  cmd/kogito/command/message/kogitoapp.go
  cmd/kogito/command/util/build_from_file.go
  cmd/kogito/command/util/build_from_file_test.go
  go.sum
  pkg/client/meta/meta.go
  pkg/client/openshift/buildconfig.go
  pkg/controller/kogitoapp/resource/build_config_s2i.go
  pkg/controller/kogitoapp/resource/build_config_s2i_test.go
  pkg/controller/kogitoapp/resource/build_config_test.go
  pkg/controller/kogitoapp/resource/requested_resources.go
  pkg/controller/kogitoapp/resource/requested_resources_test.go
  pkg/controller/kogitodataindex/kogitodataindex_controller_test.go
Labels: needs review :mag:

#349 KOGITO-2192: BDD tests: Should provide a file with created namespaces
  Jenkinsfile
  Jenkinsfile.nightly
  hack/run-tests.sh
  test/README.md
  test/framework/kubernetes.go
  test/framework/namespace.go
  test/scripts/prune_namespaces.go
Labels: bdd-tests 🧪, ready :rocket:

#322 [KOGITO-1347] Test Data index using external Kafka
  go.sum
  pkg/client/client.go
  pkg/client/meta/meta.go
  pkg/controller/kogitoinfra/kafka/resource.go
  pkg/infrastructure/kafka.go
  test/features/install_dataindex.feature
  test/framework/kafka.go
  test/framework/kogitoserviceutils.go
  test/steps/data.go
  test/steps/kafka.go
  test/steps/kogitodataindex.go
Labels: bdd-tests 🧪, ready :rocket:

#352 KOGITO-1613: Cucumber tests: Test upload source files (dmn, drl, bpmn…
  pkg/client/openshift/buildconfig.go
  test/features/deploy_source_files.feature
  test/framework/kogitodeployfiles.go
  test/steps/data.go
  test/steps/deploy_files.go
Labels: bdd-tests 🧪, ready :rocket:

#342 KOGITO-2164: Cucumber Tests: Add workaround in tests to ignore pods w…
  test/framework/kubernetes.go
  test/framework/openshift.go
Labels: bdd-tests 🧪, ready :rocket:

#357 [KOGITO-2302] correct bug on BDD tests execution
  cmd/kogito/command/install/kogito_operator.go
  cmd/kogito/command/project/project.go
  cmd/kogito/command/shared/default_services.go
  cmd/kogito/command/shared/install_services.go
  test/framework/openshift.go
Labels: bdd-tests 🧪, needs review :mag:

#358 [KOGITO-2308] Review infra component tagging
  README.md
  test/features/deploy_quarkus_service.feature
  test/features/deploy_springboot_service.feature
  test/features/deploy_travel_agency.feature
  test/features/install_dataindex.feature
  test/features/install_jobs_service.feature
  test/features/install_mgmtconsole.feature
  test/features/kogito_service_performance.feature
Labels: bdd-tests 🧪, ready :rocket:

#348 KOGITO-1899: BDD tests: Test travel-agency scenario in native mode
  test/features/deploy_travel_agency.feature
Labels: bdd-tests 🧪, ready :rocket:

#344 [KOGITO-2150][KOGITO-2117] Adjust deploy pipeline & Setup promote pipeline
  Jenkinsfile.deploy
  Jenkinsfile.promote
  Makefile
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/config/config.go
  test/framework/kogitoapp.go
  test/framework/kogitoserviceutils.go
Labels: ready :rocket:

#343 [KOGITO-833] - Operator CLI: Add option to change channel and/or oper…
  cmd/kogito/command/common/operator_flag.go
  cmd/kogito/command/deploy/common.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/infinispan.go
  cmd/kogito/command/install/jobs_service.go
  cmd/kogito/command/install/kafka.go
  cmd/kogito/command/install/keycloak.go
  cmd/kogito/command/install/kogito_operator.go
  cmd/kogito/command/install/kogito_operator_test.go
  cmd/kogito/command/install/mgmt_console.go
  cmd/kogito/command/project/new_project.go
  cmd/kogito/command/project/project.go
  cmd/kogito/command/project/use_project.go
  cmd/kogito/command/shared/install_operator.go
  cmd/kogito/command/shared/install_operator_test.go
  cmd/kogito/command/shared/install_services.go
  cmd/kogito/command/shared/kogitochannels.go
  cmd/kogito/command/shared/kogitochannels_test.go
  cmd/kogito/command/shared/operatorhub.go
Labels: needs review :mag:

#359 KOGITO-1899: Enable tests in native mode
  test/features/deploy_travel_agency.feature
Labels: bdd-tests 🧪, ready :rocket:

#355 KOGITO-2087: Test KogitoRuntime
  Makefile
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  pkg/client/client.go
  test/README.md
  test/config/config.go
  test/features/deploy_kogito_runtime.feature
  test/framework/dockerfile_provider.go
  test/framework/kogitoapp.go
  test/framework/kogitoruntime.go
  test/framework/kubernetes.go
  test/framework/util.go
  test/steps/data.go
  test/steps/image_registry.go
  test/steps/kogitoapp.go
  test/steps/kogitoruntime.go
  test/steps/utils.go
Labels: bdd-tests 🧪, ready :rocket:

#350 [KOGITO-2218] Setup new regex for images
  deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/app.kiegroup.org_kogitoapps_crd.yaml
  pkg/apis/app/v1alpha1/kogitoapp_types.go
  pkg/framework/image.go
  pkg/framework/image_test.go
Labels: ready :rocket:
