Repository kiegroup/kogito-operator, pull requests merged in 2020-08, with the labels that each got.

#485 [KOGITO-1925] CLI: force native build to use s2i
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/flag/build_flag.go
Labels: needs review :mag:

#486 KOGITO-2771: Cucumber Tests: Cover Webhooks in KogitoBuild
  test/features/deploy_kogito_build.feature
  test/framework/kogitobuild.go
  test/framework/mappers/cr_to_cli.go
  test/framework/openshift.go
  test/steps/mappers/create_kogito_build.go
  test/steps/openshift.go
Labels: bdd-tests 🧪, ready :rocket:

#487 [KOGITO-2934] - Add kie-github-ci-bot to kogito-cloud-operator reposi…
  .github/bot-files/comments.yml
  .github/bot-files/labels.yml
  .github/bot-files/paths.yml
  .github/bot-files/reviewers.yml
Labels: CI/CD :loop:, ready :rocket:

#488 [KOGITO-2940] Tests: Fix missing request body in HTTP request step
  test/steps/http.go
Labels: bdd-tests 🧪, ready :rocket:

#490 [KOGITO-2932] Install operators one after the other
  test/steps/operator.go
Labels: bdd-tests 🧪, ready :rocket:

#489 [KOGITO-2881] Tests: Migrate BDD tests to use KogitoRuntime
  pkg/apis/app/v1alpha1/kogitobuild_types.go
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  test/features/binary_build.feature
  test/features/deploy_kogito_build.feature
  test/features/deploy_kogito_runtime.feature
  test/features/deploy_quarkus_service.feature
  test/features/deploy_service_resources.feature
  test/features/deploy_springboot_service.feature
  test/features/deploy_travel_agency.feature
  test/features/install_jobs_service.feature
  test/features/kogito_service_performance.feature
  test/features/prometheus.feature
  test/features/service_discovery.feature
  test/features/update_httpport.feature
  test/framework/dockerfile_provider.go
  test/framework/kogitoapp.go
  test/framework/kogitoserviceutils.go
  test/framework/kubernetes.go
  test/framework/mappers/cr_to_cli.go
  test/framework/openshift_resources.go
  test/scripts/examples/kogito-travel-agency.feature
  test/scripts/examples/onboarding-example.feature
  test/scripts/examples/process-timer-quarkus.feature
  test/scripts/examples/process-timer-springboot.feature
  test/scripts/examples/ruleunit-quarkus-example.feature
  test/steps/data.go
  test/steps/image_registry.go
  test/steps/infinispan.go
  test/steps/kogitoapp.go
  test/steps/kogitobuild.go
  test/steps/kogitojobsservice.go
  test/steps/kogitoruntime.go
  test/steps/kubernetes.go
  test/steps/mappers/check_resource_requirements.go
  test/steps/mappers/create_infinispan_instance.go
  test/steps/mappers/create_kogito_build.go
  test/steps/mappers/create_kogito_service.go
  test/steps/mappers/shared_functions.go
  test/steps/openshift.go
  test/steps/utils.go
  test/types/holder.go
Labels: bdd-tests 🧪, operator :cloud:, ready :rocket:

#475 [KOGITO-1654] - Guide for Core/Runtimes team to Smoke test local changes on Kubernetes
  README.md
  docs/GUIDE_TO_KOGITO_DEVS.md
Labels: ready :rocket:

#495 [KOGITO-2978] Run all non native BDD tests in Kogito PR check
  Jenkinsfile
Labels: CI/CD :loop:, bdd-tests 🧪, ready :rocket:

#496 [KOGITO-2957] Considering K_SINK env var when comparing Deployments
  pkg/framework/comparator.go
  pkg/framework/comparator_test.go
Labels: ready :rocket:

#501 [KOGITO-3005] Add exe extension to Windows CLI
  hack/go-build-cli.sh
Labels: needs review :mag:

#498 [KOGITO-2999] BDD tests: Disable optaplanner native
  test/features/deploy_kogito_runtime.feature
  test/scripts/examples/process-optaplanner-quarkus.feature
Labels: bdd-tests 🧪, needs review :mag:

#420 [KOGITO-2290][KOGITO-2291] Setup stages for release
  Jenkinsfile.deploy
  Jenkinsfile.promote
  Makefile
Labels: CI/CD :loop:, ready :rocket:

#494 KOGITO-2355: BDD tests: Test Jobs service using external Infinispan and Kafka connection
  test/features/install_jobs_service.feature
Labels: bdd-tests 🧪, ready :rocket:

#506 [KOGITO-3025] Disable native binary build test
  test/features/deploy_kogito_build.feature
Labels: bdd-tests 🧪, needs review :mag:

#505 Update comments.yml for jenkins tests
  .github/bot-files/comments.yml
Labels: ready :rocket:

#513 KOGITO-3052: Allow to see the exception stacktrace.
  test/steps/data.go
Labels: bdd-tests 🧪, ready :rocket:

#508 [KOGITO-3032] - Ignoring any injected variables on PodSpecTemplate
  pkg/framework/comparator.go
  pkg/framework/comparator_test.go
  pkg/framework/env_var.go
  pkg/framework/env_var_test.go
Labels: ready :rocket:

#510 [KOGITO-2888] Cleanup old pipeline(s)
  Jenkinsfile.nightly
Labels: CI/CD :loop:, needs review :mag:

#493 [KOGITO-2966] Tests: Remove Strimzi workaround
  test/steps/data.go
Labels: bdd-tests 🧪, needs review :mag:

#507 [KOGITO-3030] Tests: Retry image build in case of failure
  test/framework/command.go
  test/framework/container_engine.go
Labels: bdd-tests 🧪, needs review :mag:

#512 [KOGITO-3045] Set image's deployment properties
  Jenkinsfile.deploy
Labels: ready :rocket:

#497 [KOGITO-2988] BDD: Revert detection for docker build
  test/framework/dockerfile_provider.go
Labels: bdd-tests 🧪, needs review :mag:

#514 [KOGITO-3061] BDD: Correct invalid pointer reference
  test/framework/kubernetes.go
Labels: bdd-tests 🧪, needs review :mag:

#516 [KOGITO-3063] Redirecting kogito CLI default output to stdout
  cmd/kogito/command/command.go
  cmd/kogito/command/context/logger.go
  pkg/logger/logger.go
Labels: cli 💻, operator :cloud:, ready :rocket:

#515 [KOGITO-3050] - Fixing from file build trigger
  cmd/kogito/command/deploy/delete_service.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/message/kogitobuild.go
  cmd/kogito/command/service/build_service.go
  cmd/kogito/command/service/runtime_service.go
  pkg/client/openshift/buildconfig.go
  pkg/client/openshift/buildconfig_test.go
  pkg/controller/kogitobuild/build/image_stream_kogito.go
  pkg/controller/kogitobuild/kogitobuild_controller.go
  pkg/test/client.go
  pkg/test/fake_build.go
Labels: cli 💻, operator :cloud:, ready :rocket:

#511 [KOGITO-3044] Improve build images time in deploy
  Jenkinsfile.deploy
Labels: CI/CD :loop:, ready :rocket:

#503 [KOGITO-2871] - Remove deprecated properties from kogito-cloud-operator
  pkg/infrastructure/services/infinispan.go
  pkg/infrastructure/services/infinispan_test.go
Labels: needs review :mag:, operator :cloud:

#437 Kogito 2707 - trusty operator
  Makefile
  README.md
  cmd/kogito/command/install/factory.go
  cmd/kogito/command/install/trusty.go
  cmd/kogito/command/install/trusty_test.go
  cmd/kogito/command/message/trusty.go
  cmd/kogito/command/shared/install_operator_test.go
  cmd/kogito/command/shared/install_services.go
  deploy/crds/app.kiegroup.org_kogitotrusties_crd.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitotrusty_cr.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitotrusties_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/kogito-operator.v1.0.0-snapshot.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitotrusties_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  examples/trusty.yaml
  go.mod
  go.sum
  hack/run-tests.sh
  hack/run-tests.sh.bats
  pkg/apis/app/v1alpha1/kogitotrusty_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_kogitotrusty.go
  pkg/controller/kogitotrusty/kogitotrusty_controller.go
  pkg/controller/kogitotrusty/kogitotrusty_controller_test.go
  pkg/infrastructure/data_index.go
  pkg/infrastructure/data_index_test.go
  pkg/infrastructure/kogito_service.go
  pkg/infrastructure/kogito_service_test.go
  pkg/infrastructure/trusty.go
  pkg/infrastructure/trusty_test.go
  pkg/test/assert_fetch.go
  test/config/config.go
  test/features/install_trusty.feature
  test/features/olm/cli_install_operator.feature
  test/features/olm/cli_new_project.feature
  test/features/olm/cli_use_project.feature
  test/framework/kogitotrusty.go
  test/scripts/examples/dmn-tracing-quarkus.feature
  test/steps/data.go
  test/steps/kogitotrusty.go
Labels: bdd-tests 🧪, cli 💻, operator :cloud:, ready :rocket:

#523 [KOGITO-3103] Improve writing new BDD tests doc
  test/README.md
Labels: bdd-tests 🧪, ready :rocket:

#525 [KOGITO-3132] Correct set test config on release
  Jenkinsfile.deploy
  Jenkinsfile.promote
Labels: ready :rocket:

#526 [KOGITO-2860] Pipeline to copy manifests from release branch to master
  Jenkinsfile.copy_csv_files
Labels: CI/CD :loop:, ready :rocket:

#529 [KOGITO-3149] Correct copy manifest files pipeline
  Jenkinsfile.copy_csv_files
Labels: needs review :mag:

#533 KOGITO-1265: Enable Jobs-service integration with Kogito test when bl…
  test/features/deploy_kogito_runtime.feature
  test/framework/kogitojobsservice.go
  test/framework/kubernetes.go
  test/steps/kogitojobsservice.go
Labels: bdd-tests 🧪, ready :rocket:

#532 [KOGITO-3170] Tests: Concurrent map writes error in pod log collector
  test/framework/logging.go
Labels: bdd-tests 🧪, ready :rocket:

#541 KOGITO-3058: Improve DEBUG option
  test/framework/logging.go
Labels: bdd-tests 🧪, needs review :mag:

#540 KOGITO-3000: BDD tests: Enable optaplanner native test
  test/features/deploy_kogito_runtime.feature
  test/scripts/examples/process-optaplanner-quarkus.feature
Labels: bdd-tests 🧪, ready :rocket:

#542 Delete paths.yml until upstream issue is resolved
  .github/bot-files/paths.yml
Labels: needs review :mag:
