Repository kiegroup/kogito-operator, pull requests merged in 2020-10, with the labels that each got.

#588 [KOGITO-3127] Set the `replaces` correctly in csv
  .github/workflows/Kogito-Operator-PR-Check.yaml
  hack/bump-version.sh
  hack/bump-version.sh.bats
Labels: ready :rocket:

#592 [KOGITO-3433] - Update Graalvm version to 20.2.0
  RELEASE_NOTES.md
Labels: needs review :mag:

#594 [KOGITO-3514] BDD: switch to docker container engine
  Jenkinsfile.deploy
Labels: needs review :mag:

#593 [KOGITO-3502] - Sasl mechanism no longer set by Kogito operator
  examples/data-index.yaml
  examples/explainability.yaml
  examples/jobs-service.yaml
  examples/process-quarkus-example-persistence.yaml
  examples/travelapp-kogito-travel-agency.yaml
  examples/travelapp-kogito-visas.yaml
  examples/trusty.yaml
  pkg/controller/kogitoinfra/infinispan/infinispan_properties.go
  pkg/controller/kogitoinfra/kogitoinfra_controller_test.go
Labels: operator :cloud:, ready :rocket:

#598 [KOGITO-3516] Services now listen to default HTTP port
  hack/go-vet.sh
  pkg/controller/kogitodataindex/kogitodataindex_controller_test.go
  pkg/controller/kogitoexplainability/kogitoexplainability_controller_test.go
  pkg/controller/kogitoinfra/kogitoinfra_controller_test.go
  pkg/controller/kogitotrusty/kogitotrusty_controller_test.go
  pkg/framework/containers.go
  pkg/infrastructure/services/route.go
Labels: hacktoberfest, hacktoberfest-accepted, needs review :mag:, operator :cloud:

#599 [KOGITO-3543] - Wrong environment values for Kogito Services after re…
  pkg/infrastructure/services/deployment.go
Labels: hacktoberfest, hacktoberfest-accepted, needs review :mag:, operator :cloud:

#603 [0.16.x][KOGITO-3543] - Wrong environment values for Kogito Services after re…
  pkg/infrastructure/services/deployment.go
Labels: operator :cloud:, ready :rocket:

#597 KOGITO-3280: Cucumber Tests: Add test for management-console with Key…
  test/features/keycloak.feature
Labels: bdd-tests 🧪, hacktoberfest, hacktoberfest-accepted, ready :rocket:

#601 KOGITO-3552: BDD tests: Enable Trusty - Keycloak test
  test/features/keycloak.feature
Labels: bdd-tests 🧪, hacktoberfest, hacktoberfest-accepted, ready :rocket:

#595 [KOGITO-3510] Deploy/Promote pIpelines: set credentials as params
  Jenkinsfile.deploy
  Jenkinsfile.promote
Labels: ready :rocket:

#608 Fix EXAMPLES_DIR path
  examples/kubernetes/travel-agency/deploy.sh
Labels: needs review :mag:

#610 [KOGITO-3481] - Review runtime specific configuration by operator
  cmd/kogito/command/converter/config_converter.go
  cmd/kogito/command/converter/config_converter_test.go
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/flag/config_flag.go
  cmd/kogito/command/flag/install_flag.go
  cmd/kogito/command/flag/runtime_flag.go
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/explainability.go
  cmd/kogito/command/install/jobs_service.go
  cmd/kogito/command/install/jobs_service_test.go
  cmd/kogito/command/install/mgmt_console.go
  cmd/kogito/command/install/trusty.go
  cmd/kogito/command/install/trusty_ui.go
  cmd/kogito/command/service/runtime_service.go
  deploy/crds/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/crds/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/crds/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/crds/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/crds/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/crds/app.kiegroup.org_kogitotrusties_crd.yaml
  deploy/crds/app.kiegroup.org_kogitotrustyuis_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitotrusties_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitotrustyuis_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/kogito-operator.v1.0.0-snapshot.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitotrusties_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitotrustyuis_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  pkg/apis/app/v1alpha1/kogitojobsservice_types.go
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/kogitojobsservice/kogitojobsservice_controller.go
  pkg/infrastructure/services/resources.go
Labels: CI/CD :loop:, cli 💻, operator :cloud:

#609 [KOGITO-3579] - travel-agency example not updated to reflect infrastr…
  deploy/crds/app.kiegroup.org_v1alpha1_kogitoinfra_cr.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/kogito-operator.v1.0.0-snapshot.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  examples/data-index.yaml
  examples/kubernetes/travel-agency/data-index.yaml
  examples/kubernetes/travel-agency/kogito-travels.yaml
  examples/kubernetes/travel-agency/kogito-visas.yaml
  examples/kubernetes/travel-agency/management-console.yaml
  examples/travelapp-kogito-travel-agency.yaml
  pkg/apis/app/v1alpha1/kogitoinfra_types.go
Labels: hacktoberfest, hacktoberfest-accepted, operator :cloud:, ready :rocket:

#611 [KOGITO-3586] BDD tests should have unique namespace
  test/steps/data.go
Labels: bdd-tests 🧪, needs review :mag:

#612 [KOGITO-2986] Remove controller package dependency in tests
  cmd/kogito/command/flag/infraresource_flag.go
  cmd/kogito/command/install/kogito_infra_test.go
  pkg/controller/kogitobuild/build/image_stream_kogito.go
  pkg/controller/kogitobuild/build/image_stream_kogito_test.go
  pkg/controller/kogitobuild/build/manager_test.go
  pkg/controller/kogitobuild/kogitobuild_controller_test.go
  pkg/controller/kogitoinfra/infinispan/infinispan_reconciler.go
  pkg/controller/kogitoinfra/infinispan/resource.go
  pkg/controller/kogitoinfra/kafka/kafka_reconciler.go
  pkg/controller/kogitoinfra/kafka/resource.go
  pkg/controller/kogitoinfra/keycloak/keyclock_reconciler.go
  pkg/controller/kogitoinfra/keycloak/resource.go
  pkg/controller/kogitoinfra/kogitoinfra_controller_test.go
  pkg/controller/kogitoinfra/kogitoinfra_service.go
  pkg/infrastructure/infinispan.go
  pkg/infrastructure/kafka.go
  pkg/infrastructure/keycloak.go
  pkg/infrastructure/kogito_images.go
  pkg/infrastructure/services/kafka.go
  pkg/infrastructure/services/kafka_test.go
  test/framework/dockerfile_provider.go
  test/framework/kogitobuild.go
  test/framework/kogitoinfra.go
  test/steps/kafka.go
Labels: bdd-tests 🧪, cli 💻, needs review :mag:, operator :cloud:

#613 [KOGITO-3465] BDD tests: Handle self-signed certificate
  Jenkinsfile
  Jenkinsfile.deploy
  Makefile
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/config/config.go
  test/framework/kogitobuild.go
Labels: CI/CD :loop:, bdd-tests 🧪, needs review :mag:

#616 [KOGITO-3579] - travel-agency example not updated to reflect infrastr…
  examples/kubernetes/travel-agency/data-index.yaml
  examples/kubernetes/travel-agency/deploy.sh
  examples/kubernetes/travel-agency/kogito-travels.yaml
  examples/kubernetes/travel-agency/kogito-visas.yaml
  examples/kubernetes/travel-agency/management-console.yaml
Labels: ready :rocket:

#622 [0.17.x] Cherry-pick manifests version 0.16.0
  deploy/olm-catalog/kogito-operator/0.16.0/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/olm-catalog/kogito-operator/0.16.0/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.16.0/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/olm-catalog/kogito-operator/0.16.0/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/olm-catalog/kogito-operator/0.16.0/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.16.0/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/0.16.0/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/0.16.0/app.kiegroup.org_kogitotrusties_crd.yaml
  deploy/olm-catalog/kogito-operator/0.16.0/app.kiegroup.org_kogitotrustyuis_crd.yaml
  deploy/olm-catalog/kogito-operator/0.16.0/kogito-operator.v0.16.0.clusterserviceversion.yaml
Labels: needs review :mag:

#629 KOGITO-3711: BDD tests: Unable to find latest tagged image
  test/steps/openshift.go
Labels: bdd-tests 🧪, ready :rocket:

#630 [KOGITO-3568] - Remove spec.httpPort attribute from Operator and HTTP…
  RELEASE_NOTES.md
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/flag/install_flag.go
  cmd/kogito/command/install/supportingservices.go
  cmd/kogito/command/install/supportingservices_test.go
  cmd/kogito/command/service/runtime_service.go
  deploy/crds/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/crds/app.kiegroup.org_kogitosupportingservices_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitosupportingservices_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitosupportingservices_crd.yaml
  examples/data-index-mongodb.yaml
  examples/data-index.yaml
  examples/explainability.yaml
  examples/trusty.yaml
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/kogitosupportingservice/explainability_reconciler_test.go
  pkg/controller/kogitosupportingservice/kogitodataindex_controller_test.go
  pkg/controller/kogitosupportingservice/trustyai_reconciler_test.go
  pkg/infrastructure/services/deployment.go
  pkg/infrastructure/services/deployment_test.go
  pkg/infrastructure/services/probe.go
  test/features/update_httpport.feature
  test/framework/kubernetes.go
  test/framework/mappers/cr_to_cli.go
  test/steps/mappers/create_kogito_service.go
Labels: bdd-tests 🧪, cli 💻, operator :cloud:, ready :rocket:

#635 [KOGITO-3715] Kogito Operator installer bundle
  Jenkinsfile.promote
  README.md
  hack/go-vet.sh
  hack/install.sh
  kogito-operator.yaml
Labels: CI/CD :loop:, ready :rocket:

#634 Fixing grammar errors
  .github/pull_request_template.md
Labels: needs review :mag:

#614 [KOGITO-3376] Update protobuf ConfigMap using fetched files
  RELEASE_NOTES.md
  pkg/controller/kogitoruntime/deployer.go
  pkg/controller/kogitoruntime/kogitoruntime_controller_test.go
  pkg/infrastructure/kogito_service.go
  pkg/infrastructure/kogito_service_test.go
  pkg/infrastructure/services/dashboards.go
  pkg/infrastructure/services/deployment.go
  pkg/infrastructure/services/messaging.go
  pkg/infrastructure/services/prometheus.go
Labels: needs review :mag:, operator :cloud:

#633 [KOGITO-3708] - Decreasing the amount of reconciliation loops for Kog…
  RELEASE_NOTES.md
  examples/kogitoinfra-infinispan.yaml
  examples/kogitoinfra-kafka.yaml
  examples/kogitoinfra-keycloak.yaml
  hack/go-vet.sh
  kogito-operator.yaml
  pkg/controller/kogitoinfra/errors.go
  pkg/controller/kogitoinfra/kogitoinfra_controller.go
  pkg/controller/kogitoinfra/kogitoinfra_controller_test.go
  pkg/controller/kogitoinfra/manage_status.go
Labels: needs review :mag:, operator :cloud:, ready :rocket:

#642 Debugging gen manifest status
  .github/workflows/Kogito-Operator-PR-Check.yaml
  hack/go-vet.sh
  kogito-operator.yaml
Labels: ready :rocket:
