Repository kiegroup/kogito-operator, pull requests merged in 2020-06, with the labels that each got.

#363 [KOGITO-2329] Implement image cache support for KogitoRuntime tests
  Makefile
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/config/config.go
  test/features/deploy_kogito_runtime.feature
  test/framework/container_engine.go
  test/framework/kogitoruntime.go
  test/steps/image_registry.go
  test/steps/kogitoruntime.go
Labels: bdd-tests 🧪, ready :rocket:

#367 [KOGITO-2350] Cleanup stuck namespaces (infinispan)
  hack/clean-stuck-namespaces.sh
  hack/run-tests.sh
Labels: needs review :mag:

#353 [KOGITO-1861] - Make possible to turn the Maven downloading process output off during s2i builds
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/deploy/deploy_service_test.go
  deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitoapp_cr.yaml
  deploy/examples/example-custom-build-images.yaml
  deploy/examples/onboarding-example.yaml
  deploy/examples/process-quarkus-example-persistence.yaml
  deploy/examples/process-quarkus-example.yaml
  deploy/examples/travelapp-kogito-travel-agency.yaml
  deploy/examples/travelapp-kogito-visas.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/kogito-operator.v0.11.0.clusterserviceversion.yaml
  pkg/apis/app/v1alpha1/kogitoapp_types.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/kogitoapp/resource/build_config_s2i.go
  pkg/controller/kogitoapp/resource/build_config_s2i_test.go
Labels: ready :rocket:

#347 [KOGITO-1503] Replace Kafka and Infinispan environment variable configuration with ConfigMap
  README.md
  go.mod
  pkg/controller/kogitoapp/kogitoapp_controller.go
  pkg/controller/kogitoapp/kogitoapp_controller_test.go
  pkg/controller/kogitoapp/resource/deployed_resources.go
  pkg/controller/kogitoapp/resource/deployed_resources_test.go
  pkg/controller/kogitoapp/resource/deployment_config.go
  pkg/controller/kogitoapp/resource/deployment_config_test.go
  pkg/controller/kogitoapp/resource/infinispan.go
  pkg/controller/kogitoapp/resource/infinispan_test.go
  pkg/controller/kogitoapp/resource/kafka.go
  pkg/controller/kogitoapp/resource/kafka_test.go
  pkg/controller/kogitoapp/resource/requested_resources.go
  pkg/controller/kogitoapp/resource/requested_resources_test.go
  pkg/controller/kogitoapp/resource/resource_comparator.go
  pkg/controller/kogitoapp/resource/util_test.go
  pkg/framework/image_metadata.go
  pkg/infrastructure/services/configmap.go
  pkg/infrastructure/services/configmap_test.go
  pkg/infrastructure/services/deployer.go
  pkg/infrastructure/services/infinispan.go
  pkg/infrastructure/services/infinispan_test.go
  pkg/infrastructure/services/kafka.go
  pkg/infrastructure/services/kafka_test.go
  pkg/infrastructure/services/resources.go
  pkg/infrastructure/services/resources_test.go
  pkg/util/maps_test.go
Labels: needs review :mag:

#372 [KOGITO-2369] Correct deploy files tests with test config
  test/framework/kogitodeployfiles.go
Labels: bdd-tests 🧪, needs review :mag:

#371 [KOGITO-2351] - Integrate golint with PR checks on kogito-cloud-opera…
  .circleci/config.yml
  cmd/kogito/command/common/operator_flag.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/shared/kogitochannels.go
  hack/go-lint.sh
  pkg/apis/app/v1alpha1/kogitoapp_types.go
  pkg/controller/kogitoapp/resource/build_config_s2i.go
  pkg/controller/kogitoapp/resource/build_config_s2i_test.go
  test/framework/kogitoinfra.go
Labels: needs review :mag:

#370 [KOGITO-2358] Add a scenario for optaplanner-quarkus on OpenShift
  test/features/deploy_kogito_runtime.feature
Labels: bdd-tests 🧪, needs review :mag:

#365 [KOGITO-2254] - Integrate Kogito Operator CI PR check with GolangCI-Lint
  .circleci/config.yml
  cmd/kogito/command/completion/completion.go
  cmd/kogito/command/install/kogito_operator_test.go
  cmd/kogito/command/message/kogitoapp.go
  cmd/kogito/command/project/new_project_test.go
  cmd/kogito/command/shared/install_services.go
  cmd/kogito/command/util/build_from_file.go
  cmd/kogito/command/util/build_from_file_test.go
  pkg/apis/app/v1alpha1/kogitoapp_types.go
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  pkg/apis/app/v1alpha1/types.go
  pkg/controller/kogitoapp/resource/build_config_s2i.go
  pkg/controller/kogitoapp/resource/deployment_config_test.go
  pkg/controller/kogitoapp/resource/infinispan.go
  pkg/controller/kogitoapp/resource/kafka.go
  pkg/controller/kogitoapp/resource/requested_resources_test.go
  pkg/controller/kogitoapp/resource/service.go
  pkg/controller/kogitoapp/test/crd_validation_test.go
  pkg/controller/kogitoinfra/infinispan/infinispan_credentials.go
  pkg/controller/kogitoinfra/infinispan/infinispan_credentials_test.go
  pkg/controller/kogitoinfra/infinispan/resource.go
  pkg/controller/kogitoinfra/infinispan/resource_test.go
  pkg/controller/kogitoinfra/kogitoinfra_controller.go
  pkg/controller/kogitoinfra/status/manage_status.go
  pkg/controller/kogitojobsservice/kogitojobsservice_controller.go
  pkg/controller/kogitoruntime/kogitoruntime_controller_test.go
  pkg/framework/comparator.go
  pkg/framework/env_var.go
  pkg/infrastructure/data_index.go
  pkg/infrastructure/data_index_test.go
  pkg/infrastructure/infinispan.go
  pkg/infrastructure/jobs_service.go
  pkg/infrastructure/kafka.go
  pkg/infrastructure/kogito_images.go
  pkg/infrastructure/kogitoinfra.go
  pkg/infrastructure/services/deployer.go
  pkg/infrastructure/services/deployer_test.go
  pkg/infrastructure/services/infinispan.go
  pkg/infrastructure/services/infinispan_test.go
  pkg/infrastructure/services/kafka.go
  pkg/infrastructure/services/resources.go
  pkg/logger/logger.go
  pkg/util/maps.go
  test/framework/http.go
  test/framework/kogitoapp.go
  test/framework/kogitojobsservice.go
  test/framework/kogitoserviceutils.go
  test/framework/logging.go
  test/framework/operator.go
  test/framework/util.go
  test/main_test.go
  test/scripts/prune_namespaces.go
  test/steps/data.go
  test/steps/kogitodataindex.go
  test/steps/kubernetes.go
Labels: ready :rocket:

#376 [KOGITO-2395] Adjust formatting to follows Go lang standards
  cmd/kogito/command/completion/completion.go
  cmd/kogito/command/util/build_from_file.go
  hack/clean-stuck-namespaces.sh
  pkg/apis/app/v1alpha1/kogitoapp_types.go
  pkg/controller/kogitoapp/test/crd_validation_test.go
  pkg/controller/kogitoinfra/infinispan/infinispan_credentials.go
  pkg/controller/kogitoinfra/infinispan/infinispan_credentials_test.go
  pkg/controller/kogitoinfra/infinispan/resource.go
  pkg/controller/kogitoinfra/infinispan/resource_test.go
  pkg/controller/kogitoinfra/kogitoinfra_controller.go
  pkg/controller/kogitojobsservice/kogitojobsservice_controller.go
  pkg/infrastructure/infinispan.go
  pkg/infrastructure/kogitoinfra.go
  pkg/infrastructure/services/deployer.go
  pkg/infrastructure/services/deployer_test.go
  pkg/logger/logger.go
Labels: ready :rocket:

#366 [KOGITO-2330] Unify parsing of configuration table for Kogito services
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  test/features/deploy_kogito_runtime.feature
  test/features/install_jobs_service.feature
  test/framework/kogitodataindex.go
  test/framework/kogitojobsservice.go
  test/framework/kogitomgmtconsole.go
  test/framework/kogitoruntime.go
  test/framework/kogitoserviceutils.go
  test/steps/kogito_service_table_parser.go
  test/steps/kogitodataindex.go
  test/steps/kogitojobsservice.go
  test/steps/kogitoruntime.go
Labels: bdd-tests 🧪, ready :rocket:

#379 KOGITO-2405: Fix info logs
  cmd/manager/main.go
Labels: ready :rocket:

#385 KOGITO-2162: Revert workaround
  test/framework/kubernetes.go
  test/framework/openshift.go
Labels: bdd-tests 🧪, needs review :mag:

#383 [KOGITO-2412] Updated paths for travel agency test
  test/features/deploy_travel_agency.feature
Labels: bdd-tests 🧪, ready :rocket:

#375 [BXMSDOC-5580] Migrate operator doc content to Kogito docs.
  README.md
  docs/ARCHITECTURE.MD
  docs/CONTRIBUTING.MD
  docs/img/catalog-kogito-operator.png
  docs/img/installed-kogito-operator.png
  docs/img/kogito_operator_packages.png
  docs/img/prometheus_graph.png
  docs/img/prometheus_target.png
Labels: on hold :hand:, ready :rocket:

#377 [KOGITO-2396] - Integrate `golangci-lint` in `hack/go-lint.sh`
  .circleci/config.yml
  README.md
  hack/go-lint.sh
Labels: ready :rocket:

#388 [KOGITO-2396] - Integrate `golangci-lint` in `hack/go-lint.sh`
  hack/go-lint.sh
Labels: needs review :mag:

#362 KOGITO-2327: KogitoRuntime Support in Kubernetes
  Makefile
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  pkg/client/client.go
  pkg/client/meta/meta.go
  test/config/config.go
  test/framework/check_setup.go
  test/framework/http.go
  test/framework/kogitoruntime.go
  test/framework/kogitoserviceutils.go
  test/framework/kubernetes.go
  test/framework/openshift.go
  test/framework/operator.go
  test/main_test.go
  test/steps/graphql.go
  test/steps/http.go
  test/steps/operator.go
  test/steps/process.go
  test/steps/prometheus.go
  test/steps/task.go
Labels: bdd-tests 🧪, ready :rocket:

#389 [KOGITO-2406] - Add Test Coverage to the Operator PR check CI
  .circleci/config.yml
  hack/coverage.sh
  hack/go-lint.sh
Labels: ready :rocket:

#369 [KOGITO-1957][KOGITO-2359] Setup a specific repository on local maven & S2I builds
  Jenkinsfile.deploy
  Makefile
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/config/config.go
  test/framework/kogitoapp.go
  test/framework/maven.go
  test/steps/maven.go
Labels: needs review :mag:

#394 [KOGITO-1946] - Release Kogito Operator/CLI 0.11.0
  deploy/examples/kubernetes/travel-agency/data-index.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/kogito-operator.v0.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/custom-subscription-example.yaml
  test/.default_config
Labels: needs review :mag:

#391 [KOGITO-1946] - Release Kogito Operator/CLI 0.11.0
  .osdk-scorecard.yaml
  README.md
  cmd/kogito/version/version.go
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/kogito-operator.v0.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/kogito-operator.package.yaml
  deploy/operator.yaml
  hack/go-build.sh
  hack/go-vet.sh
  version/version.go
Labels: ready :rocket:

#395 [KOGITO-2504] - Check headers on files on PR check on kogito-cloud-op…
  .circleci/config.yml
  hack/go-fmt.sh
  test/framework/logging.go
  test/framework/openshift_resources.go
  test/framework/util.go
  test/main_test.go
  test/steps/data.go
  test/steps/kogitodataindex.go
  test/steps/kubernetes.go
Labels: ready :rocket:

#396 KOGITO-2477: Deploy files for spring boot
  test/features/deploy_source_files.feature
  test/steps/deploy_files.go
Labels: bdd-tests 🧪, ready :rocket:

#398 [KOGITO-2524] - Renaming install script command to fit k8s docs
  hack/install.sh
Labels: ready :rocket:

#368 [KOGITO-1999] - Introducing KogitoBuild
  cmd/kogito/command/shared/install_operator_test.go
  deploy/crds/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitobuild_cr.yaml
  deploy/examples/process-quarkus-example-runtime-build.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/kogito-operator.v0.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/kogito-operator.v0.12.0.clusterserviceversion.yaml
  pkg/apis/app/v1alpha1/kogitobuild_types.go
  pkg/apis/app/v1alpha1/types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/client/client.go
  pkg/client/meta/meta.go
  pkg/client/openshift/buildconfig.go
  pkg/controller/add_kogitobuild.go
  pkg/controller/kogitoapp/build/trigger.go
  pkg/controller/kogitoapp/kogitoapp_controller.go
  pkg/controller/kogitoapp/kogitoapp_controller_test.go
  pkg/controller/kogitoapp/resource/build_config.go
  pkg/controller/kogitoapp/resource/kogito_imagestream_test.go
  pkg/controller/kogitobuild/build/build_config.go
  pkg/controller/kogitobuild/build/image_stream.go
  pkg/controller/kogitobuild/build/image_stream_kogito.go
  pkg/controller/kogitobuild/build/image_stream_kogito_test.go
  pkg/controller/kogitobuild/build/log.go
  pkg/controller/kogitobuild/build/manager.go
  pkg/controller/kogitobuild/build/manager_build_binary.go
  pkg/controller/kogitobuild/build/manager_build_source.go
  pkg/controller/kogitobuild/build/manager_test.go
  pkg/controller/kogitobuild/build/trigger.go
  pkg/controller/kogitobuild/build/trigger_test.go
  pkg/controller/kogitobuild/build/utils.go
  pkg/controller/kogitobuild/kogitobuild_controller.go
  pkg/controller/kogitobuild/kogitobuild_controller_test.go
  pkg/controller/kogitobuild/status.go
  pkg/controller/kogitobuild/status_test.go
  pkg/controller/kogitodataindex/kogitodataindex_controller_test.go
  pkg/controller/kogitoruntime/kogitoruntime_controller.go
  pkg/framework/comparator.go
  pkg/framework/owner.go
  pkg/framework/owner_test.go
  pkg/infrastructure/kogito_images.go
  pkg/infrastructure/kogito_images_test.go
  pkg/infrastructure/services/deployer.go
  pkg/infrastructure/services/deployment_test.go
  pkg/infrastructure/services/image.go
  pkg/infrastructure/services/image_test.go
  pkg/infrastructure/services/manage_status.go
  pkg/infrastructure/services/resources.go
  pkg/infrastructure/services/resources_test.go
  pkg/test/assert_fetch.go
  pkg/test/client.go
  pkg/test/io.go
  pkg/test/io_test.go
  test/framework/kogitoserviceutils.go
  test/framework/openshift.go
  test/framework/util.go
Labels: needs review :mag:

#400 [KOGITO-1584] - Integrate Operator with Events API
  pkg/infrastructure/record/event.go
  pkg/infrastructure/record/event_test.go
  pkg/infrastructure/record/log.go
  pkg/infrastructure/services/deployer.go
Labels: needs review :mag:

#378 [KOGITO-1336] - Improve the exposed HTTP port configuration for Kogito Runtime Services
  cmd/kogito/command/deploy/common.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/data_index_test.go
  cmd/kogito/command/install/jobs_service.go
  cmd/kogito/command/install/jobs_service_test.go
  cmd/kogito/command/install/mgmt_console.go
  cmd/kogito/command/install/mgmt_console_test.go
  deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/crds/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/crds/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/crds/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/crds/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/app.kiegroup.org_kogitoruntimes_crd.yaml
  pkg/apis/app/v1alpha1/kogitodataindex_types.go
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/kogitoapp/resource/deployment_config.go
  pkg/controller/kogitoapp/resource/deployment_config_test.go
  pkg/controller/kogitodataindex/kogitodataindex_controller.go
  pkg/controller/kogitodataindex/kogitodataindex_controller_test.go
  pkg/infrastructure/services/deployment.go
  pkg/infrastructure/services/deployment_test.go
  pkg/infrastructure/services/probe.go
Labels: on hold :hand:

#402 [KOGITO-2535] Fix ImageStream name when custom image is given
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitoruntimes_crd.yaml
  pkg/controller/kogitobuild/build/image_stream.go
  pkg/controller/kogitobuild/kogitobuild_controller_test.go
  pkg/controller/kogitojobsservice/kogitojobsservice_controller_test.go
  pkg/controller/kogitomgmtconsole/kogitomgmtconsole_controller_test.go
  pkg/controller/kogitoruntime/kogitoruntime_controller_test.go
  pkg/infrastructure/services/image.go
  pkg/infrastructure/services/resources.go
  pkg/test/reconciler.go
Labels: ready :rocket:

#403 KOGITO-2466: BDD tests: Update Port in Ingress for KogitoRuntime
  test/framework/check_setup.go
  test/framework/kogitoruntime.go
  test/framework/kogitoserviceutils.go
  test/framework/kubernetes.go
Labels: bdd-tests 🧪, needs review :mag:

#405 [KOGITO-2550] - Fail CI if change in CRDs when running operator-sdk g…
  .circleci/config.yml
  hack/go-vet.sh
Labels: needs review :mag:

#373 [KOGITO-2278] Add option to mark Kogito image streams as insecure
  cmd/kogito/command/deploy/common.go
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/data_index_test.go
  cmd/kogito/command/install/jobs_service.go
  cmd/kogito/command/install/jobs_service_test.go
  cmd/kogito/command/install/mgmt_console.go
  cmd/kogito/command/install/mgmt_console_test.go
  deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/crds/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/crds/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/crds/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/crds/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitoruntimes_crd.yaml
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/infrastructure/services/image.go
  pkg/infrastructure/services/image_test.go
  test/framework/kogitoruntime.go
  test/framework/kogitoserviceutils.go
Labels: ready :rocket:

#406 [KOGITO-2404] Fix WARN when registering OpenShift components on k8s
  pkg/client/client.go
  pkg/framework/controller_watcher.go
Labels: needs review :mag:

#407 [KOGITO-2551] - Review docs links and wording for CSV and CLI command
  cmd/kogito/command/deploy/delete_service.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/jobs_service.go
  cmd/kogito/command/message/kogitoapp.go
  deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/crds/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/crds/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/crds/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/crds/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/crds/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/crds/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/kogito-operator.v0.12.0.clusterserviceversion.yaml
  pkg/apis/app/v1alpha1/kogitoapp_types.go
  pkg/apis/app/v1alpha1/kogitobuild_types.go
  pkg/apis/app/v1alpha1/kogitodataindex_types.go
  pkg/apis/app/v1alpha1/kogitoinfra_types.go
  pkg/apis/app/v1alpha1/kogitojobsservice_types.go
  pkg/apis/app/v1alpha1/kogitomgmtconsole_types.go
  pkg/apis/app/v1alpha1/kogitoruntime_types.go
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  pkg/apis/app/v1alpha1/types.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/kogitobuild/build/utils.go
Labels: ready :rocket:

#408 [KOGITO-2560] Workaround for stuck zookeeper
  test/framework/kubernetes.go
  test/framework/logging.go
  test/steps/data.go
Labels: bdd-tests 🧪, needs review :mag:

#397 [KOGITO-2090] Integrate KogitoBuild in tests
  test/features/deploy_kogito_build.feature
  test/framework/kogitobuild.go
  test/framework/kogitoserviceutils.go
  test/steps/data.go
  test/steps/kogitobuild.go
  test/steps/kogitoruntime.go
  test/steps/openshift.go
Labels: bdd-tests 🧪, ready :rocket:

#411 [KOGITO-2590] SkipTests is ignored in maven.go
  test/framework/maven.go
Labels: bdd-tests 🧪, ready :rocket:

#409 [KOGITO-1906] - Create test to target incremental builds with operator
  pkg/controller/kogitobuild/build/build_config_test.go
Labels: needs review :mag:

#412 [KOGITO-2527] - Upgrade Operator Golang to 1.14
  .circleci/config.yml
  README.md
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  go.mod
  go.sum
Labels: ready :rocket:
