Repository kiegroup/kogito-operator, pull requests merged in 2020-11, with the labels that each got.

#645 Drop Jose from test reviewers
  .github/bot-files/reviewers.yml
Labels: needs review :mag:

#638 [KOGITO-3556] Kogito CRs to update Status only
  RELEASE_NOTES.md
  cmd/kogito/command/install/supportingservices.go
  cmd/kogito/command/remove/supportingservices.go
  cmd/kogito/command/shared/install_services.go
  deploy/crds/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/crds/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/crds/app.kiegroup.org_kogitosupportingservices_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitosupportingservices_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitosupportingservices_crd.yaml
  examples/explainability.yaml
  examples/process-quarkus-example-persistence-nobuild.yaml
  kogito-operator.yaml
  pkg/apis/app/v1alpha1/conditions.go
  pkg/apis/app/v1alpha1/conditions_test.go
  pkg/apis/app/v1alpha1/kogitobuild_types.go
  pkg/apis/app/v1alpha1/kogitoruntime_types.go
  pkg/apis/app/v1alpha1/kogitosupportingservice_types.go
  pkg/client/kubernetes/resource.go
  pkg/controller/kogitobuild/kogitobuild_controller.go
  pkg/controller/kogitobuild/status.go
  pkg/controller/kogitoinfra/errors.go
  pkg/controller/kogitoinfra/infinispan.go
  pkg/controller/kogitoinfra/kafka.go
  pkg/controller/kogitoinfra/keycloak.go
  pkg/controller/kogitoinfra/knative.go
  pkg/controller/kogitoinfra/kogitoinfra_service.go
  pkg/controller/kogitosupportingservice/explainability_reconciler_test.go
  pkg/controller/kogitosupportingservice/kogitosupportingservice_controller.go
  pkg/infrastructure/services/dashboards.go
  pkg/infrastructure/services/dashboards_test.go
  pkg/infrastructure/services/deployer.go
  pkg/infrastructure/services/deployer_test.go
  pkg/infrastructure/services/errors.go
  pkg/infrastructure/services/manage_status.go
  pkg/infrastructure/services/messaging_knative.go
  pkg/infrastructure/services/prometheus.go
  pkg/test/assert_create.go
  test/framework/kogitobuild.go
  test/framework/kogitoexplainability.go
  test/framework/kogitoinfra.go
  test/framework/kogitoserviceutils.go
  test/framework/operator.go
Labels: bdd-tests 🧪, cli 💻, operator :cloud:, ready :rocket:

#646 [KOGITO-3754] Making KogitoInfra create a truststore secret to hold P…
  deploy/crds/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoinfras_crd.yaml
  go.mod
  go.sum
  hack/install-manifests.sh
  kogito-operator.yaml
  pkg/apis/app/v1alpha1/kogitoinfra_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/kogitobuild/build/build_config.go
  pkg/controller/kogitoinfra/errors.go
  pkg/controller/kogitoinfra/infinispan.go
  pkg/controller/kogitoinfra/kafka.go
  pkg/controller/kogitoinfra/keycloak.go
  pkg/controller/kogitoinfra/knative.go
  pkg/controller/kogitoinfra/kogitoinfra_controller.go
  pkg/controller/kogitoinfra/kogitoinfra_controller_test.go
  pkg/controller/kogitoinfra/kogitoinfra_reconciler.go
  pkg/controller/kogitoinfra/kogitoinfra_service.go
  pkg/controller/kogitoinfra/testdata/tls.crt
  pkg/controller/kogitoruntime/deployer.go
  pkg/controller/kogitoruntime/kogitoruntime_controller_test.go
  pkg/controller/kogitosupportingservice/kogitodataindex_controller.go
  pkg/framework/file_permissions.go
  pkg/framework/pkcs12.go
  pkg/framework/pkcs12_test.go
  pkg/framework/testdata/tls.crt
  pkg/infrastructure/kogito_service.go
  pkg/infrastructure/services/configmap.go
  pkg/infrastructure/services/dashboards.go
  pkg/infrastructure/services/deployer_resources.go
  pkg/infrastructure/services/deployer_resources_test.go
  pkg/test/kogitoinfra.go
  test/framework/operator.go
Labels: bdd-tests 🧪, cli 💻, needs review :mag:, operator :cloud:

#639 [KOGITO-3745] Mirror should ignore the custom repo
  Jenkinsfile.deploy
  Makefile
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/config/config.go
  test/framework/maven.go
Labels: bdd-tests 🧪, needs review :mag:

#637 KOGITO-1046 - Data Index performance tests
  test/features/data_index_performance.feature
  test/framework/graphql.go
  test/framework/kogitodataindex.go
  test/framework/maven.go
  test/steps/graphql.go
  test/steps/graphql_queries.go
  test/steps/image_registry.go
  test/steps/mappers/create_maven_options.go
  test/steps/maven.go
Labels: bdd-tests 🧪, needs review :mag:

#643 [KOGITO-3736] - Reconciler error in Data index controller when Kogito…
  RELEASE_NOTES.md
  pkg/controller/add_kogitosupportingservice.go
  pkg/controller/kogitoruntime/kogitoruntime_controller.go
  pkg/controller/kogitosupportingservice/kogitodataindex_controller.go
  pkg/controller/kogitosupportingservice/kogitodataindex_controller_test.go
  pkg/controller/kogitosupportingservice/kogitodataindex_reconciler.go
  pkg/controller/kogitosupportingservice/kogitodataindex_reconciler_test.go
  pkg/controller/kogitosupportingservice/kogitosupportingservice_controller.go
  pkg/framework/file_permissions.go
  pkg/infrastructure/data_index.go
  pkg/infrastructure/data_index_test.go
  pkg/infrastructure/kogito_runtime.go
  pkg/infrastructure/kogito_runtime_test.go
Labels: operator :cloud:, ready :rocket:

#632 [KOGITO-1008][KOGITO-1003] BDD tests for Task Console
  Makefile
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/config/config.go
  test/features/install_taskconsole.feature
  test/features/keycloak.feature
  test/framework/kogitotaskconsole.go
  test/steps/data.go
  test/steps/kogitomgmtconsole.go
  test/steps/kogitotaskconsole.go
Labels: bdd-tests 🧪, needs review :mag:

#647 [KOGITO-3610] - Updating Kogito Service interface to describe CloudEv…
  deploy/crds/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/crds/app.kiegroup.org_kogitosupportingservices_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitosupportingservices_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/kogito-operator.v1.0.0-snapshot.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitosupportingservices_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  kogito-operator.yaml
  pkg/apis/app/v1alpha1/conditions.go
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/infrastructure/services/dashboards.go
  pkg/infrastructure/services/errors.go
  pkg/infrastructure/services/messaging.go
  pkg/infrastructure/services/messaging_kafka.go
  pkg/infrastructure/services/messaging_knative.go
  pkg/infrastructure/services/messaging_test.go
Labels: operator :cloud:, ready :rocket:

#628 Remote Debug Kogito Operator using Intellij IDEA
  README.md
  docs/images/add_configuration.png
  docs/images/add_go_remote_config.png
  docs/images/remote_debug_configurations.png
Labels: ready :rocket:

#650 [KOGITO-3831] Store ClusterServiceVersions used in tests
  test/steps/data.go
Labels: bdd-tests 🧪, needs review :mag:

#649 [KOGITO-3720] Add test coverage for Grafana dashboard
  test/features/grafana.feature
  test/framework/grafana.go
  test/steps/data.go
  test/steps/grafana.go
Labels: bdd-tests 🧪, needs review :mag:

#652 [KOGITO-3837] Update master to 2.0.0-snapshot
  .osdk-scorecard.yaml
  README.md
  cmd/kogito/version/version.go
  deploy/olm-catalog/kogito-operator/2.0.0-snapshot/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/olm-catalog/kogito-operator/2.0.0-snapshot/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/olm-catalog/kogito-operator/2.0.0-snapshot/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/2.0.0-snapshot/app.kiegroup.org_kogitosupportingservices_crd.yaml
  deploy/olm-catalog/kogito-operator/2.0.0-snapshot/kogito-operator.v2.0.0-snapshot.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/custom-subscription-example.yaml
  deploy/olm-catalog/kogito-operator/kogito-operator.package.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  kogito-operator.yaml
  pkg/controller/kogitobuild/build/image_stream_kogito_test.go
  version/version.go
Labels: cli 💻, operator :cloud:, ready :rocket:

#655 [1.0.x][KOGITO-3847] Switch Strimzi operator channel to 0.19
  test/framework/operator.go
Labels: bdd-tests 🧪, cherry-pick :cherries:, needs review :mag:

#654 [KOGITO-3847] Switch Strimzi operator channel to 0.19
  test/framework/operator.go
Labels: bdd-tests 🧪, needs cherry-pick :cherries:, needs review :mag:

#657 [1.0.x][KOGITO-3852] Extend GitHub actions to cover all branches
  .github/workflows/Kogito-Operator-OLM-tests.yaml
  .github/workflows/Kogito-Operator-PR-Check.yaml
  .github/workflows/Kogito-Operator-Unit-tests.yaml
Labels: cherry-pick :cherries:, ready :rocket:

#656 [KOGITO-3852] Extend GitHub actions to cover all branches
  .github/workflows/Kogito-Operator-OLM-tests.yaml
  .github/workflows/Kogito-Operator-PR-Check.yaml
  .github/workflows/Kogito-Operator-Unit-tests.yaml
Labels: needs cherry-pick :cherries:, ready :rocket:

#660 [KOGITO-3866] - Operator print error logs when KogitoRuntime delete
  pkg/controller/kogitoinfra/kogitoinfra_controller.go
  pkg/controller/kogitoruntime/kogitoruntime_controller.go
  pkg/controller/kogitosupportingservice/kogitosupportingservice_controller.go
  pkg/infrastructure/kogito_infra.go
  pkg/infrastructure/kogito_infra_test.go
  pkg/infrastructure/kogito_runtime.go
  pkg/infrastructure/kogito_runtime_test.go
Labels: operator :cloud:, ready :rocket:

#668 [KOGITO-3893] Add unit testing to jenkinsfiles
  Jenkinsfile
  Jenkinsfile.deploy
Labels: CI/CD :loop:, needs review :mag:

#665 [1.0.x] Update release notes with known bugs for 1.0.0 release
  RELEASE_NOTES.md
Labels: ready :rocket:

#670 [1.0.x] Copy manifests version 0.17.0 to 1.0.x
  deploy/olm-catalog/kogito-operator/0.17.0/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/olm-catalog/kogito-operator/0.17.0/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.17.0/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/olm-catalog/kogito-operator/0.17.0/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/olm-catalog/kogito-operator/0.17.0/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.17.0/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/0.17.0/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/0.17.0/app.kiegroup.org_kogitotrusties_crd.yaml
  deploy/olm-catalog/kogito-operator/0.17.0/app.kiegroup.org_kogitotrustyuis_crd.yaml
  deploy/olm-catalog/kogito-operator/0.17.0/kogito-operator.v0.17.0.clusterserviceversion.yaml
Labels: cherry-pick :cherries:, needs review :mag:

#663 [KOGITO-3874] - Allow configuration of readiness and liveness probes
  deploy/crds/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/crds/app.kiegroup.org_kogitosupportingservices_crd.yaml
  deploy/olm-catalog/kogito-operator/2.0.0-snapshot/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/2.0.0-snapshot/app.kiegroup.org_kogitosupportingservices_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitosupportingservices_crd.yaml
  kogito-operator.yaml
  pkg/apis/app/v1beta1/kogitoservices_types.go
  pkg/apis/app/v1beta1/zz_generated.deepcopy.go
  pkg/apis/app/v1beta1/zz_generated.openapi.go
  pkg/infrastructure/services/deployment.go
  pkg/infrastructure/services/probe.go
  pkg/infrastructure/services/probe_test.go
Labels: operator :cloud:, ready :rocket:

#671 [KOGITO-3899] Add build check steps in source files feature
  test/features/deploy_source_files.feature
Labels: bdd-tests 🧪, ready :rocket:

#675 [KOGITO-3935] Adjust Prometheus test for metric change
  test/features/prometheus.feature
Labels: bdd-tests 🧪, ready :rocket:

#658 [KOGITO-3215] - Support cluster-scoped deployment for operator
  cmd/kogito/command/flag/operator_flag.go
  cmd/kogito/command/install/kogito_infra.go
  cmd/kogito/command/install/kogito_operator.go
  cmd/kogito/command/install/kogito_operator_test.go
  cmd/kogito/command/install/supportingservices.go
  cmd/kogito/command/message/data_index.go
  cmd/kogito/command/message/explainability.go
  cmd/kogito/command/message/jobs_service.go
  cmd/kogito/command/message/kogitobuild.go
  cmd/kogito/command/message/kogitoinfra.go
  cmd/kogito/command/message/kogitoruntime.go
  cmd/kogito/command/message/mgmt_console.go
  cmd/kogito/command/message/project.go
  cmd/kogito/command/message/services.go
  cmd/kogito/command/message/task_console.go
  cmd/kogito/command/message/trusty.go
  cmd/kogito/command/message/trusty_ui.go
  cmd/kogito/command/project/project.go
  cmd/kogito/command/service/build_service.go
  cmd/kogito/command/service/runtime_service.go
  cmd/kogito/command/shared/install_operator.go
  cmd/kogito/command/shared/install_operator_test.go
  cmd/kogito/command/shared/install_services.go
  cmd/kogito/command/shared/operatorhub.go
  cmd/manager/main.go
  deploy/clusterrole.yaml
  deploy/clusterrole_binding.yaml
  deploy/namespace.yaml
  deploy/olm-catalog/kogito-operator/2.0.0-snapshot/kogito-operator.v2.0.0-snapshot.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  hack/deploy-operator-on-ocp.sh
  hack/go-vet.sh
  kogito-operator.yaml
  pkg/client/client.go
  pkg/client/meta/meta.go
  pkg/controller/kogitoruntime/deployer.go
  pkg/controller/kogitoruntime/kogitoruntime_controller.go
  pkg/controller/kogitoruntime/rbac.go
  pkg/framework/subscription.go
  pkg/test/client.go
  test/framework/kubernetes.go
  test/framework/operator.go
  test/main_test.go
  test/steps/data.go
  test/steps/operator.go
Labels: bdd-tests 🧪, cli 💻, operator :cloud:, ready :rocket:

#674 [KOGITO-3910] Add option to run tests with cluster wide operator
  Makefile
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/config/config.go
  test/framework/operator.go
  test/main_test.go
Labels: bdd-tests 🧪, needs review :mag:

#676 [KOGITO-3937] - Move probe configuration in to `probes` subproperty
  deploy/crds/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/crds/app.kiegroup.org_kogitosupportingservices_crd.yaml
  deploy/olm-catalog/kogito-operator/2.0.0-snapshot/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/2.0.0-snapshot/app.kiegroup.org_kogitosupportingservices_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitosupportingservices_crd.yaml
  kogito-operator.yaml
  pkg/apis/app/v1beta1/kogitoservices_types.go
  pkg/apis/app/v1beta1/probe.go
  pkg/apis/app/v1beta1/zz_generated.deepcopy.go
  pkg/apis/app/v1beta1/zz_generated.openapi.go
  pkg/infrastructure/services/probe.go
  pkg/infrastructure/services/probe_test.go
Labels: operator :cloud:, ready :rocket:

#679 Updating Release Notes to 1.1.0
  .github/pull_request_template.md
  RELEASE_NOTES.md
Labels: ready :rocket:

#677 [KOGITO-3898] - Provide CLI flags for subset of probe parameters
  RELEASE_NOTES.md
  cmd/kogito/command/converter/kogitoprobe_converter.go
  cmd/kogito/command/converter/kogitoprobe_converter_test.go
  cmd/kogito/command/flag/install_flag.go
  cmd/kogito/command/flag/probe_flag.go
  cmd/kogito/command/install/supportingservices.go
  cmd/kogito/command/install/supportingservices_test.go
  cmd/kogito/command/service/runtime_service.go
Labels: cli 💻, operator :cloud:, ready :rocket:
