Repository kiegroup/kogito-operator, pull requests merged in 2020-09, with the labels that each got.

#538 [KOGITO-3148] - Remove third party required dependencies from CSV
  cmd/kogito/command/install/infinispan.go
  cmd/kogito/command/install/kafka.go
  cmd/kogito/command/install/keycloak.go
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/kogito-operator.v1.0.0-snapshot.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
Labels: cli 💻, ready :rocket:

#521 [KOGITO-2960] - Prometheus integration with kogito-cloud-operator
  cmd/kogito/command/converter/monitoring_converter.go
  cmd/kogito/command/converter/monitoring_converter_test.go
  cmd/kogito/command/flag/monitoring_flag.go
  cmd/kogito/command/flag/runtime_flag.go
  cmd/kogito/command/service/runtime_service.go
  deploy/crds/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/kogito-operator.v1.0.0-snapshot.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  pkg/apis/app/v1alpha1/kogitoruntime_types.go
  pkg/apis/app/v1alpha1/monitoring.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/client/client.go
  pkg/client/kubernetes/resource.go
  pkg/client/kubernetes/resource_reader.go
  pkg/client/kubernetes/resource_writer.go
  pkg/client/meta/meta.go
  pkg/client/prometheus/servicemonitor.go
  pkg/client/prometheus/servicemonitor_test.go
  pkg/controller/kogitobuild/build/manager.go
  pkg/controller/kogitobuild/kogitobuild_controller.go
  pkg/controller/kogitodataindex/kogitodataindex_controller.go
  pkg/controller/kogitoinfra/kogitoinfra_controller.go
  pkg/controller/kogitojobsservice/kogitojobsservice_controller.go
  pkg/controller/kogitomgmtconsole/kogitomgmtconsole_controller.go
  pkg/controller/kogitoruntime/deployer.go
  pkg/controller/kogitoruntime/kogitoruntime_controller.go
  pkg/controller/kogitotrusty/kogitotrusty_controller.go
  pkg/framework/comparator.go
  pkg/infrastructure/services/deployer.go
  pkg/infrastructure/services/prometheus.go
  pkg/infrastructure/services/resources.go
  pkg/infrastructure/services/service.go
Labels: cli 💻, operator :cloud:, ready :rocket:

#544 [KOGITO-3104] - Missing Resources for Operator CRs
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/kogito-operator.v1.0.0-snapshot.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  pkg/apis/app/v1alpha1/kogitobuild_types.go
  pkg/apis/app/v1alpha1/kogitodataindex_types.go
  pkg/apis/app/v1alpha1/kogitoinfra_types.go
  pkg/apis/app/v1alpha1/kogitojobsservice_types.go
  pkg/apis/app/v1alpha1/kogitomgmtconsole_types.go
  pkg/apis/app/v1alpha1/kogitoruntime_types.go
  pkg/apis/app/v1alpha1/kogitotrusty_types.go
Labels: operator :cloud:, ready :rocket:

#543 [KOGITO-961] Tests: Enable Prometheus test
  test/features/prometheus.feature
  test/framework/mappers/cr_to_cli.go
  test/scripts/examples/dmn-drools-quarkus-metrics.feature
  test/steps/kogitoruntime.go
  test/steps/mappers/create_kogito_service.go
Labels: bdd-tests 🧪, ready :rocket:

#547 [KOGITO-3278] Tests: Enable Kogito infra for Kafka only when URL and …
  test/framework/kogitoserviceutils.go
Labels: bdd-tests 🧪, ready :rocket:

#549 [KOGITO-3300] - Improving tests and ignoring project not in the context
  cmd/kogito/command/deploy/delete_service.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/message/project.go
  cmd/kogito/command/service/build_service.go
  cmd/kogito/command/service/runtime_service.go
  cmd/kogito/command/shared/kubeconfig.go
  cmd/kogito/command/shared/kubeconfig_test.go
  cmd/kogito/command/shared/resource_checks.go
  cmd/kogito/command/shared/resource_checks_test.go
Labels: cli 💻, ready :rocket:

#536 KOGITO-1001: Add test for Jobs-service with Keycloak
  README.md
  test/features/install_jobs_service.feature
  test/framework/http.go
  test/framework/keycloak.go
  test/steps/data.go
  test/steps/http.go
  test/steps/keycloak.go
Labels: bdd-tests 🧪, ready :rocket:

#553 [KOGITO-3304] - Relaxing regexp to match docker images with IPs and d…
  cmd/kogito/command/converter/image_converter_test.go
  cmd/kogito/command/deploy/deploy_service_test.go
  pkg/framework/image.go
  pkg/framework/image_test.go
Labels: cli 💻, operator :cloud:, ready :rocket:

#551 [KOGITO-3311] Tests: Update tests to reflect task endpoint change
  test/framework/task.go
  test/steps/task.go
Labels: bdd-tests 🧪, ready :rocket:

#522 [KOGITO-2997] BDD: Maven native build in container
  Jenkinsfile.deploy
  Makefile
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/config/config.go
  test/framework/maven.go
Labels: bdd-tests 🧪, ready :rocket:

#548 KOGITO-999: Cucumber Tests: Add test with Data-index and Keycloak
  test/features/install_dataindex.feature
  test/framework/graphql.go
  test/steps/graphql.go
Labels: bdd-tests 🧪, needs review :mag:

#554 [KOGITO-3323] Tests: Update scenario description to be unique for eve…
  test/features/deploy_travel_agency.feature
  test/features/update_httpport.feature
Labels: bdd-tests 🧪, ready :rocket:

#558 KOGITO-3176 - disable standalone trusty test due to kafka change
  test/features/install_trusty.feature
Labels: bdd-tests 🧪, needs review :mag:

#562 [KOGITO-3335] Tests: Split current tests to operator and integration
  Jenkinsfile
  test/features/install_dataindex.feature
  test/features/integration/deploy_travel_agency.feature
  test/features/integration/keycloak.feature
  test/features/integration/service_discovery.feature
  test/features/operator/deploy_kogito_build.feature
  test/features/operator/deploy_kogito_runtime.feature
  test/features/operator/deploy_service_resources.feature
  test/features/operator/deploy_source_files.feature
  test/features/operator/install_dataindex.feature
  test/features/operator/install_jobs_service.feature
  test/features/operator/install_kogitoinfra.feature
  test/features/operator/install_mgmtconsole.feature
  test/features/operator/install_trusty.feature
  test/features/operator/kogito_service_performance.feature
  test/features/operator/olm/cli_install_operator.feature
  test/features/operator/olm/cli_new_project.feature
  test/features/operator/olm/cli_use_project.feature
  test/features/operator/prometheus.feature
  test/features/operator/update_httpport.feature
Labels: CI/CD :loop:, bdd-tests 🧪, needs review :mag:

#555 [KOGITO-3296] - Upgrading Infinispan CRD and fixing custom credential…
  go.mod
  go.sum
  pkg/controller/kogitoinfra/infinispan/comparator.go
  pkg/controller/kogitoinfra/infinispan/infinispan_credentials.go
  pkg/controller/kogitoinfra/infinispan/infinispan_credentials_test.go
  pkg/controller/kogitoinfra/infinispan/operator.go
  pkg/controller/kogitoinfra/infinispan/resource.go
  pkg/controller/kogitoinfra/infinispan/resource_test.go
  pkg/infrastructure/infinispan.go
  pkg/infrastructure/services/infinispan.go
  test/framework/container_engine.go
  test/framework/infinispan.go
  test/framework/mappers/cr_to_cli.go
Labels: bdd-tests 🧪, operator :cloud:, ready :rocket:

#559 [0.15.x] [KOGITO-3296] - Upgrading Infinispan CRD and fixing custom credential
  go.mod
  go.sum
  pkg/controller/kogitoinfra/infinispan/comparator.go
  pkg/controller/kogitoinfra/infinispan/infinispan_credentials.go
  pkg/controller/kogitoinfra/infinispan/infinispan_credentials_test.go
  pkg/controller/kogitoinfra/infinispan/operator.go
  pkg/controller/kogitoinfra/infinispan/resource.go
  pkg/controller/kogitoinfra/infinispan/resource_test.go
  pkg/infrastructure/infinispan.go
  pkg/infrastructure/services/infinispan.go
  test/framework/container_engine.go
  test/framework/infinispan.go
  test/framework/mappers/cr_to_cli.go
Labels: bdd-tests 🧪, operator :cloud:, ready :rocket:

#556 KOGITO-3332: Check whether jobs service is ready before deploying ser…
  test/features/operator/deploy_kogito_runtime.feature
Labels: bdd-tests 🧪, ready :rocket:

#561 [0.15.x] KOGITO-3176 - disable standalone trusty test due to kafka change
  test/features/install_trusty.feature
Labels: bdd-tests 🧪, ready :rocket:

#566 [0.15.x] Cherry pick trusty-ui changes
  Makefile
  README.md
  cmd/kogito/command/install/factory.go
  cmd/kogito/command/install/trusty_ui.go
  cmd/kogito/command/install/trusty_ui_test.go
  cmd/kogito/command/message/trusty_ui.go
  cmd/kogito/command/remove/runtime_services.go
  cmd/kogito/command/shared/install_operator_test.go
  cmd/kogito/command/shared/install_services.go
  deploy/crds/app.kiegroup.org_kogitotrustyuis_crd.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitotrustyui_cr.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitotrustyuis_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/kogito-operator.v1.0.0-snapshot.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitotrustyuis_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  hack/run-tests.sh
  hack/run-tests.sh.bats
  pkg/apis/app/v1alpha1/kogitotrustyui_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_kogitotrustyui.go
  pkg/controller/kogitotrustyui/kogitotrusty_ui_controller.go
  pkg/controller/kogitotrustyui/kogitotrusty_ui_controller_test.go
  pkg/infrastructure/services/deployer.go
  pkg/infrastructure/services/error.go
  pkg/infrastructure/services/resources.go
  pkg/infrastructure/services/resources_test.go
  pkg/infrastructure/trusty.go
  pkg/infrastructure/trusty_ui.go
  test/config/config.go
  test/features/install_trustyui.feature
  test/framework/kogitotrustyui.go
  test/steps/data.go
  test/steps/kogitotrustyui.go
Labels: bdd-tests 🧪, cli 💻, needs review :mag:, operator :cloud:

#564 KOGITO-3340: Cucumber Tests: Projects that use Keycloak remains as Te…
  hack/clean-stuck-namespaces.sh
Labels: ready :rocket:

#464 KOGITO-2812 - add explainability service
  Makefile
  cmd/kogito/command/install/explainability.go
  cmd/kogito/command/install/explainability_test.go
  cmd/kogito/command/install/factory.go
  cmd/kogito/command/message/explainability.go
  cmd/kogito/command/remove/runtime_services.go
  cmd/kogito/command/shared/install_operator_test.go
  cmd/kogito/command/shared/install_services.go
  deploy/crds/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitoexplainability_cr.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/kogito-operator.v1.0.0-snapshot.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  examples/explainability.yaml
  hack/run-tests.sh
  hack/run-tests.sh.bats
  pkg/apis/app/v1alpha1/kogitoexplainability_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_kogitoexplainability.go
  pkg/controller/kogitoexplainability/kogitoexplainability_controller.go
  pkg/controller/kogitoexplainability/kogitoexplainability_controller_test.go
  pkg/controller/kogitoruntime/deployer.go
  pkg/infrastructure/explainability.go
  test/config/config.go
  test/features/operator/install_explainability.feature
  test/features/operator/install_trustyui.feature
  test/framework/kogitoexplainability.go
  test/steps/data.go
  test/steps/kogitoexplainability.go
Labels: bdd-tests 🧪, cli 💻, needs review :mag:, on hold :hand:, operator :cloud:

#571 [0.15.x] - KOGITO-3333: Disable jobs service keycloak test.
  test/features/install_jobs_service.feature
Labels: bdd-tests 🧪, needs review :mag:

#568 [0.15.x] KOGITO-2812 - cherry pick explainability pr
  Makefile
  cmd/kogito/command/install/explainability.go
  cmd/kogito/command/install/explainability_test.go
  cmd/kogito/command/install/factory.go
  cmd/kogito/command/message/explainability.go
  cmd/kogito/command/remove/runtime_services.go
  cmd/kogito/command/shared/install_operator_test.go
  cmd/kogito/command/shared/install_services.go
  deploy/crds/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitoexplainability_cr.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/kogito-operator.v1.0.0-snapshot.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  examples/explainability.yaml
  hack/run-tests.sh
  hack/run-tests.sh.bats
  pkg/apis/app/v1alpha1/kogitoexplainability_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_kogitoexplainability.go
  pkg/controller/kogitoexplainability/kogitoexplainability_controller.go
  pkg/controller/kogitoexplainability/kogitoexplainability_controller_test.go
  pkg/controller/kogitoruntime/deployer.go
  pkg/infrastructure/explainability.go
  test/config/config.go
  test/features/install_explainability.feature
  test/framework/kogitoexplainability.go
  test/steps/data.go
  test/steps/kogitoexplainability.go
Labels: CI/CD :loop:, bdd-tests 🧪, cli 💻, needs review :mag:, operator :cloud:

#557 KOGITO-3333: Refactor Jobs Service test with keycloak
  test/features/integration/keycloak.feature
Labels: bdd-tests 🧪, ready :rocket:

#573 [PLANNER-2084] Tests: Disable Optaplanner native test
  test/features/operator/deploy_kogito_runtime.feature
  test/scripts/examples/process-optaplanner-quarkus.feature
Labels: bdd-tests 🧪, ready :rocket:

#577 [KOGITO-3382] Transitive dependency of Keycloak operator module missing
  go.mod
  go.sum
Labels: ready :rocket:

#578 [KOGITO-3350] CLI fails to download GitHub file properly
  cmd/kogito/command/service/buildresource_service.go
  cmd/kogito/command/service/buildresource_service_test.go
Labels: cli 💻, ready :rocket:

#575 Cucumber Tests: Add test for explainability-service with Keycloak
  test/features/integration/keycloak.feature
Labels: bdd-tests 🧪, ready :rocket:

#582 [0.15.x][KOGITO-3382] Transitive dependency of Keycloak operator module missing
  go.mod
  go.sum
Labels: CI/CD :loop:, cherry-pick :cherries:, needs review :mag:

#579 [KOGITO-3388] Remove the PrometheusCli from operator code
  pkg/client/client.go
  pkg/client/client_builder.go
  pkg/client/client_builder_test.go
  pkg/test/client.go
Labels: operator :cloud:, ready :rocket:

#567 [KOGITO-3270] - Accepting external ConfigMaps to be mounted in a give…
  RELEASE_NOTES.md
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/flag/runtime_flag.go
  cmd/kogito/command/service/config.go
  cmd/kogito/command/service/runtime_service.go
  cmd/kogito/command/util/common_util.go
  cmd/kogito/command/util/common_util_test.go
  deploy/crds/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/crds/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/crds/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/crds/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/crds/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/crds/app.kiegroup.org_kogitotrusties_crd.yaml
  deploy/crds/app.kiegroup.org_kogitotrustyuis_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitotrusties_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitotrustyuis_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/kogito-operator.v1.0.0-snapshot.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitotrusties_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitotrustyuis_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/client/kubernetes/resource_reader.go
  pkg/controller/kogitobuild/build/manager.go
  pkg/controller/kogitoruntime/kogitoruntime_controller_test.go
  pkg/infrastructure/services/configmap.go
  pkg/infrastructure/services/configmap_test.go
  pkg/infrastructure/services/deployer.go
  pkg/infrastructure/services/resources.go
  pkg/infrastructure/services/resources_test.go
Labels: cli 💻, operator :cloud:, ready :rocket:

#570 KOGITO-3360: Cucumber Tests: Keep logs only for test failures
  Jenkinsfile
  Jenkinsfile.deploy
Labels: CI/CD :loop:, bdd-tests 🧪, ready :rocket:

#552 KOGITO-3281: Cucumber Tests: Add test for trusty-service with Keycloak
  test/features/integration/keycloak.feature
Labels: bdd-tests 🧪, ready :rocket:

#574 KOGITO-3369: Cucumber Tests - Refactor Kogito Explainability Changes
  pkg/controller/kogitoexplainability/kogitoexplainability_controller.go
  pkg/controller/kogitoexplainability/kogitoexplainability_controller_test.go
  pkg/infrastructure/explainability.go
  test/features/operator/install_explainability.feature
  test/framework/kafka.go
  test/framework/keycloak.go
  test/framework/kogitotrusty.go
  test/steps/kafka.go
  test/steps/kogitoexplainability.go
Labels: bdd-tests 🧪, operator :cloud:, ready :rocket:

#583 [KOGITO-3382] Add KOGITO-3382 issue to release notes
  RELEASE_NOTES.md
Labels: ready :rocket:

#584 update release notes with image change
  RELEASE_NOTES.md
Labels: ready :rocket:

#587 [KOGITO-3420] Adjust PR check tests to execute only operator core fun…
  Jenkinsfile
  test/features/deploy_kogito_build.feature
  test/features/deploy_kogito_runtime.feature
  test/features/deploy_service_resources.feature
  test/features/deploy_source_files.feature
  test/features/deploy_travel_agency.feature
  test/features/install_dataindex.feature
  test/features/install_explainability.feature
  test/features/install_jobs_service.feature
  test/features/install_kogitoinfra.feature
  test/features/install_mgmtconsole.feature
  test/features/install_trusty.feature
  test/features/install_trustyui.feature
  test/features/keycloak.feature
  test/features/kogito_service_performance.feature
  test/features/olm/cli_install_operator.feature
  test/features/olm/cli_new_project.feature
  test/features/olm/cli_use_project.feature
  test/features/prometheus.feature
  test/features/service_discovery.feature
  test/features/update_httpport.feature
Labels: CI/CD :loop:, bdd-tests 🧪, ready :rocket:

#586 [KOGITO-3418] - Update envs field in kogito CRDs to match with native…
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/explainability.go
  cmd/kogito/command/install/jobs_service.go
  cmd/kogito/command/install/mgmt_console.go
  cmd/kogito/command/install/trusty.go
  cmd/kogito/command/install/trusty_ui.go
  cmd/kogito/command/service/build_service.go
  cmd/kogito/command/service/runtime_service.go
  deploy/crds/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/crds/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/crds/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/crds/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/crds/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/crds/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/crds/app.kiegroup.org_kogitotrusties_crd.yaml
  deploy/crds/app.kiegroup.org_kogitotrustyuis_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitotrusties_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/app.kiegroup.org_kogitotrustyuis_crd.yaml
  deploy/olm-catalog/kogito-operator/1.0.0-snapshot/kogito-operator.v1.0.0-snapshot.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoexplainabilities_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoruntimes_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitotrusties_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitotrustyuis_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  examples/example-custom-build-images.yaml
  examples/kubernetes/travel-agency/kogito-travels.yaml
  examples/kubernetes/travel-agency/kogito-visas.yaml
  examples/kubernetes/travel-agency/management-console.yaml
  examples/onboarding-example.yaml
  examples/process-quarkus-example-persistence.yaml
  examples/process-quarkus-example.yaml
  examples/springboot.yaml
  pkg/apis/app/v1alpha1/kogitobuild_types.go
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/kogitobuild/build/build_config.go
  test/framework/kogitobuild.go
  test/framework/mappers/cr_to_cli.go
Labels: bdd-tests 🧪, cli 💻, needs review :mag:, operator :cloud:

#590 [KOGITO-3475] Periodic reconciler error when KogitoInfra is deleted
  pkg/controller/kogitoinfra/kogitoinfra_controller.go
Labels: cli 💻, operator :cloud:, ready :rocket:

#589 [KOGITO-3474] Tests: Update BDD tests to reflect KogitoInfra changes
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  test/features/deploy_kogito_runtime.feature
  test/features/deploy_travel_agency.feature
  test/features/install_dataindex.feature
  test/features/install_explainability.feature
  test/features/install_jobs_service.feature
  test/features/install_kogitoinfra.feature
  test/features/install_mgmtconsole.feature
  test/features/install_trusty.feature
  test/features/keycloak.feature
  test/features/kogito_service_performance.feature
  test/features/update_httpport.feature
  test/framework/kogitoinfra.go
  test/framework/mappers/cr_to_cli.go
  test/steps/data.go
  test/steps/infinispan.go
  test/steps/kafka.go
  test/steps/kogitodataindex.go
  test/steps/kogitoexplainability.go
  test/steps/kogitoinfra.go
  test/steps/kogitojobsservice.go
  test/steps/kogitomgmtconsole.go
  test/steps/kogitoruntime.go
  test/steps/kogitotrusty.go
  test/steps/mappers/create_kogito_service.go
  test/types/holder.go
Labels: bdd-tests 🧪, operator :cloud:, ready :rocket:
