Repository kiegroup/kogito-operator, pull requests merged in 2020-04, with the labels that each got.

#248 KOGITO-1605: Amend issues in GitHub documentation
  README.md
Labels: ready :rocket:

#254 [KOGITO-1600] - Prepare 0.9.0 Kogito Operator release
  .osdk-scorecard.yaml
  Makefile
  deploy/crds/app.kiegroup.org_v1alpha1_kogitojobsservice_cr.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitomgmtconsole_cr.yaml
  deploy/olm-catalog/kogito-operator/0.9.0/kogito-operator.v0.9.0.clusterserviceversion.yaml
  go.sum
  hack/scorecard.sh
Labels: ready :rocket:

#251 KOGITO-1002: Cucumber Tests: Test Management Console provisioning via CR
  Makefile
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/README.md
  test/config/config.go
  test/features/install_mgmtconsole.feature
  test/framework/kogitomgmtconsole.go
  test/steps/data.go
  test/steps/kogitomgmtconsole.go
Labels: ready :rocket:

#249 KOGITO-1606: Add install option in makefile
  Makefile
  hack/crds-utils.sh
  hack/deploy-operator-on-ocp.sh
  hack/run-tests.sh
Labels: ready :rocket:

#256 KOGITO-1007: Cucumber Tests: Test Management Console provisioning via…
  test/framework/kogitomgmtconsole.go
  test/steps/kogitomgmtconsole.go
Labels: ready :rocket:

#261 KOGITO-1007: Cucumber Tests: Test Management Console provisioning via…
  test/framework/kogitomgmtconsole.go
  test/steps/kogitomgmtconsole.go
Labels: cherry-pick :cherries:, ready :rocket:

#258 [KOGITO-1365] - Renaming final CLI binary
  hack/go-build-cli.sh
Labels: ready :rocket:

#264 [0.9.x][KOGITO-1365] - Renaming final CLI binary (#258)
  hack/go-build-cli.sh
Labels: cherry-pick :cherries:

#265 [KOGITO-1670] - Bump to 0.9.1 version
  .osdk-scorecard.yaml
  README.md
  cmd/kogito/version/version.go
  deploy/crds/app.kiegroup.org_v1alpha1_kogitoapp_cr.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitodataindex_cr.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitojobsservice_cr.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitomgmtconsole_cr.yaml
  deploy/examples/data-index.yaml
  deploy/examples/jbpm-quarkus-example-binary-builds.yaml
  deploy/examples/jbpm-quarkus-example-persistence.yaml
  deploy/examples/management-console.yaml
  deploy/olm-catalog/kogito-operator/0.9.1/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.9.1/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.9.1/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/olm-catalog/kogito-operator/0.9.1/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.9.1/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/0.9.1/kogito-operator.v0.9.1.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/kogito-operator.package.yaml
  deploy/operator.yaml
  hack/go-build.sh
  hack/go-vet.sh
  test/README.md
  version/version.go
Labels: ready :rocket:

#266 [KOGITO-1671] - Bump Operator to 0.10.0
  .osdk-scorecard.yaml
  README.md
  cmd/kogito/version/version.go
  deploy/crds/app.kiegroup.org_v1alpha1_kogitoapp_cr.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitodataindex_cr.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitojobsservice_cr.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitomgmtconsole_cr.yaml
  deploy/examples/data-index.yaml
  deploy/examples/example-custom-build-images.yaml
  deploy/examples/jbpm-quarkus-example-binary-builds.yaml
  deploy/examples/jbpm-quarkus-example-persistence.yaml
  deploy/examples/jbpm-quarkus-example.yaml
  deploy/examples/management-console.yaml
  deploy/examples/onboarding-example.yaml
  deploy/examples/travelapp-kogito-travel-agency.yaml
  deploy/examples/travelapp-kogito-visas.yaml
  deploy/olm-catalog/kogito-operator/0.10.0/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.10.0/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.10.0/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/olm-catalog/kogito-operator/0.10.0/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.10.0/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/0.10.0/kogito-operator.v0.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/kogito-operator.package.yaml
  deploy/operator.yaml
  hack/go-build.sh
  hack/go-vet.sh
  test/README.md
  version/version.go
Labels: ready :rocket:

#269 [master][KOGITO-1703] Wrong build resource description in KogitoApp CRD
  deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.10.0/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.10.0/kogito-operator.v0.10.0.clusterserviceversion.yaml
  pkg/apis/app/v1alpha1/kogitoapp_types.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
Labels: ready :rocket:

#276 [0.9.x][KOGITO-1703] Wrong build resource description in KogitoApp CRD
  deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.9.1/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.9.1/kogito-operator.v0.9.1.clusterserviceversion.yaml
  pkg/apis/app/v1alpha1/kogitoapp_types.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
Labels: cherry-pick :cherries:, ready :rocket:

#263 [master][KOGITO-1597] Refactor Cucumber tests to get rid of KogitoAppDeployment
  pkg/apis/app/v1alpha1/kogitoapp_types.go
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  test/framework/kogitoapp.go
  test/steps/kogitoapp.go
Labels: ready :rocket:

#267 [master][KOGITO-1258] - Adding 'remove' CLI commands to runtime support services
  cmd/kogito/command/completion/completion.go
  cmd/kogito/command/completion/factory.go
  cmd/kogito/command/context/command_context.go
  cmd/kogito/command/deploy/delete_service.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/deploy/factory.go
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/factory.go
  cmd/kogito/command/install/infinispan.go
  cmd/kogito/command/install/install.go
  cmd/kogito/command/install/jobs_service.go
  cmd/kogito/command/install/kafka.go
  cmd/kogito/command/install/keycloak.go
  cmd/kogito/command/install/kogito_operator.go
  cmd/kogito/command/install/mgmt_console.go
  cmd/kogito/command/project/delete_project.go
  cmd/kogito/command/project/display_project.go
  cmd/kogito/command/project/factory.go
  cmd/kogito/command/project/new_project.go
  cmd/kogito/command/project/use_project.go
  cmd/kogito/command/remove/factory.go
  cmd/kogito/command/remove/infinispan.go
  cmd/kogito/command/remove/kafka.go
  cmd/kogito/command/remove/keycloak.go
  cmd/kogito/command/remove/remove.go
  cmd/kogito/command/remove/runtime_services.go
  cmd/kogito/command/remove/runtime_services_test.go
  cmd/kogito/command/test/common.go
Labels: ready :rocket:

#274 [0.9.x][KOGITO-1258] - Adding 'remove' CLI commands to runtime support services
  cmd/kogito/command/completion/completion.go
  cmd/kogito/command/completion/factory.go
  cmd/kogito/command/context/command_context.go
  cmd/kogito/command/deploy/delete_service.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/deploy/factory.go
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/factory.go
  cmd/kogito/command/install/infinispan.go
  cmd/kogito/command/install/install.go
  cmd/kogito/command/install/jobs_service.go
  cmd/kogito/command/install/kafka.go
  cmd/kogito/command/install/keycloak.go
  cmd/kogito/command/install/kogito_operator.go
  cmd/kogito/command/install/mgmt_console.go
  cmd/kogito/command/project/delete_project.go
  cmd/kogito/command/project/display_project.go
  cmd/kogito/command/project/factory.go
  cmd/kogito/command/project/new_project.go
  cmd/kogito/command/project/use_project.go
  cmd/kogito/command/remove/factory.go
  cmd/kogito/command/remove/infinispan.go
  cmd/kogito/command/remove/kafka.go
  cmd/kogito/command/remove/keycloak.go
  cmd/kogito/command/remove/remove.go
  cmd/kogito/command/remove/runtime_services.go
  cmd/kogito/command/remove/runtime_services_test.go
  cmd/kogito/command/test/common.go
Labels: cherry-pick :cherries:, ready :rocket:

#272 [master][KOGITO-1688] - Renaming Kogito Support Services
  README.md
  cmd/kogito/command/install/jobs_service.go
  deploy/crds/app.kiegroup.org_v1alpha1_kogitodataindex_cr.yaml
  deploy/examples/data-index.yaml
  deploy/olm-catalog/kogito-operator/0.10.0/kogito-operator.v0.10.0.clusterserviceversion.yaml
  pkg/controller/kogitomgmtconsole/kogitomgmtconsole_controller_test.go
  pkg/infrastructure/data_index.go
  pkg/infrastructure/data_index_test.go
  pkg/infrastructure/integration_test.go
  pkg/infrastructure/jobs_service.go
  pkg/infrastructure/kogito_service_test.go
  pkg/infrastructure/services/deployer_test.go
  pkg/infrastructure/services/resources_test.go
  test/features/install_dataindex.feature
  test/features/install_jobs_service.feature
  test/features/olm/cli_install_operator.feature
  test/features/olm/cli_new_project.feature
  test/features/olm/cli_use_project.feature
Labels: ready :rocket:

#277 [0.9.x][KOGITO-1688] - Renaming Kogito Support Services
  README.md
  cmd/kogito/command/install/jobs_service.go
  deploy/crds/app.kiegroup.org_v1alpha1_kogitodataindex_cr.yaml
  deploy/examples/data-index.yaml
  deploy/olm-catalog/kogito-operator/0.9.1/kogito-operator.v0.9.1.clusterserviceversion.yaml
  pkg/controller/kogitomgmtconsole/kogitomgmtconsole_controller_test.go
  pkg/infrastructure/data_index.go
  pkg/infrastructure/data_index_test.go
  pkg/infrastructure/integration_test.go
  pkg/infrastructure/jobs_service.go
  pkg/infrastructure/kogito_service_test.go
  pkg/infrastructure/services/deployer_test.go
  pkg/infrastructure/services/resources_test.go
  test/features/install_dataindex.feature
  test/features/install_jobs_service.feature
  test/features/olm/cli_install_operator.feature
  test/features/olm/cli_new_project.feature
  test/features/olm/cli_use_project.feature
Labels: cherry-pick :cherries:, ready :rocket:

#270 [master] [KOGITO-1627] Load default test config
  Jenkinsfile
  Jenkinsfile.nightly
  Makefile
  README.md
  deploy/examples/jobs-service.yaml
  hack/bump-version.sh
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/.default_config
Labels: bdd-tests 🧪, needs review :mag:

#257 [master][KOGITO-1044] - Kogito runtime performance and load tests
  Makefile
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/config/config.go
  test/features/kogito_service_performance.feature
  test/framework/http.go
  test/framework/logging.go
  test/main_test.go
  test/steps/data.go
  test/steps/http.go
Labels: bdd-tests 🧪, needs review :mag:

#260 [master][KOGITO-1663] - Support for Kogito runtimes images micro version
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/jobs_service.go
  cmd/kogito/command/install/mgmt_console.go
  deploy/crds/app.kiegroup.org_v1alpha1_kogitojobsservice_cr.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitomgmtconsole_cr.yaml
  deploy/examples/management-console.yaml
  pkg/controller/kogitoapp/kogitoapp_controller.go
  pkg/controller/kogitoapp/kogitoapp_controller_test.go
  pkg/controller/kogitoapp/resource/build_config.go
  pkg/controller/kogitoapp/resource/kogito_imagestream_test.go
  pkg/controller/kogitodataindex/kogitodataindex_controller_test.go
  pkg/infrastructure/data_index.go
  pkg/infrastructure/jobs_service.go
  pkg/infrastructure/kogito_images.go
  pkg/infrastructure/kogito_images_test.go
  pkg/infrastructure/mgmt_console.go
  pkg/infrastructure/services/deployment_test.go
  pkg/infrastructure/services/image.go
  pkg/infrastructure/services/image_test.go
  pkg/infrastructure/services/resources_test.go
  pkg/test/image.go
  test/config/config.go
  test/framework/kogitodataindex.go
  test/framework/kogitojobsservice.go
  test/framework/kogitomgmtconsole.go
Labels: ready :rocket:

#278 [0.9.x][KOGITO-1663] - Support for Kogito runtimes images micro version
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/jobs_service.go
  cmd/kogito/command/install/mgmt_console.go
  deploy/crds/app.kiegroup.org_v1alpha1_kogitojobsservice_cr.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitomgmtconsole_cr.yaml
  deploy/examples/data-index.yaml
  deploy/examples/management-console.yaml
  deploy/olm-catalog/kogito-operator/0.9.1/kogito-operator.v0.9.1.clusterserviceversion.yaml
  pkg/controller/kogitoapp/kogitoapp_controller.go
  pkg/controller/kogitoapp/kogitoapp_controller_test.go
  pkg/controller/kogitoapp/resource/build_config.go
  pkg/controller/kogitoapp/resource/kogito_imagestream_test.go
  pkg/controller/kogitodataindex/kogitodataindex_controller_test.go
  pkg/infrastructure/data_index.go
  pkg/infrastructure/jobs_service.go
  pkg/infrastructure/kogito_images.go
  pkg/infrastructure/kogito_images_test.go
  pkg/infrastructure/mgmt_console.go
  pkg/infrastructure/services/deployment_test.go
  pkg/infrastructure/services/image.go
  pkg/infrastructure/services/image_test.go
  pkg/infrastructure/services/resources_test.go
  pkg/test/image.go
  test/config/config.go
  test/framework/kogitodataindex.go
  test/framework/kogitojobsservice.go
  test/framework/kogitomgmtconsole.go
Labels: cherry-pick :cherries:, ready :rocket:

#275 [master][KOGITO-1593] Cucumber tests: Add Cucumber test for resource requests …
  test/features/deploy_service_resources.feature
  test/framework/kogitoapp.go
  test/framework/kubernetes.go
  test/framework/openshift_resources.go
  test/steps/kogitoapp.go
  test/steps/openshift.go
Labels: bdd-tests 🧪, needs review :mag:

#279 [0.9.x] [KOGITO-1927] [cherry-pick] Add load_default_config option for testsand updated pipelines to use …
  Jenkinsfile
  Jenkinsfile.nightly
  Makefile
  README.md
  deploy/examples/jobs-service.yaml
  hack/bump-version.sh
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/.default_config
Labels: bdd-tests 🧪, cherry-pick :cherries:, ready :rocket:

#280 [master] [KOGITO-1750] Set simple mgmt console test as smoke test
  test/features/install_mgmtconsole.feature
Labels: bdd-tests 🧪, ready :rocket:

#281 [0.9.x] [KOGITO-1750] [cherry-pick] Set simple mgmt console test as smoke test
  test/features/install_mgmtconsole.feature
Labels: bdd-tests 🧪, cherry-pick :cherries:, ready :rocket:

#273 [master] [KOGITO-1359] Setup jobs-service to data-index feature test
  test/features/install_jobs_service.feature
  test/framework/kogitojobsservice.go
  test/steps/graphql.go
  test/steps/graphql_queries.go
  test/steps/kogitojobsservice.go
Labels: bdd-tests 🧪, ready :rocket:

#285 [master] [KOGITO-1359] Corrected jobservice/data-index feature test
  test/features/install_jobs_service.feature
Labels: bdd-tests 🧪, ready :rocket:

#268 [master] [KOGITO-1702] Updated discovery test due to onboarding example migrated to ruleunit
  test/features/service_discovery.feature
Labels: bdd-tests 🧪, ready :rocket:

#283 [master] [KOGITO-1669] Updated features with new examples' names
  test/features/binary_build.feature
  test/features/deploy_quarkus_service.feature
  test/features/deploy_springboot_service.feature
  test/features/install_dataindex.feature
  test/features/kogito_service_performance.feature
Labels: bdd-tests 🧪, needs review :mag:

#284 [0.9.x] [KOGITO-1359] Setup jobs-service to data-index feature test
  test/features/install_jobs_service.feature
  test/framework/kogitojobsservice.go
  test/steps/graphql.go
  test/steps/graphql_queries.go
  test/steps/kogitojobsservice.go
Labels: bdd-tests 🧪, cherry-pick :cherries:, needs review :mag:

#286 [0.9.x] [KOGITO-1702] Updated discovery test due to onboarding example migrated to ruleunit
  test/features/service_discovery.feature
Labels: bdd-tests 🧪, cherry-pick :cherries:, needs review :mag:

#288 [0.9.x] [KOGITO-1669] Updated features with new examples' names
  test/features/binary_build.feature
  test/features/deploy_quarkus_service.feature
  test/features/deploy_springboot_service.feature
  test/features/install_dataindex.feature
Labels: bdd-tests 🧪, cherry-pick :cherries:, ready :rocket:

#287 [KOGITO-1772] Use generic command execution in cli.go
  test/framework/cli.go
Labels: bdd-tests 🧪, ready :rocket:

#262 [master][KOGITO-1628] Cucumber tests: Merge the way we handle services into th…
  test/framework/kogitodataindex.go
  test/framework/kogitojobsservice.go
  test/framework/kogitomgmtconsole.go
  test/framework/kogitoserviceutils.go
  test/steps/kogitodataindex.go
  test/steps/kogitomgmtconsole.go
Labels: bdd-tests 🧪, needs review :mag:

#289 [master][KOGITO-1770] - Renaming examples and CR to match kogito-examples repo
  README.md
  cmd/kogito/command/deploy/deploy_service_test.go
  deploy/crds/app.kiegroup.org_v1alpha1_kogitoapp_cr.yaml
  deploy/examples/example-custom-build-images.yaml
  deploy/examples/process-quarkus-example-binary-builds.yaml
  deploy/examples/process-quarkus-example-persistence.yaml
  deploy/examples/process-quarkus-example.yaml
  deploy/examples/service-labels.yaml
  deploy/examples/springboot.yaml
  deploy/olm-catalog/kogito-operator/0.10.0/kogito-operator.v0.10.0.clusterserviceversion.yaml
  pkg/controller/kogitoapp/kogitoapp_controller_test.go
  pkg/controller/kogitoapp/resource/build_config_test.go
  pkg/controller/kogitoapp/resource/deployment_config_test.go
  pkg/controller/kogitoapp/resource/service_test.go
  pkg/infrastructure/kogito_images_test.go
Labels: ready :rocket:

#293 [0.9.x][KOGITO-1774] Updated test default config to 0.9.1-rc1
  test/.default_config
Labels: bdd-tests 🧪, needs review :mag:

#292 [master][KOGITO-1774] Updated test default config to 0.10.0-rc1
  test/.default_config
Labels: bdd-tests 🧪, ready :rocket:

#290 [0.9.x] [KOGITO-1407] Enable scenario 'Process instance events are stored in Data Index' with native enabled
  test/features/install_dataindex.feature
Labels: bdd-tests 🧪, ready :rocket:

#294 [0.9.x][KOGITO-1770] - Renaming examples and CR to match kogito-examples repo
  README.md
  cmd/kogito/command/deploy/deploy_service_test.go
  deploy/crds/app.kiegroup.org_v1alpha1_kogitoapp_cr.yaml
  deploy/examples/example-custom-build-images.yaml
  deploy/examples/onboarding-example.yaml
  deploy/examples/process-quarkus-example-binary-builds.yaml
  deploy/examples/process-quarkus-example-persistence.yaml
  deploy/examples/process-quarkus-example.yaml
  deploy/examples/service-labels.yaml
  deploy/examples/springboot.yaml
  deploy/examples/travelapp-kogito-travel-agency.yaml
  deploy/examples/travelapp-kogito-visas.yaml
  deploy/olm-catalog/kogito-operator/0.9.1/kogito-operator.v0.9.1.clusterserviceversion.yaml
  pkg/controller/kogitoapp/kogitoapp_controller_test.go
  pkg/controller/kogitoapp/resource/build_config_test.go
  pkg/controller/kogitoapp/resource/deployment_config_test.go
  pkg/controller/kogitoapp/resource/service_test.go
Labels: cherry-pick :cherries:, ready :rocket:

#295 [master][KOGITO-1407] Enable scenario 'Process instance events are stored in Data Index' with native enabled
  test/features/install_dataindex.feature
Labels: bdd-tests 🧪, cherry-pick :cherries:, ready :rocket:

#291 KOGITO-1699 - Unify configuration for KogitoApp deployments in BDD tests
  pkg/apis/app/v1alpha1/kogitoapp_types.go
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  test/features/deploy_quarkus_service.feature
  test/features/deploy_service_resources.feature
  test/features/deploy_springboot_service.feature
  test/features/install_dataindex.feature
  test/features/kogito_service_performance.feature
  test/features/prometheus.feature
  test/features/service_discovery.feature
  test/framework/kogitoapp.go
  test/steps/kogitoapp.go
  test/steps/openshift.go
  test/steps/utils.go
Labels: bdd-tests 🧪, needs review :mag:

#296 [0.9.x][KOGITO-1828] Updated test default config to 0.9.1-rc2
  test/.default_config
Labels: bdd-tests 🧪, needs review :mag:

#271 [master][KOGITO-1698]: Add instructions about how to debug the automation tests
  test/README.md
Labels: bdd-tests 🧪, ready :rocket:

#298 KOGITO-1415: Cucumber tests: enable scenario 'Discovery with onboardi…
  test/features/service_discovery.feature
Labels: bdd-tests 🧪, ready :rocket:

#299 [KOGITO-675] Add NAMESPACE env var to facilitate service discovery in…
  deploy/examples/onboarding-example.yaml
  pkg/controller/kogitoapp/resource/deployment_config.go
  pkg/controller/kogitoapp/resource/deployment_config_test.go
  test/framework/kogitoapp.go
  test/steps/utils.go
Labels: ready :rocket:

#301 KOGITO-1830: BDD tests: Test service discovery on Spring Boot applica…
  test/features/service_discovery.feature
Labels: bdd-tests 🧪, ready :rocket:

#303 KOGITO-1881: Cucumber tests: Execute commands from framework outputs …
  test/framework/cli.go
  test/framework/command.go
  test/steps/maven.go
  test/steps/openshift.go
Labels: bdd-tests 🧪, ready :rocket:

#302 KOGITO-1831: BDD tests: Test binary build via CLI is working for a Qu…
  test/features/binary_build.feature
  test/features/deploy_service_resources.feature
  test/features/deploy_springboot_service.feature
  test/features/kogito_service_performance.feature
  test/features/service_discovery.feature
  test/steps/kogitoapp.go
  test/steps/maven.go
Labels: bdd-tests 🧪, ready :rocket:

#223 [KOGITO-1499] Cucumber tests: migrate to godog 0.9.0
  Makefile
  README.md
  go.mod
  go.sum
  hack/run-tests.sh
  test/config/config.go
  test/feature.go
  test/features/deploy_quarkus_service.feature
  test/features/deploy_service_resources.feature
  test/features/install_dataindex.feature
  test/features/install_kogitoinfra.feature
  test/features/kogito_service_performance.feature
  test/features/service_discovery.feature
  test/framework/util.go
  test/main_test.go
  test/steps/data.go
  test/steps/graphql.go
  test/steps/http.go
  test/steps/kogitoapp.go
  test/steps/openshift.go
  test/steps/process.go
  test/steps/task.go
  test/steps/utils.go
Labels: bdd-tests 🧪, needs review :mag:

#307 [KOGITO-1926] Removed quarkus binary build from smoke tests
  test/features/binary_build.feature
Labels: bdd-tests 🧪, ready :rocket:

#309 Fix number of replicas in log entry
  test/framework/kogitoserviceutils.go
Labels: bdd-tests 🧪, ready :rocket:

#297 KOGITO-1829: BDD tests: Test that Spring boot cloud events are correc…
  test/features/deploy_quarkus_service.feature
  test/features/deploy_springboot_service.feature
  test/features/install_dataindex.feature
Labels: bdd-tests 🧪, ready :rocket:

#311 [KOGITO-1950] Tests: Skip tests when building binary builds
  test/features/binary_build.feature
  test/steps/maven.go
Labels: bdd-tests 🧪, ready :rocket:

#306 [KOGITO-1900] Data index Infinispan usernameKey and passwordKey were …
  go.sum
  pkg/infrastructure/infinispan_integration.go
  pkg/infrastructure/infinispan_integration_test.go
Labels: ready :rocket:

#312 [KOGITO-1728] - Release Kogito Operator/CLI 0.9.1
  deploy/examples/example-custom-build-images.yaml
  deploy/olm-catalog/kogito-operator/custom-subscription-example.yaml
  test/.default_config
Labels: ready :rocket:

#308 [KOGITO-1706] - Updating Architecture documentation
  docs/ARCHITECTURE.MD
  docs/img/general_archictecture.png
  docs/img/kogito_operator_packages.png
  docs/img/kogitoapp_resource_composition.png
  docs/img/packages_structure.png
Labels: ready :rocket:

#317 [KOGITO-865] Small refactor to reuse same functions to deploy data index
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/data_index_test.go
  cmd/kogito/command/install/kogito_operator.go
  cmd/kogito/command/message/data_index.go
  cmd/kogito/command/message/flags/project.go
  cmd/kogito/command/project/new_project.go
  cmd/kogito/command/project/use_project.go
  cmd/kogito/command/shared/install_data_index.go
  cmd/kogito/command/shared/install_services.go
Labels: needs review :mag:

#321 [KOGITO-2009] Updated bump-version script for test default cfg
  hack/bump-version.sh
Labels: needs review :mag:

#320 [KOGITO-2007] - Prepare Kogito Operator for 0.11.x version iteration
  .osdk-scorecard.yaml
  README.md
  cmd/kogito/version/version.go
  deploy/olm-catalog/kogito-operator/0.11.0/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/app.kiegroup.org_kogitomgmtconsoles_crd.yaml
  deploy/olm-catalog/kogito-operator/0.11.0/kogito-operator.v0.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/kogito-operator.package.yaml
  deploy/operator.yaml
  hack/go-build.sh
  hack/go-vet.sh
  test/.default_config
  version/version.go
Labels: ready :rocket:

#304 [KOGITO-1852] Corrected bug on pulling from internal Openshift in parallel
  hack/run-tests.sh.bats
  test/config/config.go
  test/framework/http.go
  test/framework/operator.go
Labels: bdd-tests 🧪, ready :rocket:

#310 KOGITO-1877: Cucumber tests should allow to change registry/namespace…
  Makefile
  README.md
  cmd/kogito/command/install/data_index.go
  hack/run-tests.sh
  hack/run-tests.sh.bats
  pkg/infrastructure/data_index.go
  pkg/infrastructure/jobs_service.go
  pkg/infrastructure/kogito_images.go
  pkg/infrastructure/mgmt_console.go
  pkg/infrastructure/services/deployment_test.go
  test/config/config.go
  test/framework/kogitoapp.go
  test/framework/kogitodataindex.go
  test/framework/kogitojobsservice.go
  test/framework/kogitomgmtconsole.go
  test/framework/kogitoserviceutils.go
  test/steps/kogitoapp.go
Labels: needs review :mag:

#323 [KOGITO-1771] Checking build status before triggering a new build
  pkg/client/openshift/buildconfig.go
  pkg/controller/kogitoapp/build/trigger.go
  pkg/controller/kogitoapp/kogitoapp_controller.go
  pkg/controller/kogitoapp/kogitoapp_controller_test.go
  pkg/util/arrays.go
  pkg/util/arrays_test.go
  pkg/util/envs.go
  pkg/util/maps.go
  pkg/util/maps_test.go
  pkg/util/type.go
Labels: ready :rocket:

#315 [KOGITO-1347] Test Data index using external Infinispan
  pkg/client/client.go
  pkg/client/meta/meta.go
  pkg/controller/kogitoinfra/infinispan/infinispan_credentials.go
  pkg/controller/kogitoinfra/infinispan/resource.go
  pkg/controller/kogitoinfra/infinispan/resource_test.go
  test/features/install_dataindex.feature
  test/framework/infinispan.go
  test/framework/kogitodataindex.go
  test/framework/kogitojobsservice.go
  test/framework/kogitomgmtconsole.go
  test/framework/kogitoserviceutils.go
  test/framework/kubernetes.go
  test/steps/data.go
  test/steps/infinispan.go
  test/steps/kogitodataindex.go
  test/steps/prometheus.go
Labels: bdd-tests 🧪, ready :rocket:

#324 KOGITO-2001: BDD tests: Refactor Deploy Quarkus and Deploy Spring Boo…
  test/features/binary_build.feature
  test/features/deploy_quarkus_service.feature
  test/features/deploy_springboot_service.feature
  test/features/deploy_travel_agency.feature
  test/features/kogito_service_performance.feature
  test/features/service_discovery.feature
  test/steps/process.go
Labels: bdd-tests 🧪, needs review :mag:

#314 KOGITO-1953: BDD tests: Test user task actions scenarios
  test/features/deploy_quarkus_service.feature
  test/features/deploy_springboot_service.feature
  test/framework/task.go
  test/steps/data.go
  test/steps/http.go
  test/steps/process.go
  test/steps/task.go
Labels: bdd-tests 🧪, ready :rocket:

#330 [KOGITO-2037] Adjust process-quarkus-example example for Kogito operator
  test/steps/utils.go
Labels: bdd-tests 🧪, ready :rocket:

#325 [KOGITO-2006] - Release Kogito Operator/CLI 0.10.0
  README.md
  deploy/olm-catalog/kogito-operator/custom-subscription-example.yaml
  deploy/olm-catalog/kogito-operator/kogito-operator.package.yaml
  test/.default_config
  test/README.md
Labels: ready :rocket:
