Repository kiegroup/kogito-operator, pull requests merged in 2020-07, with the labels that each got.

#416 [KOGITO-2611] BDD tests: `otherOptions` append corrected
  test/framework/maven.go
Labels: bdd-tests 🧪, needs review :mag:

#417 [KOGITO-2612] Set back correct default config
  test/.default_config
Labels: bdd-tests 🧪, needs review :mag:

#418 [KOGITO-2614] Disable `Data Index retrieves Quarkus process' events with native enabled` test
  test/features/deploy_quarkus_service.feature
Labels: bdd-tests 🧪, needs review :mag:

#415 KOGITO-2438: Cover Port changes configuration for Kogito services
  pkg/apis/app/v1alpha1/kogitoservices_types.go
  test/features/update_httpport.feature
  test/framework/kogitoserviceutils.go
  test/steps/kogito_service_table_parser.go
Labels: bdd-tests 🧪, ready :rocket:

#413 [KOGITO-2550] - Fixed vet test
  .circleci/config.yml
  go.sum
  hack/go-vet.sh
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
Labels: needs review :mag:

#419 [KOGITO-2628] Use nightly images for test dft config
  test/.default_config
Labels: bdd-tests 🧪, needs review :mag:, on hold :hand:

#414 [KOGITO-2594] Implement script to generate Kogito example images
  Makefile
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/config/config.go
  test/config/image_cache_mode.go
  test/framework/check_setup.go
  test/framework/util.go
  test/scripts/examples/process-optaplanner-quarkus.feature
  test/scripts/examples/process-quarkus-example.feature
  test/scripts/examples/process-springboot-example.feature
  test/steps/image_registry.go
Labels: bdd-tests 🧪, needs review :mag:

#421 [KOGITO-2646] Scenario names for KogitoRuntime tests not descriptive …
  test/features/deploy_kogito_runtime.feature
Labels: bdd-tests 🧪, needs review :mag:

#386 [KOGITO-2451] Migrate nightly pipelines to RHBA
  Jenkinsfile.deploy
  Jenkinsfile.promote
  Makefile
  hack/go-build.sh
Labels: needs review :mag:

#422 [KOGITO-2649] Default cfg contains app runtime
  test/.default_config
Labels: bdd-tests 🧪, ready :rocket:

#423 [KOGITO-2650] Setup retry HTTP calls for tests
  Makefile
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/.default_config
  test/config/config.go
  test/framework/http.go
Labels: bdd-tests 🧪, ready :rocket:

#429 [KOGITO-2616] Enable events quarkus native enabled
  test/features/deploy_quarkus_service.feature
Labels: bdd-tests 🧪, ready :rocket:

#425 [KOGITO-2662] - Migrate circleCi jobs of kogito-cloud-operator to Git…
  .circleci/config.yml
  .github/workflows/Kogito-Operator-PR-Check.yaml
  hack/addheaders.sh
  hack/coverage.sh
  hack/go-fmt.sh
Labels: ready :rocket:

#424 [KOGITO-2661] Deploy pipeline cannot build examples images
  Jenkinsfile.deploy
  test/framework/maven.go
  test/steps/maven.go
Labels: bdd-tests 🧪, ready :rocket:

#431 Remove circleci from the repo
  .circleci/config.yml
  .github/workflows/Kogito-Operator-PR-Check.yaml
Labels: ready :rocket:

#432 [KOGITO-2688] Removing listType=map from non-required objects
  deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/crds/app.kiegroup.org_kogitobuilds_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitobuilds_crd.yaml
  examples/process-quarkus-example-runtime-build-webhook.yaml
  examples/process-quarkus-example-runtime-build.yaml
  pkg/apis/app/v1alpha1/kogitoapp_types.go
  pkg/apis/app/v1alpha1/kogitobuild_types.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
Labels: needs review :mag:

#433 [KOGITO-2700] Tests: increase timeout and concurrent
  Jenkinsfile.deploy
  test/framework/namespace.go
Labels: bdd-tests 🧪, ready :rocket:

#435 [KOGITO-2702] Optimize bats tests runtime
  hack/run-tests.sh.bats
Labels: ready :rocket:

#434 [KOGITO-2701] Scenario after code blocked in case zookeeper pod resta…
  test/steps/data.go
Labels: bdd-tests 🧪, ready :rocket:

#436 [KOGITO-2100][KOGITO-2706] - Add Operator Framework OLM Integration T…
  .github/workflows/Kogito-Operator-PR-Check.yaml
  Makefile
  deploy/crds/app.kiegroup.org_v1alpha1_kogitoinfra_cr.yaml
  deploy/olm-catalog/kogito-operator/0.12.0/kogito-operator.v0.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  hack/ci/install-kind.sh
  hack/ci/install-operator-sdk.sh
  hack/ci/load-operator-image.sh
  hack/ci/operator-ensure-manifests.sh
  hack/ci/operator-olm-test.sh
  hack/ci/operatorhubio-catalog.Dockerfile
  hack/ci/start-kind.sh
  hack/export-version.sh
  hack/generate-manifests.sh
  hack/go-build.sh
  hack/go-vet.sh
Labels: ready :rocket:

#438 KOGITO-2692 - Integrate codecov with kogito-cloud-operator
  .github/workflows/Kogito-Operator-PR-Check.yaml
  codecov.yml
  hack/coverage.sh
Labels: needs review :mag:

#441 KOGITO-2725: Cucumber Tests: Fix undefined step for Install Managemen…
  test/features/update_httpport.feature
  test/framework/kogitomgmtconsole.go
  test/steps/kogitomgmtconsole.go
Labels: bdd-tests 🧪, ready :rocket:

#443 [KOGITO-2635] - Preparing release 0.12.0
  deploy/olm-catalog/kogito-operator/custom-subscription-example.yaml
  deploy/olm-catalog/kogito-operator/kogito-operator.package.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  examples/kubernetes/travel-agency/data-index.yaml
  examples/process-quarkus-example-runtime-build-webhook.yaml
Labels: ready :rocket:

#442 KOGITO-2692 codecov changed with GH actions
  .github/workflows/Kogito-Operator-PR-Check.yaml
Labels: needs review :mag:

#449 Changed the operator-testing image with previous version of operator-courier
  hack/ci/operator-olm-test.sh
Labels: ready :rocket:

#439 [KOGITO 2723] Post-release updates
  Jenkinsfile.deploy
  test/features/deploy_quarkus_service.feature
Labels: bdd-tests 🧪, ready :rocket:

#451 KOGITO-2522: Webhooks seems not working when deploying a Kogito Build
  pkg/controller/kogitobuild/build/build_config.go
  pkg/controller/kogitobuild/build/build_config_test.go
Labels: ready :rocket:

#450 KOGITO-2738 - Run unit tests only when change in operator or cli file…
  .github/workflows/Kogito-Operator-OLM-tests.yaml
  .github/workflows/Kogito-Operator-PR-Check.yaml
  .github/workflows/Kogito-Operator-Unit-tests.yaml
  codecov.yml
Labels: on hold :hand:, ready :rocket:

#404 [KOGITO-2119] - Kogito CLI support for setting variable values from s…
  cmd/kogito/command/deploy/common.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/jobs_service.go
  cmd/kogito/command/install/mgmt_console.go
  cmd/kogito/command/shared/converter_test.go
  cmd/kogito/command/shared/converters.go
  cmd/kogito/command/util/common_util.go
  cmd/kogito/command/util/common_util_test.go
  pkg/framework/env_var.go
  pkg/framework/env_var_test.go
  pkg/util/maps.go
  pkg/util/maps_test.go
Labels: ready :rocket:

#448 [KOGITO-2749] Tests: Fix invalid memory address for unsuccessful HTTP request
  test/framework/http.go
Labels: bdd-tests 🧪, ready :rocket:

#458 [KOGITO-2793] Set cr_deployment_only flag to true for image generation
  Makefile
Labels: bdd-tests 🧪, ready :rocket:

#445 [KOGITO-2747] Tests: Store log informations about image streams and K…
  test/framework/logging.go
  test/steps/data.go
Labels: bdd-tests 🧪, ready :rocket:

#461 [KOGITO-2797] - Fixing Deployment comparator
  pkg/controller/kogitodataindex/kogitodataindex_controller_test.go
  pkg/framework/comparator.go
  pkg/framework/comparator_test.go
  pkg/infrastructure/services/resources.go
Labels: ready :rocket:

#430 [KOGITO-2640] Upgrade tests to godog 0.10.0
  go.mod
  go.sum
  test/feature.go
  test/main_test.go
  test/steps/data.go
  test/steps/deploy_files.go
  test/steps/git.go
  test/steps/graphql.go
  test/steps/http.go
  test/steps/image_registry.go
  test/steps/infinispan.go
  test/steps/kafka.go
  test/steps/kogito_service_table_parser.go
  test/steps/kogitoapp.go
  test/steps/kogitobuild.go
  test/steps/kogitodataindex.go
  test/steps/kogitoinfra.go
  test/steps/kogitojobsservice.go
  test/steps/kogitomgmtconsole.go
  test/steps/kogitoruntime.go
  test/steps/kubernetes.go
  test/steps/maven.go
  test/steps/openshift.go
  test/steps/operator.go
  test/steps/process.go
  test/steps/prometheus.go
  test/steps/task.go
  test/steps/utils.go
Labels: bdd-tests 🧪, ready :rocket:

#463 [KOGITO-2825] - Change operator-testing image to latest
  .github/workflows/Kogito-Operator-OLM-tests.yaml
  hack/ci/operator-olm-test.sh
Labels: ready :rocket:

#460 [KOGITO-2795] Update bump-version.sh script
  hack/bump-version.sh
Labels: ready :rocket:

#456 [KOGITO-2786] - Run smoke tests only when necesarry
  .github/workflows/Kogito-Operator-OLM-tests.yaml
  .github/workflows/Kogito-Operator-PR-Check.yaml
  .github/workflows/Kogito-Operator-Unit-tests.yaml
  Jenkinsfile
Labels: needs review :mag:

#444 [KOGITO-2739] Tests: Add CLI support for KogitoRuntime and KogitoBuild
  test/features/deploy_kogito_build.feature
  test/features/deploy_kogito_runtime.feature
  test/features/deploy_source_files.feature
  test/framework/kogitoapp.go
  test/framework/kogitobuild.go
  test/framework/kogitodataindex.go
  test/framework/kogitojobsservice.go
  test/framework/kogitomgmtconsole.go
  test/framework/kogitoruntime.go
  test/framework/kogitoserviceutils.go
  test/framework/mappers/cr_to_cli.go
  test/framework/util.go
  test/steps/deploy_files.go
  test/steps/kogito_service_table_parser.go
  test/steps/kogitoapp.go
  test/steps/kogitobuild.go
  test/steps/kogitodataindex.go
  test/steps/kogitojobsservice.go
  test/steps/kogitomgmtconsole.go
  test/steps/kogitoruntime.go
  test/steps/mappers/create_kogito_build.go
  test/steps/mappers/create_kogito_service.go
  test/steps/mappers/shared_functions.go
  test/types/holder.go
Labels: bdd-tests 🧪, ready :rocket:

#467 [KOGITO-2813] - Renaming KogitoApp description to KogitoService, Fixes #462
  deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.13.0/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/manifests/kogito-operator.clusterserviceversion.yaml
  pkg/apis/app/v1alpha1/kogitoapp_types.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
Labels: ready :rocket:

#472 [KOGITO-2878] Align operator OLM test scripts to reflect directory ch…
  hack/ci/operator-ensure-manifests.sh
Labels: ready :rocket:

#473 [KOGITO-2880] - Fix failing lint stage
  deploy/olm-catalog/kogito-operator/0.13.0/kogito-operator.v0.13.0.clusterserviceversion.yaml
Labels: needs review :mag:

#468 [KOGITO-2827] - Use environment variable when no Data Index route ava…
  examples/kubernetes/travel-agency/deploy.sh
  examples/kubernetes/travel-agency/management-console-ingress.yaml
  examples/kubernetes/travel-agency/management-console.yaml
  pkg/infrastructure/services/deployer.go
  pkg/infrastructure/services/resources.go
  pkg/infrastructure/services/resources_test.go
Labels: ready :rocket:

#465 [KOGITO-2850] Tests: Add Maven mirror configuration for local Maven builds
  test/framework/maven.go
Labels: bdd-tests 🧪, ready :rocket:

#476 KOGITO-2903 KogitoBuild include custom maven repo
  test/framework/kogitobuild.go
Labels: bdd-tests 🧪, needs review :mag:

#457 [KOGITO-2790] Setup build examples images
  Jenkinsfile
  test/framework/container_engine.go
Labels: bdd-tests 🧪, ready :rocket:

#477 [cherry-pick][KOGITO-2903] KogitoBuild include custom maven repo
  test/framework/kogitobuild.go
Labels: bdd-tests 🧪, cherry-pick :cherries:, ready :rocket:

#478 [KOGITO-2904] Tests: Enable KogitoRuntime tests
  test/features/deploy_kogito_runtime.feature
Labels: bdd-tests 🧪, ready :rocket:

#480 [KOGITO-2916] CLI auto-completion for fish shell
  cmd/kogito/command/completion/completion.go
Labels: ready :rocket:

#481 [KOGITO-2917] Update contributors' guide link in PR template
  .github/pull_request_template.md
Labels: ready :rocket:
