Repository kiegroup/kogito-operator, pull requests merged in 2020-01, with the labels that each got.

#135 [KOGITO-850] Add Cucumber test for Prometheus integration
  pkg/client/client.go
  pkg/client/meta/meta.go
  test/smoke/disabled/deploy_prometheus.feature
  test/smoke/kubernetes.go
  test/smoke/main_test.go
  test/smoke/openshift.go
  test/smoke/prometheus.go
  test/smoke/util.go
Labels: ready :rocket:

#120 [KOGITO-261] Installs default Data Index service when creating a new …
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/kogito_operator.go
  cmd/kogito/command/install/kogito_operator_test.go
  cmd/kogito/command/message/data_index.go
  cmd/kogito/command/message/infra.go
  cmd/kogito/command/project/new_project.go
  cmd/kogito/command/project/new_project_test.go
  cmd/kogito/command/project/use_project.go
  cmd/kogito/command/shared/install_data_index.go
  cmd/kogito/command/shared/install_operator.go
  cmd/kogito/command/shared/install_operator_test.go
  cmd/kogito/command/shared/install_services.go
  deploy/crds/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/crds/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.7.0-rc1/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.7.0-rc1/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.7.0-rc1/kogito-operator.v0.7.0-rc1.clusterserviceversion.yaml
  pkg/client/client.go
  pkg/client/meta/meta.go
  pkg/controller/kogitodataindex/kogitodataindex_controller.go
  pkg/controller/kogitodataindex/resource/defaults.go
Labels: ready :rocket:

#139 [KOGITO-870] Operator: Spring Boot Persistence not working
  pkg/controller/kogitoapp/resource/deployment_config.go
  pkg/controller/kogitoapp/resource/deployment_config_test.go
  test/smoke/features/deploy_springboot_with_persistence.feature
Labels: needs review :mag:

#140 [KOGITO-871] Prepare Operator 0.7.0-rc4 release
  .osdk-scorecard.yaml
  README.md
  cmd/kogito/version/version.go
  deploy/examples/jbpm-quarkus-example-persistence.yaml
  deploy/examples/jbpm-quarkus-example.yaml
  deploy/examples/kogito-kafka-quickstart-quarkus.yaml
  deploy/examples/onboarding-example.yaml
  deploy/examples/travelapp-kogito-travel-agency.yaml
  deploy/examples/travelapp-kogito-visas.yaml
  deploy/olm-catalog/kogito-operator/0.7.0-rc4/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.7.0-rc4/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.7.0-rc4/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/olm-catalog/kogito-operator/0.7.0-rc4/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.7.0-rc4/kogito-operator.v0.7.0-rc4.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/kogito-operator.package.yaml
  deploy/operator.yaml
  hack/go-build.sh
  hack/go-vet.sh
  version/version.go
Labels: ready :rocket:

#136 [KOGITO-852] Detect running operator using subscription name
  cmd/kogito/command/shared/operatorhub.go
  pkg/framework/subscription.go
  pkg/infrastructure/operator.go
  test/smoke/operator.go
Labels: ready :rocket:

#142 [KOGITO-691] - Creating new tags when ImageStream already exists
  deploy/olm-catalog/kogito-operator/0.7.0-rc4/kogito-operator.v0.7.0-rc4.clusterserviceversion.yaml
  pkg/client/openshift/imagestream.go
  pkg/controller/kogitoapp/kogitoapp_controller.go
  pkg/controller/kogitoapp/kogitoapp_controller_test.go
  pkg/controller/kogitoapp/resource/kogito_imagestream.go
  pkg/controller/kogitoapp/resource/kogito_imagestream_test.go
  pkg/controller/kogitoapp/resource/requested_resources.go
  pkg/framework/comparator.go
Labels: on hold :hand:

#144 [KOGITO-915] Change operator base image from 'registry.redhat.io' to 'registry.access.redhat.com'
  build/Dockerfile
Labels: needs review :mag:

#143 [KOGITO-614] Deploy Kafka for Data Index with Infra
  README.md
  cmd/kogito/command/install/data_index.go
  cmd/kogito/command/install/data_index_test.go
  cmd/kogito/command/shared/install_data_index.go
  deploy/crds/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/crds/app.kiegroup.org_v1alpha1_kogitodataindex_cr.yaml
  deploy/examples/data-index.yaml
  deploy/olm-catalog/kogito-operator/0.7.0-rc4/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.7.0-rc4/kogito-operator.v0.7.0-rc4.clusterserviceversion.yaml
  docs/img/strimzi_installed.png
  pkg/apis/app/v1alpha1/kogitodataindex_types.go
  pkg/apis/app/v1alpha1/types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/kogitodataindex/kogitodataindex_controller.go
  pkg/controller/kogitodataindex/kogitodataindex_controller_test.go
  pkg/controller/kogitodataindex/resource/kafka.go
  pkg/controller/kogitodataindex/resource/kafka_test.go
  pkg/controller/kogitodataindex/resource/requested_resources.go
  pkg/controller/kogitodataindex/resource/requested_resources_test.go
  pkg/controller/kogitodataindex/status/manage_status_test.go
  pkg/controller/kogitoinfra/kafka/resource.go
  pkg/infrastructure/infinispan_integration.go
  pkg/infrastructure/kafka.go
  pkg/infrastructure/kafka_integration.go
  pkg/infrastructure/kafka_integration_test.go
  pkg/infrastructure/kafka_test.go
Labels: ready :rocket:

#150 [KOGITO-938] [Bug] If the kogitoinfra already exists, the infrastructure package will overwrite the components installation values
  pkg/infrastructure/kogitoinfra.go
  pkg/infrastructure/kogitoinfra_test.go
Labels: ready :rocket:

#151 [KOGITO-946] - Forcing 'false' to KOGITO_PROTOBUF_WATCH' env var on D…
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/kogitodataindex/resource/defaults.go
  pkg/controller/kogitodataindex/resource/statefulset.go
  pkg/controller/kogitodataindex/resource/statefulset_test.go
  pkg/infrastructure/kogitoinfra_test.go
Labels: ready :rocket:

#149 [KOGITO-919] Release 0.7.0 version
  .osdk-scorecard.yaml
  README.md
  cmd/kogito/version/version.go
  deploy/crds/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/examples/jbpm-quarkus-example-persistence.yaml
  deploy/examples/jbpm-quarkus-example.yaml
  deploy/examples/kogito-kafka-quickstart-quarkus.yaml
  deploy/examples/onboarding-example.yaml
  deploy/examples/travelapp-kogito-travel-agency.yaml
  deploy/examples/travelapp-kogito-visas.yaml
  deploy/olm-catalog/kogito-operator/0.7.0/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/olm-catalog/kogito-operator/0.7.0/app.kiegroup.org_kogitodataindices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.7.0/app.kiegroup.org_kogitoinfras_crd.yaml
  deploy/olm-catalog/kogito-operator/0.7.0/app.kiegroup.org_kogitojobsservices_crd.yaml
  deploy/olm-catalog/kogito-operator/0.7.0/kogito-operator.v0.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/kogito-operator/kogito-operator.package.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/go-build.sh
  hack/go-vet.sh
  pkg/apis/app/v1alpha1/kogitoinfra_types.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  vendor/github.com/machinebox/graphql/.gitignore
  vendor/github.com/machinebox/graphql/.travis.yml
  vendor/github.com/machinebox/graphql/LICENSE
  vendor/github.com/machinebox/graphql/README.md
  vendor/github.com/machinebox/graphql/graphql.go
  vendor/modules.txt
  version/version.go
Labels: ready :rocket:

#148 [KOGITO-692] Allowing specific images to be set for build configurations
  cmd/kogito/command/deploy/common.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/install/jobs_service.go
  cmd/kogito/command/shared/converters.go
  cmd/kogito/command/shared/converters_test.go
  deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml
  deploy/examples/example-custom-build-images.yaml
  deploy/examples/jbpm-quarkus-example-persistence.yaml
  deploy/examples/kogito-kafka-quickstart-quarkus.yaml
  deploy/examples/onboarding-example.yaml
  deploy/examples/travelapp-kogito-travel-agency.yaml
  deploy/examples/travelapp-kogito-visas.yaml
  deploy/olm-catalog/kogito-operator/0.7.0/app.kiegroup.org_kogitoapps_crd.yaml
  pkg/apis/app/v1alpha1/kogitoapp_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/kogitoapp/kogitoapp_controller.go
  pkg/controller/kogitoapp/kogitoapp_controller_test.go
  pkg/controller/kogitoapp/resource/build_config.go
  pkg/controller/kogitoapp/resource/build_config_runtime.go
  pkg/controller/kogitoapp/resource/build_config_s2i.go
  pkg/controller/kogitoapp/resource/build_config_test.go
  pkg/controller/kogitoapp/resource/kogito_imagestream.go
  pkg/controller/kogitoapp/resource/kogito_imagestream_test.go
  pkg/framework/image.go
  pkg/framework/image_test.go
  test/e2e/kogitoapp_test.go
  test/smoke/framework/kogitoapp.go
Labels: ready :rocket:

#153 [KOGITO-956] Disable smoke test for springboot-example with persistence because of KOGITO-948
  test/smoke/features/cli/cli_deploy_springboot_service.feature
  test/smoke/features/operator/deploy_springboot_service.feature
Labels: ready :rocket:

#154 [KOGITO-939] Set the concurrent tests as parameter
  Makefile
  README.md
  hack/run-smoke.sh
Labels: needs review :mag:

#152 [KOGITO-912] Setup tests for Kogito Infra components
  pkg/infrastructure/kogitoinfra.go
  pkg/infrastructure/kogitoinfra_test.go
  test/smoke/features/cli/cli_install_dataindex.feature
  test/smoke/features/cli/cli_install_kogitoinfra_components.feature
  test/smoke/features/operator/install_kogitoinfra.feature
  test/smoke/framework/cli.go
  test/smoke/framework/kogitoinfra.go
  test/smoke/framework/operator.go
  test/smoke/framework/util.go
  test/smoke/steps/cli.go
  test/smoke/steps/data.go
  test/smoke/steps/kafka.go
  test/smoke/steps/kogitoinfra.go
Labels: ready :rocket:

#155 [KOGITO-941] Tests operator deployment via yaml files should use the files from Filesystem and not from Github master
  Makefile
  README.md
  hack/run-smoke.sh
  test/smoke/README.md
  test/smoke/framework/cli.go
  test/smoke/framework/env.go
  test/smoke/framework/kogitoapp.go
  test/smoke/framework/operator.go
  test/smoke/framework/util.go
Labels: needs review :mag:

#156 [KOGITO-872] Add Cucumber test for Data Index integration
  test/smoke/features/operator/install_dataindex_service.feature
  test/smoke/framework/graphql.go
  test/smoke/framework/kogitoapp.go
  test/smoke/framework/kogitodataindexservice.go
  test/smoke/steps/graphql.go
  test/smoke/steps/graphql_queries.go
  test/smoke/steps/kogitoapp.go
  test/smoke/steps/kogitodataindex.go
Labels: ready :rocket:

#158 [KOGITO-972] Allow to change the image-builder when building the operator
  Makefile
  hack/go-build.sh
Labels: ready :rocket:
