Repository kiegroup/kogito-operator, pull requests merged in 2020-12, with the labels that each got.

#681 [KOGITO-3864] - KogitoInfra gets deleted when refering KogitoRuntime/KogitoSupportingService delete
  RELEASE_NOTES.md
  pkg/controller/add_kogitoruntime.go
  pkg/controller/add_kogitosupportingservice.go
  pkg/controller/kogitoinfra/kogitoinfra_controller.go
  pkg/controller/kogitoruntime/kogitoruntime_controller.go
  pkg/controller/kogitoruntime/kogitoruntime_finalizer.go
  pkg/controller/kogitosupportingservice/kogitosupportingservice_controller.go
  pkg/controller/kogitosupportingservice/kogitosupportingservice_finalizer.go
  pkg/framework/owner.go
  pkg/framework/owner_test.go
  pkg/infrastructure/kogito_infra.go
  pkg/infrastructure/kogito_infra_test.go
  pkg/infrastructure/kogito_service.go
  pkg/infrastructure/kogito_service_test.go
Labels: operator :cloud:, ready :rocket:

#683 [KOGITO-3960] Add log monitoring for OLM namespace
  test/framework/operator.go
  test/main_test.go
Labels: bdd-tests 🧪, needs review :mag:

#684 [KOGITO-3961] Adjust clean-stuck-namespaces.sh with Kogito CRs
  hack/clean-stuck-namespaces.sh
Labels: bdd-tests 🧪, needs review :mag:

#686 [KOGITO-3962] BDD tests: Set load factor to 1 for nightlies/release
  Jenkinsfile.deploy
Labels: bdd-tests 🧪, needs review :mag:

#685 [KOGITO-3960] Store OLM logs for PR checks and nightly builds
  Jenkinsfile
  Jenkinsfile.deploy
Labels: CI/CD :loop:, ready :rocket:

#682 KOGITO-3343 - Failover scenario for scaling Infinispan to 0 using BDD…
  README.md
  test/features/deploy_kogito_runtime.feature
  test/framework/http.go
  test/framework/infinispan.go
  test/steps/http.go
  test/steps/infinispan.go
Labels: bdd-tests 🧪, ready :rocket:

#688 [KOGITO-3966] Update explainability BDD test
  test/features/install_explainability.feature
Labels: bdd-tests 🧪, needs review :mag:

#692 Disabling the OLM tests until KOGITO-3979 is fixed
  .github/workflows/Kogito-Operator-OLM-tests.yaml
Labels: needs review :mag:

#687 [KOGITO-3947] - Fix infinite reconciliation loop when no env var is defined
  RELEASE_NOTES.md
  examples/jobs-service.yaml
  hack/install-manifests.sh
  pkg/infrastructure/kogito_service.go
  pkg/infrastructure/services/deployment.go
  pkg/infrastructure/services/deployment_test.go
  pkg/test/fake_client.go
Labels: operator :cloud:, ready :rocket:

#680 [KOGITO-3939] Adjust readiness and liveness probes
  pkg/apis/app/v1beta1/kogitoservices_types.go
  test/framework/kogitoruntime.go
  test/framework/kogitoserviceutils.go
Labels: bdd-tests 🧪, operator :cloud:, ready :rocket:

#690 [KOGITO-3977] Release: Add branch to PR creation
  Jenkinsfile.deploy
  Jenkinsfile.promote
Labels: needs review :mag:

#691 [KOGITO-3968] - Add support to deploy Kogito services from SW files
  RELEASE_NOTES.md
  cmd/kogito/command/deploy/delete_service.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/deploy/testdata/greetings.sw.json
  cmd/kogito/command/iozip/zip_files.go
  cmd/kogito/command/service/build_service.go
  cmd/kogito/command/shared/install_operator_test.go
  cmd/kogito/command/shared/resource_checks_test.go
  cmd/kogito/command/test/common.go
  go.mod
  go.sum
  pkg/client/client.go
Labels: cli 💻, operator :cloud:, ready :rocket:

#694 [KOGITO-3938] Add option to run tests with Kogito cluster wide operator
  Jenkinsfile
  Jenkinsfile.deploy
  Makefile
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/config/config.go
  test/framework/namespace.go
  test/framework/operator.go
  test/main_test.go
  test/steps/operator.go
Labels: CI/CD :loop:, bdd-tests 🧪, ready :rocket:

#696 [KOGITO-4016] Don't deploy Kogito operator when building example images
  Jenkinsfile
  Jenkinsfile.deploy
Labels: CI/CD :loop:, needs review :mag:

#697 [KOGITO-3908] Don't commit go.mod&go.sum in release pipeline when changing version
  Jenkinsfile.deploy
Labels: ready :rocket:

#698 [KOGITO-3863] Setup timeout to pipelines
  Jenkinsfile.copy_csv_files
  Jenkinsfile.deploy
  Jenkinsfile.promote
Labels: CI/CD :loop:, ready :rocket:

#699 [KOGITO-4046] - Deploying a new Kogito service from files in CLI not …
  RELEASE_NOTES.md
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/iozip/zip_files.go
Labels: cli 💻, on hold :hand:

#703 Update RELEASE_NOTES.md
  RELEASE_NOTES.md
Labels: ready :rocket:
