Repository kiegroup/kogito-operator, pull requests merged in 2021-11, with the labels that each got.

#1068 [KOGITO-6232] - migrate the prod build files from rhpam-kogito-operat…
  osbs-extra/gating.yaml
Labels: ready :rocket:

#1011 [KOGITO-5947] BDD - Kogito Services failover tests
  go.mod
  go.sum
  hack/run-tests.sh
  test/features/install_dataindex.feature
  test/features/install_jobs_service.feature
  test/features/install_trusty.feature
  test/go.mod
  test/go.sum
  test/pkg/framework/graphql.go
  test/pkg/framework/http.go
  test/pkg/framework/kubernetes.go
  test/pkg/framework/mongodb.go
  test/pkg/framework/postgresql.go
  test/pkg/steps/graphql.go
  test/pkg/steps/graphql_queries.go
  test/pkg/steps/http.go
  test/pkg/steps/mongodb.go
  test/pkg/steps/postgresql.go
Labels: needs review :mag:, bdd-tests 🧪

#1069 [KOGITO-6260] BDD tests: Don't delete Subscriptions not created by BDD
  test/pkg/framework/operator.go
Labels: ready :rocket:

#1070 Fix tests to disable_clean_cluster
  test/Makefile
Labels: ready :rocket:, bdd-tests 🧪

#1072 Updated GHA: cache is specific to Go version
  .github/workflows/Kogito-Operator-OLM-tests.yaml
  .github/workflows/Kogito-Operator-PR-Check.yaml
  .github/workflows/Kogito-Operator-Unit-tests.yaml
Labels: needs review :mag:

#1067 [KOGITO-6230] Do not set GOOS/GOARCH
  hack/go-build-cli.sh
  hack/go-install-cli.sh
  modules/org.kie.kogito.app.buildProfilingOperator/install.sh
  modules/org.kie.kogito.app.builder/install.sh
  modules/org.kie.kogito.rhpam.builder/install.sh
Labels: needs review :mag:

#1074 [RHPAM-4027] - RHPAM Kogito Operator OLM page links should point to R…
  config/crd/rhpam/bases/rhpam.kiegroup.org_kogitoruntimes.yaml
  config/crd/rhpam/bases/rhpam.kiegroup.org_kogitosupportingservices.yaml
  config/manifests/rhpam/bases/rhpam-kogito-operator.clusterserviceversion.yaml
  rhpam-operator.yaml
Labels: needs review :mag:

#1079 [1.14.x] Fix bdd tests
  test/features/deploy_kogito_runtime.feature
  test/features/keycloak.feature
  test/go.mod
  test/go.sum
Labels: ready :rocket:, bdd-tests 🧪

#1080 Fix BDD tests
  test/features/deploy_kogito_runtime.feature
  test/features/keycloak.feature
Labels: ready :rocket:, bdd-tests 🧪

#1073 KOGITO-6294 : ProtoBuf ConfigMap should be created on instantiation o…
  controllers/common/runtime_controller.go
  core/kogitosupportingservice/dataindex_reconciler.go
  core/shared/protobuf.go
  core/shared/protobuf_configmap.go
  core/shared/protobuf_configmap_reconciler.go
Labels: needs review :mag:, operator :cloud:
