Repository kiegroup/kogito-operator, pull requests merged in 2021-06, with the labels that each got.

#895 [1.7.x] [KOGITO-5263] BDD tests: Ignore Keycloak URL difference in retrieved …
  test/features/keycloak.feature
Labels: bdd-tests 🧪, needs review :mag:

#894 [KOGITO-5263] BDD tests: Ignore Keycloak URL difference in retrieved …
  test/features/keycloak.feature
Labels: bdd-tests 🧪, needs review :mag:

#893 [KOGITO-5256] - Fix Knative Trigger creation
  RELEASE_NOTES.md
  core/kogitoservice/messaging_knative.go
  core/kogitoservice/messaging_knative_test.go
  core/test/env.go
Labels: needs review :mag:, operator :cloud:

#901 KOGITO-5297 Enable process-timer native BDD test
  test/features/deploy_kogito_runtime.feature
Labels: bdd-tests 🧪, ready :rocket:

#904 KOGITO-5303 BDD: Disable SSL on Git option
  hack/run-tests.sh
  test/Makefile
  test/features/deploy_kogito_build.feature
  test/pkg/config/config.go
  test/pkg/steps/kogitobuild.go
Labels: bdd-tests 🧪, needs review :mag:

#907 [1.5.x] Change source folder BDD test to use dmn project
  test/features/deploy_source_files.feature
Labels: bdd-tests 🧪, needs review :mag:

#908 [KOGITO-5312] BDD tests: Implement service installer for Prometheus
  test/pkg/installers/prometheus_installer.go
  test/pkg/steps/prometheus.go
Labels: bdd-tests 🧪, ready :rocket:

#909 [KOGITO-5316] BDD tests: Wrong Jobs service image is used for Infinis…
  core/kogitosupportingservice/jobsservice_reconciler.go
  test/features/install_jobs_service.feature
  test/pkg/steps/kogitojobsservice.go
Labels: bdd-tests 🧪, needs review :mag:, operator :cloud:

#888 [KOGITO-5205] - ImageStream tag is not updated when image parameter i…
  controllers/kogitoruntime_controller.go
  controllers/kogitoruntime_controller_test.go
  controllers/kogitoruntime_finalizer.go
  controllers/kogitoruntime_finalizer_test.go
  controllers/kogitosupportingservice_controller_test.go
  core/framework/owner.go
  core/framework/owner_test.go
  core/framework/util/arrays.go
  core/framework/util/arrays_test.go
  core/infrastructure/image.go
  core/infrastructure/image_test.go
  core/infrastructure/imagestream.go
  core/infrastructure/imagestream_reconciler.go
  core/infrastructure/imagestream_test.go
  core/kogitoruntime/imagestream_finalizer.go
  core/kogitoservice/configmap.go
  core/kogitoservice/configmap_test.go
  core/kogitoservice/dashboards.go
  core/kogitoservice/deployer.go
  core/kogitoservice/deployer_resources.go
  core/kogitoservice/deployer_resources_test.go
  core/kogitoservice/deployer_test.go
  core/kogitoservice/errors.go
  core/kogitoservice/infra_finalizer.go
  core/kogitoservice/infra_finalizer_test.go
  core/kogitoservice/prometheus.go
  core/kogitosupportingservice/dataindex_reconciler_test.go
  core/kogitosupportingservice/explainability_reconciler_test.go
  core/kogitosupportingservice/jobsservice_reconciler_test.go
  core/kogitosupportingservice/mgmtconsole_reconciler_test.go
  core/kogitosupportingservice/taskconsole_reconciler_test.go
  core/kogitosupportingservice/trustyai_reconciler_test.go
  core/kogitosupportingservice/trustyui_reconciler_test.go
  core/manager/infra_manager.go
  core/test/imagestream.go
Labels: needs review :mag:, operator :cloud:

#910 [KOGITO-5348] BDD tests: Use Grafana image based on digest
  core/kogitoservice/dashboards.go
  go.mod
  go.sum
  test/pkg/framework/grafana.go
  test/pkg/framework/kubernetes.go
Labels: bdd-tests 🧪, needs review :mag:, operator :cloud:

#911 [KOGITO-5313][KOGITO-5315] Upgrade Kogito operator and BDD tests to Infinispan 12
  README.md
  RELEASE_NOTES.md
  core/kogitoinfra/infinispan_reconciler.go
  core/kogitoinfra/infinispan_reconciler_test.go
  go.mod
  go.sum
  test/pkg/framework/infinispan.go
  test/pkg/installers/infinispan_installer.go
Labels: bdd-tests 🧪, operator :cloud:, ready :rocket:

#912 [KOGITO-5393] BDD tests: Concurrent map read and map write error
  test/pkg/framework/logging.go
Labels: bdd-tests 🧪, ready :rocket:

#914 [1.8.x] [KOGITO-5393] BDD tests: Concurrent map read and map write error
  test/pkg/framework/logging.go
Labels: bdd-tests 🧪, ready :rocket:

#902 KOGITO-5262 Remove reference to no longer used consumers
  core/kogitosupportingservice/dataindex_reconciler.go
Labels: operator :cloud:, ready :rocket:

#915 [1.8.x] KOGITO-5262 Remove reference to no longer used consumers (#902)
  core/kogitosupportingservice/dataindex_reconciler.go
Labels: needs review :mag:, operator :cloud:
