Repository kiegroup/kogito-operator, pull requests merged in 2021-03, with the labels that each got.

#773 [KOGITO-4546] - Create make olm-manifests target responsible for crea…
  Makefile
  README.md
  hack/create-olm-manifests.sh
Labels: CI/CD :loop:, needs review :mag:

#775 [1.3.x][KOGITO-4546] - Create make olm-manifests target responsible for crea…
  Makefile
  README.md
  hack/create-olm-manifests.sh
Labels: cherry-pick :cherries:, needs review :mag:

#762 KOGITO-4444 - Sanitize dashboard name
  core/kogitoservice/dashboards.go
  core/kogitoservice/dashboards_test.go
Labels: CI/CD :loop:, bdd-tests 🧪, cli 💻, operator :cloud:, ready :rocket:

#774 [1.3.x] KOGITO-4444 - cherry pick grafana dashboard regex sanitizer
  pkg/infrastructure/services/dashboards.go
  pkg/infrastructure/services/dashboards_test.go
Labels: cherry-pick :cherries:, ready :rocket:

#778 Fix image reference in some examples and guide
  docs/GUIDE_TO_KOGITO_DEVS.md
  examples/quarkus-jvm.Dockerfile
  examples/springboot.Dockerfile
Labels: ready :rocket:

#779 [1.3.x] Fix image reference in some examples and guide
  docs/GUIDE_TO_KOGITO_DEVS.md
  examples/quarkus-jvm.Dockerfile
  examples/springboot.Dockerfile
Labels: ready :rocket:

#776 [KOGITO-4553] Panic when even number of proto files are available in …
  controllers/runtime_deployer.go
Labels: operator :cloud:, ready :rocket:

#783 [KOGITO-4583] Revert lint to version v1.37.1
  .github/workflows/Kogito-Operator-PR-Check.yaml
  hack/go-lint.sh
Labels: needs review :mag:

#782 [KOGITO-4572] KogitoInfra doesn't detect running Infinispan instance
  core/kogitoinfra/infinispan_reconciler.go
Labels: operator :cloud:, ready :rocket:

#785 KOGITO-4616 - Revise BDD tests debugging instructions and add GoLand
  test/README.md
Labels: bdd-tests 🧪, needs review :mag:

#784 [KOGITO-233] - Migrate Operator image generation to CEKit
  .github/workflows/Kogito-Operator-OLM-tests.yaml
  Dockerfile
  Makefile
  README.md
  RELEASE_NOTES.md
  image.yaml
  modules/buildOperator/install.sh
  modules/buildOperator/module.yaml
  modules/goModDownload/install.sh
  modules/goModDownload/module.yaml
Labels: needs review :mag:

#787 [KOGITO-4620] - role.yaml is not updating
  Makefile
Labels: ready :rocket:

#705 KOGITO-3948 - Change trusty infinispan default image name
  core/kogitosupportingservice/trustyai_reconciler.go
Labels: needs review :mag:, operator :cloud:

#791 KOGITO-4644 Support Quarkus fast-jar
  cmd/kogito/command/converter/binarybuildtype_converter.go
  cmd/kogito/command/converter/binarybuildtype_converter_test.go
  cmd/kogito/command/converter/native_converter_test.go
  cmd/kogito/command/converter/runtimetype_converter.go
  cmd/kogito/command/converter/runtimetype_converter_test.go
  cmd/kogito/command/flag/binary_build_type.go
  cmd/kogito/command/iozip/zip_files.go
  cmd/kogito/command/iozip/zip_files_test.go
  cmd/kogito/command/service/build_service.go
  cmd/kogito/command/test/mkdir.go
  docs/GUIDE_TO_KOGITO_DEVS.md
  examples/quarkus-jvm.Dockerfile
  test/framework/dockerfile_provider.go
Labels: bdd-tests 🧪, cli 💻, ready :rocket:

#793 [KOGITO-4644] Update release notes
  RELEASE_NOTES.md
Labels: needs review :mag:

#794 [KOGITO-4675] Kogito operator PR check doesn't work after repository …
  .jenkins/dsl/jobs.groovy
  Jenkinsfile
Labels: CI/CD :loop:, needs review :mag:

#755 [KOGITO-4412] New service installer approach for BDD tests
  test/features/data_index_performance.feature
  test/features/deploy_kogito_runtime.feature
  test/features/deploy_travel_agency.feature
  test/features/install_dataindex.feature
  test/features/install_explainability.feature
  test/features/install_jobs_service.feature
  test/features/install_mgmtconsole.feature
  test/features/install_taskconsole.feature
  test/features/install_trusty.feature
  test/features/keycloak.feature
  test/features/kogito_service_performance.feature
  test/features/olm/cli_install_operator.feature
  test/features/olm/cli_new_project.feature
  test/features/olm/cli_use_project.feature
  test/framework/kubernetes.go
  test/framework/logging.go
  test/framework/mongodb.go
  test/framework/namespace.go
  test/framework/operator.go
  test/installers/grafana_installer.go
  test/installers/infinispan_installer.go
  test/installers/kafka_installer.go
  test/installers/keycloak_installer.go
  test/installers/knative_installer.go
  test/installers/kogito_installer.go
  test/installers/mongodb_installer.go
  test/installers/service_installer.go
  test/main_test.go
  test/scripts/prune_namespaces.go
  test/steps/data.go
  test/steps/grafana.go
  test/steps/infinispan.go
  test/steps/kafka.go
  test/steps/keycloak.go
  test/steps/knative.go
  test/steps/mongodb.go
  test/steps/operator.go
Labels: bdd-tests 🧪, ready :rocket:

#796 Branching 1.4.x - Reset release notes
  RELEASE_NOTES.md
Labels: ready :rocket:

#795 [1.4.x] Update version to 1.4.0-snapshot
  Makefile
  README.md
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  cmd/kogito/version/version.go
  config/manager/kustomization.yaml
  config/manifests/bases/kogito-operator.clusterserviceversion.yaml
  kogito-operator.yaml
  test/.default_config
  version/version.go
Labels: bdd-tests 🧪, cli 💻, needs review :mag:

#797 Fix typo in MongoDB BDD test
  test/features/install_dataindex.feature
Labels: bdd-tests 🧪, needs review :mag:

#792 [KOGITO-4453] Fix overwriting propertiesConfigMap
  RELEASE_NOTES.md
  core/kogitoservice/deployer_resources.go
  core/kogitoservice/deployer_resources_test.go
  core/test/kogitosupportingservice.go
Labels: needs review :mag:, operator :cloud:

#798 KOGITO-3107 DSL: Correct repo name
  .jenkins/dsl/jobs.groovy
Labels: needs review :mag:

#799 Add Kogito operator tested integrations into readme
  README.md
Labels: needs review :mag:

#802 [KOGITO-4703] correct bats test
  hack/update_test_config.sh.bats
Labels: ready :rocket:

#803 KOGITO-3756 Added Kafka&MongoDB BDD test
  test/features/deploy_kogito_runtime.feature
  test/features/deploy_travel_agency.feature
Labels: bdd-tests 🧪, needs review :mag:

#804 [KOGITO-4635] Allow to override the tag if exists
  .jenkins/scripts/helper.groovy
  Jenkinsfile.promote
Labels: needs review :mag:

#805 [KOGITO-4728] Build process mongodb events example
  test/scripts/examples/process-mongodb-persistence-quarkus-example.feature
  test/scripts/examples/process-mongodb-persistence-springboot-example.feature
Labels: bdd-tests 🧪, ready :rocket:

#810 [KOGITO-4742] Reuse nightly example images for BDD PR check
  Jenkinsfile
Labels: CI/CD :loop:, needs review :mag:

#807 KOGITO-3344 - Failover scenario for scaling Kafka to 0 using BDD tests
  test/features/deploy_kogito_runtime.feature
  test/framework/graphql.go
  test/framework/kafka.go
  test/steps/kafka.go
Labels: bdd-tests 🧪, needs review :mag:

#812 [KOGITO-4753] - Cannot deploy Kogito operator together with RHPAM Kog…
  RELEASE_NOTES.md
  api/v1beta1/zz_generated.openapi.go
  bundle/manifests/kogito-operator-controller-manager_v1_serviceaccount.yaml
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  go.sum
  kogito-operator.yaml
Labels: operator :cloud:, ready :rocket:

#815 [KOGITO-4775] Solve artifacts saving in PR check
  Jenkinsfile
Labels: CI/CD :loop:, needs review :mag:

#816 [KOGITO-4333] - Hardening Kogito Operator permissions
  RELEASE_NOTES.md
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/kogitobuild_controller.go
  controllers/kogitoruntime_controller.go
  controllers/kogitosupportingservice_controller.go
  kogito-operator.yaml
Labels: needs review :mag:, operator :cloud:

#813 [KOGITO-4606] - Remove the hardcoded references to the default images…
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/kogitobuild_controller_test.go
  core/infrastructure/image.go
  core/kogitobuild/image_stream.go
  core/kogitobuild/image_stream_test.go
  core/kogitobuild/manager_test.go
  kogito-operator.yaml
  test/framework/dockerfile_provider.go
  test/framework/kogitobuild.go
  test/framework/kogitoserviceutils.go
  test/framework/util.go
Labels: bdd-tests 🧪, operator :cloud:, ready :rocket:

#818 [KOGITO-4789] BDD tests: Don't fail step in case pod is in ErrImagePu…
  test/framework/kubernetes.go
Labels: bdd-tests 🧪, ready :rocket:

#819 [KOGITO-4790] BDD tests: Remove unit test from BDD PR check pipeline
  Jenkinsfile
Labels: CI/CD :loop:, ready :rocket:

#820 [KOGITO-4797] - Disable Dev mode in logging by default
  main.go
Labels: ready :rocket:

#814 [KOGITO-4769] BDD tests: Create DMN example test
  test/features/deploy_kogito_runtime.feature
  test/scripts/examples/dmn-quarkus-example.feature
  test/scripts/examples/dmn-springboot-example.feature
Labels: bdd-tests 🧪, needs review :mag:

#821 [KOGITO-4798] Extracted Makefile test commands
  Makefile
  test/Makefile
Labels: bdd-tests 🧪, ready :rocket:

#817 [KOGITO-3105] - Missing status for failures for KogitoRuntime CRs
  RELEASE_NOTES.md
  api/kogitoservices_types.go
  controllers/kogitoruntime_controller_test.go
  core/infrastructure/image.go
  core/kogitoservice/deployer_resources.go
  core/kogitoservice/errors.go
Labels: operator :cloud:, ready :rocket:

#823 [KOGITO-4826] Service ClusterIPs triggers reconciliation
  RELEASE_NOTES.md
  core/framework/comparator.go
  core/framework/comparator_test.go
  core/kogitoservice/deployer_resources.go
Labels: operator :cloud:, ready :rocket:

#825 [1.5.x][KOGITO-4826] Service ClusterIPs triggers reconciliation
  RELEASE_NOTES.md
  core/framework/comparator.go
  core/framework/comparator_test.go
  core/kogitoservice/deployer_resources.go
Labels: cherry-pick :cherries:, operator :cloud:, ready :rocket:
