Repository kiegroup/kogito-operator, pull requests merged in 2021-02, with the labels that each got.

#741 [1.2.x][KOGITO-4245][cherry-pick] - Remove status dependency to get secret credentials (#…
  .github/workflows/Kogito-Operator-PR-Check.yaml
  RELEASE_NOTES.md
  api/kafka/v1beta1/zz_generated.openapi.go
  api/v1beta1/zz_generated.openapi.go
  controllers/infinispan.go
  hack/addheaders.sh
  hack/ci/install-kind.sh
  hack/ci/install-operator-sdk.sh
  hack/ci/start-kind.sh
  hack/go-lint.sh
  hack/openapi.sh
  pkg/infrastructure/infinispan.go
Labels: cherry-pick :cherries:, needs review :mag:, operator :cloud:

#742 [KOGITO-4332] Fixing role.yaml generation
  Makefile
  RELEASE_NOTES.md
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/kogitobuild_controller.go
  controllers/kogitoinfra_controller.go
  controllers/kogitoruntime_controller.go
  controllers/kogitosupportingservice_controller.go
  controllers/mongodb.go
  go.mod
  go.sum
  kogito-operator.yaml
  main.go
  pkg/client/client.go
  pkg/client/client_builder.go
  pkg/client/client_builder_test.go
  test/framework/kubernetes.go
  test/framework/operator.go
Labels: bdd-tests 🧪, needs review :mag:, operator :cloud:

#745 [1.2.x][KOGITO-4332] Fixing role.yaml generation
  Makefile
  RELEASE_NOTES.md
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  cmd/kogito/command/deploy/delete_service_test.go
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/project/delete_project_test.go
  cmd/kogito/command/project/new_project_test.go
  cmd/kogito/command/remove/kogitoinfra_test.go
  config/rbac/role.yaml
  controllers/kogitobuild_controller.go
  controllers/kogitoinfra_controller.go
  controllers/kogitoruntime_controller.go
  controllers/kogitosupportingservice_controller.go
  controllers/mongodb.go
  go.mod
  go.sum
  kogito-operator.yaml
  main.go
  pkg/client/client.go
  pkg/client/client_builder.go
  pkg/client/client_builder_test.go
  test/framework/kubernetes.go
  test/framework/operator.go
Labels: bdd-tests 🧪, cherry-pick :cherries:, cli 💻, needs review :mag:, operator :cloud:

#743 [KOGITO-2317] - Unify Kogito Quarkus and Spring Images
  RELEASE_NOTES.md
  controllers/build/build_config.go
  controllers/build/image_stream_kogito.go
  controllers/build/image_stream_kogito_test.go
  controllers/build/manager_test.go
  controllers/kogitobuild_controller.go
  controllers/kogitobuild_controller_test.go
  pkg/infrastructure/kogito_images.go
  pkg/infrastructure/services/deployer_resources.go
  test/framework/dockerfile_provider.go
  test/framework/kogitobuild.go
Labels: bdd-tests 🧪, operator :cloud:, ready :rocket:

#747 Added `kogito-operator-system` log archive
  Jenkinsfile.deploy
Labels: needs review :mag:

#749 [1.2.x] Added `kogito-operator-system` log archive (#747)
  Jenkinsfile.deploy
Labels: needs review :mag:

#744 [KOGITO-4307] Add tags params
  Jenkinsfile.deploy
Labels: needs review :mag:, on hold :hand:

#748 [KOGITO-4361] Invalid image tag for native image
  pkg/infrastructure/kogito_images.go
Labels: operator :cloud:, ready :rocket:

#746 [KOGITO-2785] - Operator nightly pipeline: add olm tests
  Jenkinsfile.deploy
  hack/ci/run-olm-tests.sh
Labels: CI/CD :loop:, ready :rocket:

#753 Fix promote file
  Jenkinsfile.promote
  hack/update_test_config.sh.bats
Labels: needs review :mag:

#754 Fix promote file
  Jenkinsfile.promote
Labels: ready :rocket:

#750 [KOGITO-3678] Add test coverage for Knative functionality
  README.md
  test/features/deploy_kogito_runtime.feature
  test/framework/http.go
  test/framework/knative.go
  test/framework/kogitoinfra.go
  test/framework/kubernetes.go
  test/steps/data.go
  test/steps/http.go
  test/steps/knative.go
  test/steps/kogitoinfra.go
  test/steps/kubernetes.go
Labels: bdd-tests 🧪, needs review :mag:

#710 [KOGITO-3034][BXMSPROD-1094] Setup Jenkins DSL scripts
  .github/workflows/jenkins-tests-PR.yml
  .jenkins/dsl/jobs.groovy
  .jenkins/dsl/test.sh
  Jenkinsfile.deploy
  Jenkinsfile.promote
  test/framework/maven.go
Labels: bdd-tests 🧪, needs review :mag:

#756 Correct DSL generation
  .github/workflows/jenkins-tests-PR.yml
  .jenkins/dsl/jobs.groovy
Labels: needs review :mag:, ready :rocket:

#733 [KOGITO-4210] Fix probe config for Quarkus deployments
  RELEASE_NOTES.md
  controllers/kogitoruntime_controller.go
  pkg/infrastructure/services/probe.go
Labels: operator :cloud:, ready :rocket:

#757 Update README.md
  README.md
Labels: needs review :mag:

#761 Use docker for OLM test in nightly pipeline
  Jenkinsfile.deploy
Labels: needs review :mag:

#765 [KOGITO-2947] - Upgrade Operator manifests to the new bundle format
  Makefile
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
  hack/ci/operator-ensure-manifests.sh
Labels: CI/CD :loop:, ready :rocket:

#766 [1.3.x] [KOGITO-2947] - Upgrade Operator manifests to the new bundle format
  Makefile
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
  hack/ci/operator-ensure-manifests.sh
Labels: CI/CD :loop:, cherry-pick :cherries:, ready :rocket:

#764 Update version to 1.3.0-snapshot
  Makefile
  README.md
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  cmd/kogito/version/version.go
  config/manager/kustomization.yaml
  config/manifests/bases/kogito-operator.clusterserviceversion.yaml
  kogito-operator.yaml
  pkg/version/version.go
  test/.default_config
Labels: bdd-tests 🧪, cli 💻, operator :cloud:, ready :rocket:

#770 [1.3.x][KOGITO-4521] - Add `kogito-variables-events` as hard coded topic lis…
  .github/workflows/Kogito-Operator-PR-Check.yaml
  RELEASE_NOTES.md
  controllers/kogitodataindex_reconciler.go
Labels: cherry-pick :cherries:, needs review :mag:

#768 KOGITO-4517 - Update code base and documentation after proto files ge…
  examples/quarkus-jvm.Dockerfile
  examples/springboot.Dockerfile
  test/framework/dockerfile_provider.go
Labels: bdd-tests 🧪, ready :rocket:

#763 [1.3.x] KOGITO-4444 - Sanitize dashboard name
  RELEASE_NOTES.md
  pkg/infrastructure/services/dashboards.go
  pkg/infrastructure/services/dashboards_test.go
Labels: cherry-pick :cherries:, needs review :mag:, operator :cloud:, ready :rocket:

#769 [KOGITO-4521] - Add `kogito-variables-events` as hard coded topic lis…
  .github/workflows/Kogito-Operator-PR-Check.yaml
  RELEASE_NOTES.md
  core/kogitosupportingservice/dataindex_reconciler.go
Labels: operator :cloud:, ready :rocket:

#771 [KOGITO-3784] - Update CustomResourceDefinition to apiextensions.k8s.…
  Makefile
  RELEASE_NOTES.md
  bundle/manifests/app.kiegroup.org_kogitobuilds.yaml
  bundle/manifests/app.kiegroup.org_kogitoinfras.yaml
  bundle/manifests/app.kiegroup.org_kogitoruntimes.yaml
  bundle/manifests/app.kiegroup.org_kogitosupportingservices.yaml
  config/crd/bases/app.kiegroup.org_kogitobuilds.yaml
  config/crd/bases/app.kiegroup.org_kogitoinfras.yaml
  config/crd/bases/app.kiegroup.org_kogitoruntimes.yaml
  config/crd/bases/app.kiegroup.org_kogitosupportingservices.yaml
  kogito-operator.yaml
Labels: ready :rocket:

#767 KOGITO-4477 - Operator sees the Infinispan as not ready after it is r…
  RELEASE_NOTES.md
  core/kogitoinfra/infinispan_reconciler.go
  core/kogitoinfra/infinispan_reconciler_test.go
Labels: needs review :mag:, operator :cloud:, ready :rocket:

#772 [KOGITO-4529] - Throwing nil pointer dereference for Knative broker K…
  RELEASE_NOTES.md
  core/kogitoinfra/knative_reconciler.go
  core/kogitoservice/deployer_resources.go
  core/kogitoservice/deployer_resources_test.go
  core/test/kogitoinfra.go
Labels: operator :cloud:, ready :rocket:
