Repository kiegroup/kogito-operator, pull requests merged in 2021-01, with the labels that each got.

#702 [KOGITO-4074] Extract update-test-config into a script
  Jenkinsfile.deploy
  Jenkinsfile.promote
  Makefile
  hack/bump-version.sh
  hack/bump-version.sh.bats
  hack/ci/load-operator-image.sh
  hack/ci/operator-ensure-manifests.sh
  hack/ci/operator-olm-test.sh
  hack/env.sh
  hack/export-version.sh
  hack/update_test_config.sh
  hack/update_test_config.sh.bats
Labels: needs review :mag:

#706 [KOGITO-4004] Encapsulate BDD tests stages into a lockable resource
  Jenkinsfile
  Jenkinsfile.deploy
  hack/go-lint.sh
Labels: CI/CD :loop:, needs review :mag:

#708 [KOGITO-4111] Use docker in deploy/promote pipelines
  Jenkinsfile.deploy
  Jenkinsfile.promote
Labels: CI/CD :loop:, needs review :mag:

#704 KOGITO-4082 - remove kogito-application.proto reference
  pkg/framework/comparator_test.go
Labels: needs review :mag:, operator :cloud:

#711 [KOGITO-4121] Disable native options for BDD tests
  Jenkinsfile
Labels: CI/CD :loop:, needs review :mag:

#709 [KOGITO-4112] Improve steps to test Kogito operator on OpenShift usin…
  Makefile
  README.md
  hack/update-bundle.sh
Labels: needs review :mag:

#713 [1.1.x][KOGITO-4110] - Single namespaced operator reacts on CRs created in d…
  cmd/manager/main.go
  deploy/operator.yaml
  kogito-operator.yaml
Labels: cherry-pick :cherries:, cli 💻, ready :rocket:

#714 [KOGITO-4121] Switch PR checks to podman
  Jenkinsfile
Labels: CI/CD :loop:, needs review :mag:

#712 [KOGITO-4110] - Single namespaced operator reacts on CRs created in d…
  RELEASE_NOTES.md
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/kogito-operator.clusterserviceversion.yaml
  kogito-operator.yaml
  main.go
Labels: ready :rocket:

#700 [KOGITO-3777] Separate Quarkus/Spring Boot env/properties in KogitoInfra status
  api/v1beta1/kogitoinfra_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  bundle/manifests/app.kiegroup.org_kogitoinfras.yaml
  config/crd/bases/app.kiegroup.org_kogitoinfras.yaml
  controllers/infinispan.go
  controllers/kafka.go
  controllers/kogitoinfra_controller_test.go
  controllers/kogitoinfra_manage_status.go
  controllers/mongodb.go
  go.sum
  kogito-operator.yaml
  pkg/infrastructure/services/deployer_resources.go
  pkg/infrastructure/services/deployer_test.go
  pkg/infrastructure/services/messaging_kafka.go
  pkg/infrastructure/services/messaging_kafka_test.go
  pkg/test/kogitoinfra.go
Labels: operator :cloud:, ready :rocket:

#715 [KOGITO-4109] Implement OLM based approach for running tests
  Makefile
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/config/config.go
  test/framework/operator.go
  test/main_test.go
  test/steps/operator.go
Labels: bdd-tests 🧪, ready :rocket:

#716 [1.1.x][KOGITO-4004][KOGITO-4068][cherry-pick] BDD tests stages in lockable resource
  Jenkinsfile
  Jenkinsfile.deploy
  hack/go-lint.sh
Labels: CI/CD :loop:, bdd-tests 🧪, cherry-pick :cherries:, needs review :mag:

#717 [KOGITO-4159] updated BDD tests lock string
  Jenkinsfile
  Jenkinsfile.deploy
Labels: CI/CD :loop:, needs review :mag:

#719 [1.1.x][KOGITO-4159][cherry-pick] Updated BDD tests lock string (#717)
  Jenkinsfile
  Jenkinsfile.deploy
Labels: CI/CD :loop:, bdd-tests 🧪, cherry-pick :cherries:, needs review :mag:

#721 [1.1.x] [KOGITO-4173] Appy workaround for Keycloak tests
  RELEASE_NOTES.md
  test/features/keycloak.feature
Labels: bdd-tests 🧪, cherry-pick :cherries:, needs review :mag:

#720 [KOGITO-4173] Appy workaround for Keycloak tests
  RELEASE_NOTES.md
  test/features/keycloak.feature
Labels: bdd-tests 🧪, needs review :mag:

#722 [1.1.x][KOGITO-4159] Fix to get the OPENSHIFT_API credentials in lock
  Jenkinsfile.deploy
Labels: CI/CD :loop:, bdd-tests 🧪, cherry-pick :cherries:, ready :rocket:

#723 [KOGITO-4159] Fix to get the OPENSHIFT_API credentials in lock
  Jenkinsfile.deploy
Labels: CI/CD :loop:, bdd-tests 🧪, ready :rocket:

#725 Update GUIDE_TO_KOGITO_DEVS.md
  docs/GUIDE_TO_KOGITO_DEVS.md
Labels: needs review :mag:

#718 [KOGITO-4133] - API rule violation when running openapi-gen
  RELEASE_NOTES.md
  api/v1beta1/kogitoinfra_types.go
  api/v1beta1/zz_generated.deepcopy.go
  controllers/infinispan.go
  controllers/kogitoinfra_controller_test.go
  pkg/infrastructure/services/deployer_resources.go
  pkg/infrastructure/services/deployer_resources_test.go
  pkg/test/kogitoinfra.go
Labels: operator :cloud:, ready :rocket:

#726 [KOGITO-4180] Setup different lock for BDD
  Jenkinsfile.deploy
Labels: CI/CD :loop:, bdd-tests 🧪, needs review :mag:

#729 Small change in the release notes section
  Jenkinsfile.promote
Labels: needs review :mag:

#730 [KOGITO-4208] - BDD tests: namespace does not appear anymore into the…
  test/framework/logger.go
Labels: bdd-tests 🧪, ready :rocket:

#728 [KOGITO-4188] [KOGITO-4192] Update Infinispan to 2.0.6
  RELEASE_NOTES.md
  controllers/infinispan.go
  controllers/kogitoinfra_controller.go
  go.mod
  go.sum
  hack/install-manifest.sh
  pkg/infrastructure/infinispan.go
Labels: operator :cloud:, ready :rocket:

#734 Correct promote Jenkinsfile
  Jenkinsfile.promote
Labels: ready :rocket:

#732 [KOGITO-4241] Setup godog 0.11
  cmd/kogito/command/deploy/delete_service_test.go
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/project/delete_project_test.go
  cmd/kogito/command/project/new_project_test.go
  cmd/kogito/command/remove/kogitoinfra_test.go
  go.mod
  go.sum
  test/config/config.go
  test/main_test.go
Labels: bdd-tests 🧪, cli 💻, needs review :mag:

#735 [1.2.x] Set next snapshot
  Makefile
  README.md
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  cmd/kogito/version/version.go
  config/manager/kustomization.yaml
  config/manifests/bases/kogito-operator.clusterserviceversion.yaml
  kogito-operator.yaml
  pkg/version/version.go
  test/.default_config
Labels: bdd-tests 🧪, cli 💻, operator :cloud:, ready :rocket:

#738 [KOGITO-4245] - Remove status dependency to get secret credentials
  .github/workflows/Kogito-Operator-PR-Check.yaml
  RELEASE_NOTES.md
  api/kafka/v1beta1/zz_generated.openapi.go
  api/v1beta1/zz_generated.openapi.go
  controllers/infinispan.go
  hack/addheaders.sh
  hack/ci/install-kind.sh
  hack/ci/install-operator-sdk.sh
  hack/ci/start-kind.sh
  hack/go-lint.sh
  hack/openapi.sh
  pkg/infrastructure/infinispan.go
Labels: on hold :hand:, operator :cloud:, ready :rocket:
