Repository kiegroup/kogito-operator, pull requests merged in 2021-12, with the labels that each got.

#1055 [KOGITO-6125] Default Builder broken
  README.md
Labels: ready :rocket:

#1084 [1.11.x] BAPL-1990 conscious language
  core/kogitoinfra/infinispan_reconciler.go
  core/kogitoinfra/mongodb_reconciler.go
  docs/GUIDE_FOR_KOGITO_DEVS.md
  examples/data-index.yaml
  examples/jobs-service-infinispan.yaml
  examples/kogitoinfra-infinispan.yaml
  examples/kubernetes/travel-agency/data-index.yaml
  examples/process-quarkus-example-persistence-nobuild.yaml
  examples/process-quarkus-example-persistence.yaml
  examples/travelapp-kogito-travel-agency.yaml
  examples/travelapp-kogito-visas.yaml
  examples/trusty.yaml
Labels: ready :rocket:, operator :cloud:

#1082 BAPL-1990 conscious language
  core/kogitoinfra/infinispan_reconciler.go
  core/kogitoinfra/mongodb_reconciler.go
  docs/GUIDE_FOR_KOGITO_DEVS.md
  examples/app/data-index.yaml
  examples/app/jobs-service-infinispan.yaml
  examples/app/kogitoinfra-infinispan.yaml
  examples/app/kubernetes/travel-agency/data-index.yaml
  examples/app/process-quarkus-example-persistence-nobuild.yaml
  examples/app/process-quarkus-example-persistence.yaml
  examples/app/travelapp-kogito-travel-agency.yaml
  examples/app/travelapp-kogito-visas.yaml
  examples/app/trusty.yaml
Labels: ready :rocket:, operator :cloud:

#1081 [KOGITO-6293] Update metric endpoint in kogito-operator
  RELEASE_NOTES.md
  apis/monitoring.go
  cmd/kogito/command/flag/monitoring_flag.go
  core/kogitoservice/prometheus.go
  core/kogitoservice/prometheus_test.go
  go.mod
  go.sum
Labels: cli 💻, operator :cloud:

#1085 [1.14.x] updated go.mod
  go.mod
  go.sum
  go.tools.mod
  go.tools.sum
Labels: needs review :mag:

#1091 Update RELEASE_NOTES.md
  RELEASE_NOTES.md
Labels: ready :rocket:

#1092 Update RELEASE_NOTES.md
  RELEASE_NOTES.md
Labels: ready :rocket:

#1094 [1.11.x] Ignore CLI build
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.profiling
Labels: needs review :mag:

#1093 [KOGITO-6414] Operator fails reconciliation when specific KafkaTopic …
  RELEASE_NOTES.md
  core/infrastructure/kafka/v1beta2/kafkatopic_types.go
  core/infrastructure/kafka/v1beta2/zz_generated.deepcopy.go
  go.tools.mod
  go.tools.sum
Labels: ready :rocket:, operator :cloud:, needs cherry-pick :cherries:

#1095 [1.15.x] [KOGITO-6414] Operator fails reconciliation when specific KafkaTopic …
  RELEASE_NOTES.md
  core/infrastructure/kafka/v1beta2/kafkatopic_types.go
  core/infrastructure/kafka/v1beta2/zz_generated.deepcopy.go
  go.tools.mod
  go.tools.sum
Labels: ready :rocket:, cherry-pick :cherries:, operator :cloud:

#1097 BXMSPROD-1577 Improved result message for nightlies
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/Jenkinsfile.promote
Labels: ready :rocket:

#1096 KOGITO-6362 Update Maven calls to be more reliable
  go.mod
  go.sum
  hack/go-build-cli.sh
  test/pkg/framework/maven.go
Labels: needs review :mag:, bdd-tests 🧪

#1099 [1.15.x] BXMSPROD-1577 Improved result message for nightlies (#1097)
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/Jenkinsfile.promote
Labels: needs review :mag:, cherry-pick :cherries:

#1100 [1.11.x] BXMSPROD-1577 Improved result message for nightlies (#1097)
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/Jenkinsfile.promote
Labels: needs review :mag:, cherry-pick :cherries:

#1098 [1.15.x] KOGITO-6362 Update Maven calls to be more reliable
  go.mod
  go.sum
  hack/go-build-cli.sh
  test/pkg/framework/maven.go
Labels: needs review :mag:, cherry-pick :cherries:, bdd-tests 🧪

#1101 Send test error logs to Zulip
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.profiling
Labels: needs review :mag:
