Repository kiegroup/kogito-operator, pull requests merged in 2021-08, with the labels that each got.

#960 Correct OLM tests link
  hack/ci/run-olm-tests.sh
Labels: ready :rocket:

#962 [KOGITO-5632] - [1.10.x] - 'javax.net.ssl.trustStore' error with disa…
  core/kogitoinfra/infinispan_reconciler.go
  core/kogitoinfra/infinispan_reconciler_test.go
  go.mod
Labels: operator :cloud:, ready :rocket:

#965 [1.10.x] Setup QE production cluster for tests
  .jenkins/dsl/jobs.groovy
  .jenkins/scripts/helper.groovy
  Jenkinsfile.deploy
  Jenkinsfile.profiling
Labels: needs review :mag:

#966 [KOGITO-5673] Setup BDD test for runtime with only events
  Makefile
  core/infrastructure/kafka.go
  go.sum
  test/features/deploy_kogito_runtime.feature
  test/pkg/framework/kafka.go
  test/pkg/steps/kafka.go
Labels: needs review :mag:, bdd-tests 🧪, operator :cloud:

#969 Fix build problem with addlicense library
  go.tools.mod
  go.tools.sum
  hack/addheaders.sh
Labels: needs review :mag:

#970 [KOGITO-5694] BDD tests: Increase failure threshold for startup probe
  test/pkg/framework/kogitoruntime.go
  test/pkg/framework/kogitoserviceutils.go
Labels: needs review :mag:, bdd-tests 🧪

#968 KOGITO-5685 RHPAM BDD tests with events
  api/kogitoinfra_types.go
  api/v1beta1/kogitoinfra_types.go
  test/pkg/framework/kogitoinfra.go
  test/pkg/framework/mappers/cr_to_cli.go
  test/pkg/steps/kogitoinfra.go
  test/pkg/steps/mappers/create_kogito_infra.go
Labels: needs review :mag:, bdd-tests 🧪, operator :cloud:

#972 Fix build problem with addlicense library (#969)
  go.tools.mod
  go.tools.sum
  hack/addheaders.sh
Labels: needs review :mag:, cherry-pick :cherries:

#950 [KOGITO-4700] BDD tests for Data Index Service with PostgreSQL persis…
  core/kogitosupportingservice/dataindex_reconciler.go
  test/features/deploy_kogito_runtime.feature
  test/features/install_dataindex.feature
  test/pkg/steps/kogitodataindex.go
Labels: ready :rocket:, bdd-tests 🧪, operator :cloud:

#975 [KOGITO-5688] Correct sanitize dashboard names
  core/kogitoservice/dashboards.go
Labels: ready :rocket:, operator :cloud:

#978 KOGITO-5707 Disable mgmt/task keycloak tests
  test/features/keycloak.feature
Labels: ready :rocket:, bdd-tests 🧪

#979 [1.10.x] KOGITO-5707 BDD: Disable mgmt/task keycloak tests
  test/features/keycloak.feature
Labels: ready :rocket:, cherry-pick :cherries:, bdd-tests 🧪

#957 [KOGITO-5612] BDD tests: Migrate performance tests to Hyperfoil
  go.mod
  go.sum
  hack/run-tests.sh
  hack/run-tests.sh.bats
  meta/meta.go
  test/Makefile
  test/features/kogito_service_performance.feature
  test/pkg/config/config.go
  test/pkg/framework/http.go
  test/pkg/installers/hyperfoil_installer.go
  test/pkg/steps/data.go
  test/pkg/steps/hyperfoil.go
Labels: ready :rocket:, bdd-tests 🧪

#976 KOGITO-5636 Native build image with another image
  .jenkins/dsl/jobs.groovy
  .jenkins/scripts/helper.groovy
  Jenkinsfile.deploy
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/Makefile
  test/features/deploy_kogito_build.feature
  test/pkg/config/config.go
  test/pkg/framework/maven.go
  test/pkg/steps/kogitobuild.go
Labels: ready :rocket:, bdd-tests 🧪

#982 Update Jenkins deploy jobs
  Jenkinsfile.deploy
  Jenkinsfile.examples-images.deploy
Labels: ready :rocket:

#985 BDD: Removed usage of Maven mirror
  .jenkins/scripts/helper.groovy
Labels: needs review :mag:

#988 [KOGITO-3793] Review OLM UI spec descriptors
  RELEASE_NOTES.md
  api/v1beta1/artifact.go
  api/v1beta1/gitsource.go
  api/v1beta1/kogitobuild_types.go
  api/v1beta1/kogitoinfra_types.go
  api/v1beta1/kogitoruntime_types.go
  api/v1beta1/kogitoservices.go
  api/v1beta1/kogitosupportingservice_types.go
  api/v1beta1/probe.go
  api/v1beta1/zz_generated.openapi.go
  bundle/manifests/app.kiegroup.org_kogitobuilds.yaml
  bundle/manifests/app.kiegroup.org_kogitoinfras.yaml
  bundle/manifests/app.kiegroup.org_kogitoruntimes.yaml
  bundle/manifests/app.kiegroup.org_kogitosupportingservices.yaml
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  config/crd/bases/app.kiegroup.org_kogitobuilds.yaml
  config/crd/bases/app.kiegroup.org_kogitoinfras.yaml
  config/crd/bases/app.kiegroup.org_kogitoruntimes.yaml
  config/crd/bases/app.kiegroup.org_kogitosupportingservices.yaml
  config/manifests/bases/kogito-operator.clusterserviceversion.yaml
  kogito-operator.yaml
  profiling/kogito-operator-profiling.yaml
Labels: needs review :mag:, operator :cloud:

#946 KOGITO-4113 Move all jenkins files to .ci/jenkins
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/Jenkinsfile.promote
  .ci/jenkins/dsl/Jenkinsfile.seed
  .ci/jenkins/dsl/jobs.groovy
  .ci/jenkins/dsl/test.sh
  .ci/jenkins/scripts/container.groovy
  .ci/jenkins/scripts/helper.groovy
  .ci/jenkins/scripts/openshift.groovy
  .ci/jenkins/scripts/properties.groovy
  .github/bot-files/reviewers.yml
  .github/workflows/jenkins-tests-PR.yml
Labels: needs review :mag:

#991 Upgrade Kogito Operator tested integrations
  README.md
Labels: needs review :mag:
