Repository kiegroup/kogito-operator, pull requests merged in 2021-04, with the labels that each got.

#829 Updated reviewers bot file
  .github/bot-files/reviewers.yml
Labels: ready :rocket:

#831 [1.5.x] Correction on deploy pipeline
  Jenkinsfile.deploy
Labels: ready :rocket:

#828 [1.5.x] Set 1.5.0-snapshot version
  Makefile
  README.md
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  cmd/kogito/version/version.go
  config/manager/kustomization.yaml
  config/manifests/bases/kogito-operator.clusterserviceversion.yaml
  kogito-operator.yaml
  test/.default_config
  version/version.go
Labels: bdd-tests 🧪, cli 💻, ready :rocket:

#827 [KOGITO-4837] Allow to update snapshot version
  .jenkins/dsl/jobs.groovy
  .jenkins/scripts/helper.groovy
  Jenkinsfile.deploy
Labels: ready :rocket:

#830 [KOGITO-4849] BDD tests: Add support for deploying files and folders …
  test/features/deploy_kogito_build.feature
  test/features/deploy_source_files.feature
  test/steps/deploy_files.go
  test/steps/kogitobuild.go
Labels: bdd-tests 🧪, ready :rocket:

#834 [1.5.x][KOGITO-4849] BDD tests: Add support for deploying files and folders …
  test/features/deploy_kogito_build.feature
  test/features/deploy_source_files.feature
  test/steps/deploy_files.go
  test/steps/kogitobuild.go
Labels: bdd-tests 🧪, cherry-pick :cherries:, ready :rocket:

#835 [KOGITO-4877] Implement YAML based approach for Infinispan installation
  examples/process-quarkus-example-persistence-nobuild.yaml
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/Makefile
  test/config/config.go
  test/framework/infinispan.go
  test/framework/kubernetes.go
  test/installers/infinispan_installer.go
  test/steps/infinispan.go
Labels: bdd-tests 🧪, needs review :mag:

#833 [KOGITO-4729] - Upgrade from Operator 1.3.0 to 1.4.0 fails with refer…
  RELEASE_NOTES.md
  api/v1beta1/kogitoinfra_types.go
  controllers/kogitoinfra_controller.go
  controllers/kogitoinfra_controller_test.go
  core/infrastructure/kafka.go
  core/infrastructure/kafka/v1beta2/doc.go
  core/infrastructure/kafka/v1beta2/kafka_types.go
  core/infrastructure/kafka/v1beta2/kafkatopic_types.go
  core/infrastructure/kafka/v1beta2/register.go
  core/infrastructure/kafka/v1beta2/zz_generated.deepcopy.go
  core/infrastructure/kafka_test.go
  core/kogitoinfra/errors.go
  core/kogitoinfra/kafka_reconciler.go
  core/kogitoinfra/kafka_reconciler_test.go
  core/kogitoinfra/reconciler.go
  core/kogitoinfra/status_test.go
  core/kogitoservice/deployer_test.go
  core/kogitoservice/messaging_kafka_test.go
  core/test/fake_client.go
  core/test/kafka.go
  core/test/kogitoinfra.go
  examples/data-index-mongodb.yaml
  examples/data-index.yaml
  examples/explainability.yaml
  examples/kogitoinfra-kafka.yaml
  examples/kubernetes/travel-agency/data-index.yaml
  examples/process-quarkus-example-persistence.yaml
  examples/travelapp-kogito-travel-agency.yaml
  examples/travelapp-kogito-visas.yaml
  examples/trusty.yaml
  meta/meta.go
  test/framework/kafka.go
  test/installers/kafka_installer.go
  test/steps/kafka.go
Labels: bdd-tests 🧪, operator :cloud:, ready :rocket:

#838 [KOGITO-4905] Fix COPY line in springboot.Dockerfile
  RELEASE_NOTES.md
  examples/springboot.Dockerfile
Labels: ready :rocket:

#837 [KOGITO-4894] - Remove `image` default value in KogitoRuntime CR (pro…
  RELEASE_NOTES.md
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  config/samples/app_v1beta1_kogitobuild.yaml
  config/samples/app_v1beta1_kogitoruntime.yaml
Labels: operator :cloud:, ready :rocket:

#836 [KOGITO-4888] Update Prometheus operator GitHub link
  controllers/runtime_deployer.go
  core/framework/comparator.go
  core/kogitoservice/prometheus.go
  go.mod
  go.sum
  meta/meta.go
  test/pkg/framework/prometheus.go
Labels: bdd-tests 🧪, operator :cloud:, ready :rocket:

#822 [KOGITO-4781] Fix deployment constantly updating
  RELEASE_NOTES.md
  core/kogitoservice/probe.go
  core/kogitoservice/probe_test.go
Labels: operator :cloud:, ready :rocket:

#826 [KOGITO-4322] Add startup probes
  RELEASE_NOTES.md
  api/probe.go
  api/v1beta1/probe.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/app.kiegroup.org_kogitoruntimes.yaml
  bundle/manifests/app.kiegroup.org_kogitosupportingservices.yaml
  config/crd/bases/app.kiegroup.org_kogitoruntimes.yaml
  config/crd/bases/app.kiegroup.org_kogitosupportingservices.yaml
  core/kogitoservice/deployment.go
  core/kogitoservice/probe.go
  core/kogitoservice/probe_test.go
  kogito-operator.yaml
Labels: operator :cloud:, ready :rocket:

#842 Corrected examples images deploy job cfg
  .jenkins/dsl/jobs.groovy
  Jenkinsfile.promote
Labels: needs review :mag:

#843 [1.5.x] Corrected examples images deploy job cfg
  .jenkins/dsl/jobs.groovy
  Jenkinsfile.promote
Labels: needs review :mag:

#845 [KOGITO-4946] BDD: Allow to modify logged K8s objects
  test/pkg/steps/data.go
Labels: bdd-tests 🧪, needs review :mag:

#848 [KOGITO-4952] Support installing product operator using insecure regi…
  test/pkg/framework/openshift.go
Labels: bdd-tests 🧪, needs review :mag:

#847 [KOGITO-4154] - CLI displays usage page whenever any command fails
  cmd/kogito/command/context/root.go
Labels: cli 💻, ready :rocket:

#851 [KOGITO-4973] Correct Examples Images building archiving
  Jenkinsfile.examples-images.deploy
Labels: needs review :mag:

#849 [KOGITO-4905] Fix COPY line comment in springboot.Dockerfile
  examples/springboot.Dockerfile
Labels: ready :rocket:

#850 [1.5.x][KOGITO-4952] Support installing product operator using insecure regi…
  test/framework/openshift.go
Labels: bdd-tests 🧪, cherry-pick :cherries:, needs review :mag:

#852 [1.5.x] [KOGITO-4974] Corrected OLM tests on release branch
  Makefile
  README.md
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  cmd/kogito/version/version.go
  config/manager/kustomization.yaml
  config/manifests/bases/kogito-operator.clusterserviceversion.yaml
  hack/ci/operator-ensure-manifests.sh
  kogito-operator.yaml
  version/version.go
Labels: cli 💻, ready :rocket:

#853 [KOGITO-4975] Set back snapshot after release
  .jenkins/scripts/helper.groovy
  Jenkinsfile.promote
Labels: CI/CD :loop:, needs review :mag:

#854 [1.6.x] [KOGITO-4975] Set back snapshot after release (#853)
  .jenkins/scripts/helper.groovy
  Jenkinsfile.promote
Labels: CI/CD :loop:, cherry-pick :cherries:, needs review :mag:

#858 [1.6.x][KOGITO-4993] Operator crash when data-index is created
  RELEASE_NOTES.md
  core/kogitoservice/deployer_test.go
  core/manager/infra_manager.go
Labels: cherry-pick :cherries:, operator :cloud:, ready :rocket:

#857 [KOGITO-4993] Operator crash when data-index is created
  RELEASE_NOTES.md
  core/kogitoservice/deployer_test.go
  core/manager/infra_manager.go
Labels: needs review :mag:, operator :cloud:
