Repository kiegroup/kogito-operator, pull requests merged in 2021-09, with the labels that each got.

#996 [KOGITO-5811] - no kind is registered for the type v1beta1.KogitoInfra
  RELEASE_NOTES.md
  controllers/kogitoinfra_controller.go
  core/kogitoinfra/status.go
  core/kogitoinfra/status_test.go
Labels: needs review :mag:, operator :cloud:

#998 [KOGITO-5390] Support using images without namespace part in KogitoRu…
  api/image.go
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  core/framework/image.go
  core/framework/image_test.go
  core/infrastructure/image.go
  core/kogitobuild/image_stream.go
  kogito-operator.yaml
  profiling/kogito-operator-profiling.yaml
  test/pkg/framework/kogitobuild.go
  test/pkg/framework/kogitoserviceutils.go
  test/pkg/framework/util.go
Labels: WIP :construction_worker_man:, needs review :mag:, bdd-tests 🧪, operator :cloud:

#994 KOGITO-5781 Push reduced tag in deploy pipeline
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/dsl/jobs.groovy
  .ci/jenkins/scripts/helper.groovy
Labels: needs review :mag:

#1001 [1.11.x] KOGITO-5781 Push reduced tag in deploy pipeline (#994)
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/dsl/jobs.groovy
  .ci/jenkins/scripts/helper.groovy
Labels: needs review :mag:, cherry-pick :cherries:

#1003 KOGITO-5837 BDD: Split jvm and native runtime imgs
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/Makefile
  test/pkg/config/config.go
  test/pkg/framework/kogitobuild.go
Labels: needs review :mag:, bdd-tests 🧪

#1008 [KOGITO-5857] Correct bats test
  hack/update_test_config.sh
  hack/update_test_config.sh.bats
Labels: needs review :mag:, needs cherry-pick :cherries:

#1007 [1.11.x] [KOGITO-5857] Correct bats test
  hack/update_test_config.sh
  hack/update_test_config.sh.bats
Labels: needs review :mag:, cherry-pick :cherries:

#1010 [1.11.x] [KOGITO-5837] [KOGITO-5845] BDD: Split jvm and native runtime imgs (#1003)(#1005)
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/Makefile
  test/features/deploy_kogito_runtime.feature
  test/features/service_discovery.feature
  test/pkg/config/config.go
  test/pkg/framework/dockerfile_provider.go
  test/pkg/framework/kogitobuild.go
  test/pkg/framework/util.go
Labels: needs review :mag:, cherry-pick :cherries:, bdd-tests 🧪

#1015 [KOGITO-5692] Store objects to be logged to Data struct
  test/pkg/executor/bdd_executor.go
  test/pkg/steps/data.go
Labels: needs review :mag:, bdd-tests 🧪

#1016 [1.11.x] [KOGITO-5692] Store objects to be logged to Data struct
  test/pkg/executor/bdd_executor.go
  test/pkg/steps/data.go
Labels: ready :rocket:, bdd-tests 🧪

#1005 KOGITO-5845 Add @rhpam native scenarios
  test/features/deploy_kogito_runtime.feature
  test/features/service_discovery.feature
  test/pkg/framework/dockerfile_provider.go
  test/pkg/framework/kogitobuild.go
  test/pkg/framework/util.go
Labels: needs review :mag:, bdd-tests 🧪

#999 [KOGITO-5740] Unnecessary reconciliations triggered for Service
  RELEASE_NOTES.md
  core/framework/comparator.go
  core/framework/comparator_test.go
  core/kogitoservice/deployer_resources.go
  core/kogitoservice/deployer_resources_test.go
Labels: ready :rocket:, operator :cloud:

#1017 [KOGITO-5888] Remove namespace option from BDD tests
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/scripts/helper.groovy
  go.sum
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/Makefile
  test/pkg/config/config.go
  test/pkg/framework/kogitoserviceutils.go
  test/pkg/framework/util.go
  test/pkg/steps/image_registry.go
Labels: ready :rocket:, bdd-tests 🧪

#1018 [1.11.x][KOGITO-5740] Unnecessary reconciliations triggered for Service (#999)
  RELEASE_NOTES.md
  core/framework/comparator.go
  core/framework/comparator_test.go
  core/kogitoservice/deployer_resources.go
  core/kogitoservice/deployer_resources_test.go
  go.sum
Labels: ready :rocket:, cherry-pick :cherries:, operator :cloud:

#986 [KOGITO-5745] BDD tests: Add Node scraper for performance tests
  .github/workflows/Kogito-Operator-PR-Check.yaml
  hack/run-tests.sh
  test/features/kogito_service_performance.feature
  test/pkg/framework/kubernetes.go
  test/pkg/installers/hyperfoil_node_scraper_installer.go
  test/pkg/steps/hyperfoil.go
Labels: needs review :mag:, bdd-tests 🧪

#987 KOGITO-5730 Restructure DSL folders
  .ci/jenkins/dsl/jobs.groovy
Labels: needs review :mag:

#1023 [1.11.x] KOGITO-5730 Restructure DSL folders (#987)
  .ci/jenkins/dsl/jobs.groovy
Labels: needs review :mag:

#1027 Specify timeout for cluster resource delete
  go.tools.mod
  go.tools.sum
  hack/env.sh
Labels: ready :rocket:

#1026 [KOGITO-5945] BDD tests: Add option to run tests using released operator
  test/pkg/config/config.go
  test/pkg/installers/kogito_installer.go
Labels: ready :rocket:, bdd-tests 🧪

#1025 BDD tests: Allow configuring Hyperfoil controller image version
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/Makefile
  test/pkg/config/config.go
  test/pkg/steps/hyperfoil.go
Labels: ready :rocket:, bdd-tests 🧪

#1031 Adjust go.sum and go.mod after operator-sdk migration
  go.mod
  go.sum
Labels: ready :rocket:

#1030 [KOGITO-4791] Add metrics related files back in the operator bundle
  RELEASE_NOTES.md
  hack/create-olm-manifests.sh
Labels: ready :rocket:

#1034 [KOGITO-5958] BDD tests: Adjust the memory limit for operator profili…
  config/profiling/kustomization.yaml
  config/profiling/patches/manager_profiling_limits.yaml
  profiling/kogito-operator-profiling.yaml
Labels: ready :rocket:

#1035 BDD tests: Add disable_clean_cluster flag into Makefile
  test/Makefile
  test/go.sum
Labels: needs review :mag:, bdd-tests 🧪

#1024 BXMSPROD-1478 Setup Jenkins pipelines with new golang
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/Jenkinsfile.promote
  .ci/jenkins/scripts/helper.groovy
  Makefile
  hack/ci/install-operator-sdk.sh
  hack/ci/uninstall-operator-sdk.sh
  test/go.mod
  test/go.sum
  test/pkg/steps/data.go
Labels: needs review :mag:, bdd-tests 🧪

#1029 [1.11.x] BXMSPROD-1478 Setup Jenkins pipelines with new golang
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/Jenkinsfile.promote
  .ci/jenkins/scripts/helper.groovy
  Makefile
  hack/ci/install-operator-sdk.sh
  hack/ci/uninstall-operator-sdk.sh
  test/pkg/steps/data.go
Labels: needs review :mag:, bdd-tests 🧪

#1037 [KOGITO-5977] - Pod is never created when deploying source files
  RELEASE_NOTES.md
  core/infrastructure/reconciliation_error.go
  core/kogitoservice/deployer.go
  core/kogitoservice/deployment_reconciler.go
  test/go.mod
  test/go.sum
Labels: needs review :mag:, bdd-tests 🧪, operator :cloud:
