Repository kiegroup/kogito-operator, pull requests merged in 2021-10, with the labels that each got.

#1040 BDD tests: Update golang.org/x/sys
  test/go.mod
  test/go.sum
Labels: needs review :mag:, bdd-tests 🧪

#1038 [1.11.x] [KOGITO-5977] Pod is never created when deploying source…
  RELEASE_NOTES.md
  core/infrastructure/reconciliation_error.go
  core/kogitoservice/deployer.go
Labels: needs review :mag:, operator :cloud:

#1039 [KOGITO-6032] BDD tests: Rename disable_clean_cluster parameter to en…
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/scripts/helper.groovy
  hack/run-tests.sh
  test/Makefile
  test/go.mod
  test/go.sum
Labels: needs review :mag:, bdd-tests 🧪

#1042 BDD tests: Add support for Infinispan storage class
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/Makefile
  test/pkg/config/config.go
  test/pkg/framework/infinispan.go
Labels: needs review :mag:, bdd-tests 🧪

#997 [KOGITO-5796] BDD tests: Adjust Knative test to use KogitoSource for …
  README.md
  test/features/deploy_kogito_runtime.feature
  test/pkg/installers/knative-eventing-kogito-installer.go
  test/pkg/installers/knative_installer.go
  test/pkg/steps/data.go
  test/pkg/steps/knative-eventing-kogito.go
Labels: ready :rocket:, bdd-tests 🧪
