Repository kiegroup/kogito-operator, pull requests merged in 2021-05, with the labels that each got.

#861 [1.6.x] Fix explainability dto
  test/features/keycloak.feature
Labels: bdd-tests 🧪, cherry-pick :cherries:, needs review :mag:

#862 Fix explainability dto
  test/features/keycloak.feature
Labels: bdd-tests 🧪, needs review :mag:

#841 [KOGITO-4898] Set probe defaults based on YAML action values
  RELEASE_NOTES.md
  controllers/kogitoruntime_controller.go
  core/kogitoservice/deployer.go
  core/kogitoservice/deployment.go
  core/kogitoservice/deployment_test.go
  core/kogitoservice/probe.go
  core/kogitoservice/probe_test.go
  core/kogitosupportingservice/dataindex_reconciler.go
  core/kogitosupportingservice/explainability_reconciler.go
  core/kogitosupportingservice/jobsservice_reconciler.go
  core/kogitosupportingservice/trustyai_reconciler.go
Labels: operator :cloud:

#865 [KOGITO-5063] BDD tests: Support using builder images from insecure r…
  test/pkg/framework/openshift.go
Labels: bdd-tests 🧪, needs cherry-pick :cherries:, needs review :mag:

#866 [1.5.x][KOGITO-5063] BDD tests: Support using builder images from insecure r…
  test/framework/openshift.go
Labels: bdd-tests 🧪, cherry-pick :cherries:, needs review :mag:

#874 [KOGITO-4453] Fix getAppPropsFromConfigMap
  RELEASE_NOTES.md
  core/kogitoservice/configmap.go
  core/kogitoservice/configmap_test.go
Labels: operator :cloud:, ready :rocket:

#876 [1.5.x] [KOGITO-4453] Fix getAppPropsFromConfigMap
  RELEASE_NOTES.md
  core/kogitoservice/configmap.go
  core/kogitoservice/configmap_test.go
Labels: cherry-pick :cherries:, needs review :mag:, operator :cloud:

#867 [KOGITO-5104] - [1.5.x] - RHPAM Kogito operator creates wrong default image tags
  Makefile
  RELEASE_NOTES.md
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
  controllers/kogitobuild_controller.go
  controllers/kogitobuild_controller_test.go
  controllers/kogitoinfra_controller.go
  controllers/kogitoruntime_controller.go
  controllers/kogitoruntime_finalizer.go
  controllers/kogitosupportingservice_controller.go
  controllers/kogitosupportingservice_finalizer.go
  core/infrastructure/image.go
  core/infrastructure/image_test.go
  core/kogitobuild/build_config.go
  core/kogitobuild/image_stream.go
  core/kogitobuild/image_stream_test.go
  core/kogitobuild/manager_test.go
  core/kogitoservice/deployer_resources_test.go
  core/kogitoservice/deployment_test.go
  core/operator/context.go
  hack/ci/ensure-image.sh
  hack/ci/olm-pretest.sh
  hack/ci/operator-ensure-manifests.sh
  hack/ci/run-olm-tests.sh
  test/framework/kogitoserviceutils.go
  test/framework/util.go
Labels: bdd-tests 🧪, needs review :mag:, operator :cloud:

#868 [KOGITO-5104] - RHPAM Kogito operator creates wrong default image tags
  RELEASE_NOTES.md
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  config/manifests/bases/kogito-operator.clusterserviceversion.yaml
  controllers/kogitobuild_controller.go
  controllers/kogitobuild_controller_test.go
  controllers/kogitoinfra_controller.go
  controllers/kogitoruntime_controller.go
  controllers/kogitoruntime_finalizer.go
  controllers/kogitosupportingservice_controller.go
  controllers/kogitosupportingservice_finalizer.go
  core/infrastructure/image.go
  core/infrastructure/image_test.go
  core/kogitobuild/build_config.go
  core/kogitobuild/image_stream.go
  core/kogitobuild/image_stream_test.go
  core/kogitobuild/manager_test.go
  core/kogitoservice/deployer_resources_test.go
  core/kogitoservice/deployment_test.go
  core/operator/context.go
  hack/ci/ensure-image.sh
  hack/ci/olm-pretest.sh
  hack/ci/operator-ensure-manifests.sh
  hack/ci/run-olm-tests.sh
  test/pkg/framework/kogitoserviceutils.go
  test/pkg/framework/util.go
Labels: bdd-tests 🧪, operator :cloud:, ready :rocket:

#878 BDD tests: Fix nil pointer error for KogitoInfra check
  test/pkg/framework/kogitoinfra.go
Labels: bdd-tests 🧪, needs review :mag:

#880 [1.7.x] Correct promote examples images
  Jenkinsfile.examples-images.promote
Labels: needs review :mag:

#872 [1.7.x] Update project version to 1.7.0-snapshot
  Makefile
  README.md
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  cmd/kogito/version/version.go
  config/manager/kustomization.yaml
  config/manifests/bases/kogito-operator.clusterserviceversion.yaml
  hack/ci/ensure-image.sh
  hack/ci/olm-pretest.sh
  hack/ci/operator-ensure-manifests.sh
  hack/ci/run-olm-tests.sh
  kogito-operator.yaml
  profiling/kogito-operator-profiling.yaml
  test/.default_config
  version/version.go
Labels: bdd-tests 🧪, cli 💻, needs review :mag:

#881 Correct promote examples images
  Jenkinsfile.examples-images.promote
Labels: needs review :mag:

#879 [KOGITO-4722] - Support Job Service MongoDB distribution provisioning…
  RELEASE_NOTES.md
  core/kogitosupportingservice/jobsservice_reconciler.go
  docs/GUIDE_TO_KOGITO_DEVS.md
  examples/jobs-service-infinispan.yaml
  examples/jobs-service.yaml
Labels: needs review :mag:, operator :cloud:

#886 [1.6.x] Update certification versions
  README.md
Labels: needs review :mag:

#885 [1.7.x] Update certification versions
  README.md
Labels: needs review :mag:

#884 Update certification versions
  README.md
Labels: needs review :mag:

#882 [KOGITO-5182] BDD tests: Fix Grafana test after dashboard name change
  test/features/grafana.feature
Labels: bdd-tests 🧪, ready :rocket:

#887 [KOGITO-5083] - Kogito Runtime Image Stream Fails to Update
  RELEASE_NOTES.md
  core/infrastructure/image.go
  core/infrastructure/imagestream.go
  core/kogitoservice/deployer_resources.go
Labels: needs review :mag:, operator :cloud:

#889 [KOGITO-4487] Update to nightly branch for testing
  hack/update_test_config.sh
  hack/update_test_config.sh.bats
  test/.default_config
Labels: bdd-tests 🧪, needs review :mag:

#883 [KOGITO-4455] Enabling raw redeploy of Kogito Services on CLI
  RELEASE_NOTES.md
  cmd/kogito/command/deploy/delete_service_test.go
  cmd/kogito/command/deploy/deploy_service_test.go
  cmd/kogito/command/deploy/testdata/greetings.sw.json
  cmd/kogito/command/install/kogito_infra_test.go
  cmd/kogito/command/install/supportingservices_test.go
  cmd/kogito/command/project/delete_project_test.go
  cmd/kogito/command/project/display_project_test.go
  cmd/kogito/command/project/new_project_test.go
  cmd/kogito/command/project/use_project_test.go
  cmd/kogito/command/remove/kogitoinfra_test.go
  cmd/kogito/command/remove/supportingservices_test.go
  cmd/kogito/command/service/build_service.go
  cmd/kogito/command/service/runtime_service.go
  cmd/kogito/command/shared/install_services.go
  cmd/kogito/command/test/common.go
  cmd/kogito/core/doc.go
  cmd/kogito/core/resource_manager.go
  core/client/kubernetes/resource_writer.go
Labels: cli 💻, operator :cloud:, ready :rocket:
