Repository kiegroup/kogito-operator, pull requests merged in 2021-07, with the labels that each got.

#875 [KOGITO-5127] Guide for new Kogito operator developers
  .github/pull_request_template.md
  README.md
  RELEASE_NOTES.md
  docs/GUIDE_FOR_KOGITO_DEVS.md
  docs/GUIDE_FOR_RUNTIMES_DEVS.md
Labels: ready :rocket:

#917 [RHPAM-3681] - Add metering labels in KogitoBuild
  RELEASE_NOTES.md
  controllers/kogitobuild_controller.go
  core/kogitobuild/buid_config_test.go
  core/kogitobuild/build_config.go
  core/kogitobuild/build_context.go
  core/kogitobuild/decorator.go
  core/kogitobuild/decorator_test.go
  core/kogitobuild/image_stream.go
  core/kogitobuild/image_stream_test.go
  core/kogitobuild/manager.go
  core/kogitobuild/manager_build_binary.go
  core/kogitobuild/manager_build_source.go
  core/kogitobuild/manager_test.go
  core/kogitobuild/status.go
  core/kogitobuild/status_test.go
  internal/kogitobuild.go
Labels: needs review :mag:, operator :cloud:

#920 Changes in the installation steps
  README.md
Labels: ready :rocket:

#921 [RHPAM-3681] - [1.5.x] - Introduce BuildContext
  controllers/kogitobuild_controller.go
  core/kogitobuild/buid_config_test.go
  core/kogitobuild/build_config.go
  core/kogitobuild/build_context.go
  core/kogitobuild/decorator.go
  core/kogitobuild/decorator_test.go
  core/kogitobuild/image_stream.go
  core/kogitobuild/image_stream_test.go
  core/kogitobuild/manager.go
  core/kogitobuild/manager_build_binary.go
  core/kogitobuild/manager_build_source.go
  core/kogitobuild/manager_test.go
  core/kogitobuild/status.go
  core/kogitobuild/status_test.go
  internal/kogitobuild.go
Labels: cherry-pick :cherries:, operator :cloud:, ready :rocket:

#923 [RHPAM-3681] Fix file name typo
  core/kogitobuild/build_config_test.go
Labels: needs review :mag:, operator :cloud:

#922 [1.5.x] [RHPAM-3681] Fix file name typo
  core/kogitobuild/build_config_test.go
Labels: needs review :mag:, operator :cloud:

#896 [KOGITO-5246] Update namespace cleanup
  Jenkinsfile
  Jenkinsfile.deploy
  Jenkinsfile.profiling
  test/pkg/framework/namespace.go
  test/pkg/installers/service_installer.go
Labels: CI/CD :loop:, bdd-tests 🧪, needs review :mag:

#751 [KOGITO-4362] BDD wait for OperatorGroup creation
  test/pkg/framework/operator.go
Labels: bdd-tests 🧪, needs review :mag:

#919 Various BDD adjustments
  test/pkg/config/config.go
  test/pkg/executor/bdd_executor.go
  test/pkg/framework/http.go
  test/pkg/framework/operator.go
  test/pkg/installers/grafana_installer.go
  test/pkg/installers/infinispan_installer.go
  test/pkg/installers/kafka_installer.go
  test/pkg/installers/keycloak_installer.go
  test/pkg/installers/kogito_installer.go
  test/pkg/installers/prometheus_installer.go
  test/pkg/installers/service_installer.go
  test/pkg/steps/data.go
Labels: bdd-tests 🧪, needs review :mag:

#928 Various BDD adjustments
  test/pkg/framework/grafana.go
  test/pkg/framework/graphql.go
  test/pkg/framework/kogitoserviceutils.go
  test/pkg/framework/kubernetes.go
  test/pkg/framework/prometheus.go
Labels: bdd-tests 🧪, ready :rocket:

#930 [KOGITO-4699] BDD tests for Jobs Service with PostgreSQL persistence
  README.md
  core/kogitosupportingservice/jobsservice_reconciler.go
  test/features/install_jobs_service.feature
  test/pkg/steps/data.go
  test/pkg/steps/kogitojobsservice.go
  test/pkg/steps/mappers/create_postgresql_instance.go
  test/pkg/steps/postgresql.go
Labels: bdd-tests 🧪, needs review :mag:, operator :cloud:

#925 [KOGITO-5478] - Management console does not work on OpenShift
  RELEASE_NOTES.md
  api/v1beta1/kogitosupportingservice_types.go
  api/v1beta1/kogitosupportingservice_types_test.go
  core/manager/supportingservice_manager.go
  go.sum
  internal/kogitosupportingservice.go
Labels: bdd-tests 🧪, cli 💻, needs review :mag:, operator :cloud:

#926 [KOGITO-5478]- [1.8.x] - Management console does not work on OpenShift
  RELEASE_NOTES.md
  api/v1beta1/kogitosupportingservice_types.go
  api/v1beta1/kogitosupportingservice_types_test.go
  core/manager/supportingservice_manager.go
  internal/kogitosupportingservice.go
Labels: bdd-tests 🧪, cli 💻, operator :cloud:, ready :rocket:

#933 [KOGITO-5478] - [1.9.x] - Management console does not work on OpenShift
  RELEASE_NOTES.md
  api/v1beta1/kogitosupportingservice_types.go
  api/v1beta1/kogitosupportingservice_types_test.go
  core/manager/supportingservice_manager.go
  go.sum
  internal/kogitosupportingservice.go
Labels: operator :cloud:, ready :rocket:

#929 KOGITO-5480 Reorganized seed jobs & trigger automatically
  .jenkins/dsl/Jenkinsfile.seed
Labels: ready :rocket:

#932 [1.8.x] Setup External cluster use for BDD tests
  .jenkins/dsl/jobs.groovy
  .jenkins/scripts/helper.groovy
  Jenkinsfile.deploy
  Jenkinsfile.profiling
Labels: needs review :mag:

#934 [1.5.x] KOGITO-5480 Reorganized seed jobs & trigger automatically (#929)
  .jenkins/dsl/Jenkinsfile.seed
Labels: cherry-pick :cherries:, ready :rocket:

#936 [1.9.x] KOGITO-5480 Reorganized seed jobs & trigger automatically (#929)
  .jenkins/dsl/Jenkinsfile.seed
Labels: cherry-pick :cherries:, ready :rocket:

#935 [1.8.x] KOGITO-5480 Reorganized seed jobs & trigger automatically (#929)
  .jenkins/dsl/Jenkinsfile.seed
Labels: cherry-pick :cherries:, ready :rocket:

#939 [1.9.x] Use external cluster for tests (#932)
  .jenkins/dsl/jobs.groovy
  .jenkins/scripts/helper.groovy
  Jenkinsfile.deploy
  Jenkinsfile.profiling
Labels: ready :rocket:

#942 [1.9.x] [KOGITO-4699] BDD tests for Jobs Service with PostgreSQL persistence
  README.md
  core/kogitosupportingservice/jobsservice_reconciler.go
  test/features/install_jobs_service.feature
  test/pkg/steps/data.go
  test/pkg/steps/kogitojobsservice.go
  test/pkg/steps/mappers/create_postgresql_instance.go
  test/pkg/steps/postgresql.go
Labels: bdd-tests 🧪, cherry-pick :cherries:, needs review :mag:, operator :cloud:

#941 [KOGITO-5512] controller-gen doesn't generate CRD's
  Makefile
  RELEASE_NOTES.md
  go.sum
Labels: ready :rocket:

#947 Update OLM retrieval + version
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  config/manifests/bases/kogito-operator.clusterserviceversion.yaml
  go.sum
  hack/env.sh
Labels: ready :rocket:

#948 [1.9.x] Correct Maven repository handling
  .jenkins/scripts/helper.groovy
Labels: needs review :mag:

#945 Update of tested certification matrix
  README.md
Labels: ready :rocket:

#944 [KOGITO-5326] Setup deploy/promote notifications on demand
  .jenkins/dsl/jobs.groovy
  Jenkinsfile.deploy
  Jenkinsfile.examples-images.deploy
  Jenkinsfile.examples-images.promote
  Jenkinsfile.profiling
  Jenkinsfile.promote
Labels: needs review :mag:

#905 BXMSPROD-1265: Conscious language initiative
  .github/bot-files/comments.yml
  .github/pull_request_template.md
  .github/workflows/jenkins-tests-PR.yml
  .jenkins/dsl/test.sh
  README.md
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  cmd/kogito/command/install/supportingservices.go
  config/manifests/bases/kogito-operator.clusterserviceversion.yaml
  core/framework/image.go
  docs/GUIDE_FOR_KOGITO_DEVS.md
  examples/data-index-mongodb.yaml
  examples/data-index.yaml
  examples/explainability.yaml
  examples/kogitoinfra-kafka.yaml
  examples/kubernetes/travel-agency/data-index.yaml
  examples/process-quarkus-example-persistence.yaml
  examples/springboot.yaml
  examples/travelapp-kogito-travel-agency.yaml
  examples/travelapp-kogito-visas.yaml
  examples/trusty.yaml
  hack/run-tests.sh
  hack/update_test_config.sh
  hack/update_test_config.sh.bats
  test/.default_config
Labels: bdd-tests 🧪, cli 💻, needs review :mag:, operator :cloud:

#952 [1.9.x] Update OLM retrieval + version (#947)
  hack/env.sh
Labels: needs review :mag:, on hold :hand:

#956 [1.9.x] [KOGITO-5573] Kogito Operator Data-Index Unable to connect to Infinis…
  RELEASE_NOTES.md
  core/kogitoinfra/infinispan_reconciler.go
  core/kogitoinfra/infinispan_reconciler_test.go
  test/pkg/framework/infinispan.go
Labels: bdd-tests 🧪, cherry-pick :cherries:, needs review :mag:, operator :cloud:

#955 [KOGITO-5573] Kogito Operator Data-Index Unable to connect to Infinis…
  RELEASE_NOTES.md
  core/kogitoinfra/infinispan_reconciler.go
  core/kogitoinfra/infinispan_reconciler_test.go
  test/pkg/framework/infinispan.go
Labels: bdd-tests 🧪, operator :cloud:, ready :rocket:

#953 KOGITO-5601 : Add KogitoInfra capablities in RHPAM Kogito Operator
  api/kogitoinfra_types.go
  api/v1beta1/kogitoinfra_types.go
  api/v1beta1/kogitoinfra_types_test.go
  api/v1beta1/zz_generated.deepcopy.go
  controllers/kogitoruntime_controller_test.go
  core/kogitoinfra/infinispan_reconciler.go
  core/kogitoinfra/kafka_reconciler.go
  core/kogitoinfra/mongodb_reconciler.go
  core/kogitoinfra/status.go
  core/kogitoservice/messaging_kafka.go
  core/manager/infra_manager.go
Labels: operator :cloud:, ready :rocket:

#958 [1.9.x] Correct OLM tests
  bundle/manifests/kogito-operator.clusterserviceversion.yaml
  config/manifests/bases/kogito-operator.clusterserviceversion.yaml
  hack/ci/operator-ensure-manifests.sh
  hack/ci/run-olm-tests.sh
Labels: ready :rocket:
