Repository kiegroup/kogito-operator, pull requests merged in 2022-12, with the labels that each got.

#1330 [1.13.x][KIECLOUD-656] - Prepare RHPAM branches for 7.13.2
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manager/rhpam/kustomization.yaml
  version/rhpam/version.go
Labels: needs review :mag:

#1331 [1.13.x-blue][KIECLOUD-656] - Prepare BAMOE branches for 8.0.2
  bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml
  config/manager/bamoe/kustomization.yaml
  version/rhpam/version.go
Labels: needs review :mag:

#1333 [1.13.x-blue][KIECLOUD-656] update modules to version 8.0.2
  bamoe-image-bundle.yaml
  bamoe-image-prod.yaml
  bamoe-image.yaml
  modules/org.kie.kogito.rhpam.builder.prod/module.yaml
  modules/org.kie.kogito.rhpam.bundleinstall/module.yaml
Labels: ready :rocket:

#1306 KOGITO-8062 DSL: Refactor environments and export to config
  .ci/jenkins/dsl/jobs.groovy
Labels: WIP :construction_worker_man:

#1337 [1.32.x] Fix from release 1.32.0
  test/features/deploy_kogito_runtime.feature
  test/pkg/framework/grafana.go
Labels: needs review :mag:, bdd-tests 🧪

#1338 Fixes from Release 1.32.0
  test/features/deploy_kogito_runtime.feature
  test/pkg/framework/grafana.go
Labels: needs review :mag:, bdd-tests 🧪
