Repository kiegroup/kogito-operator, pull requests merged in 2022-02, with the labels that each got.

#1108 Fix typo in ISSUES_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: ready :rocket:

#1123 KOGITO-5531 Update Jenkins CI to Maven 3.8.1
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.profiling
Labels: ready :rocket:

#1124 [1.11.x] KOGITO-5531 Update Jenkins CI to Maven 3.8.1
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.profiling
Labels: ready :rocket:

#1125 [1.16.x] KOGITO-5531 Update Jenkins CI to Maven 3.8.1
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.profiling
Labels: ready :rocket:, cherry-pick :cherries:

#1129 [KOGITO-2787] Unify namespace/project wording in logs and Kogito CLI
  RELEASE_NOTES.md
  cmd/kogito/command/deploy/delete_service.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/flag/install_flag.go
  cmd/kogito/command/project/delete_project_test.go
  cmd/kogito/command/remove/kogitoinfra.go
  cmd/kogito/command/shared/resource_checks.go
Labels: ready :rocket:, needs cherry-pick :cherries:

#1131 [KOGITO-2787] Unify namespace/project wording in logs and Kogito CLI
  RELEASE_NOTES.md
  cmd/kogito/command/deploy/delete_service.go
  cmd/kogito/command/deploy/deploy_service.go
  cmd/kogito/command/flag/install_flag.go
  cmd/kogito/command/project/delete_project_test.go
  cmd/kogito/command/remove/kogitoinfra.go
  cmd/kogito/command/shared/resource_checks.go
Labels: ready :rocket:, cherry-pick :cherries:

#1130 Setup multiarch CSV file
  .ci/jenkins/Jenkinsfile-rhpam
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  bundle/rhpam/manifests/rhpam.kiegroup.org_kogitoruntimes.yaml
  bundle/rhpam/manifests/rhpam.kiegroup.org_kogitosupportingservices.yaml
  config/manifests/rhpam/bases/rhpam-kogito-operator.clusterserviceversion.yaml
Labels: ready :rocket:

#1139 [1.13.x] Prepare branch for productization
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile-rhpam
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/Jenkinsfile.promote
  .github/bot-files/reviewers.yml
  .github/workflows/Kogito-Operator-OLM-tests.yaml
  .github/workflows/Kogito-Operator-PR-Check.yaml
  .github/workflows/Kogito-Operator-Unit-tests.yaml
  .github/workflows/jenkins-tests-PR.yml
Labels: needs review :mag:

#1135 [KOGITO-5976] - Kogito operator de-scoping - support for AllNamespaces
  bundle/app/manifests/kogito-operator.clusterserviceversion.yaml
  config/manager/app/manager.yaml
  hack/ci/run-olm-tests.sh
  kogito-operator.yaml
  main.go
  profiling/kogito-operator-profiling.yaml
Labels: ready :rocket:
