Repository kiegroup/kogito-operator, pull requests merged in 2022-06, with the labels that each got.

#1201 [KOGITO-4806] - Track which version of the Operator deployed a Kogito…
  RELEASE_NOTES.md
  controllers/app/kogitoruntimedeployment_controller.go
  core/deployment/deployment_processor.go
  core/deployment/deployment_processor_test.go
  core/framework/annotations.go
  core/kogitobuild/build_config.go
  core/kogitoservice/kogito_deployment.go
  core/kogitosupportingservice/dataindex_reconciler_test.go
  core/kogitosupportingservice/explainability_reconciler_test.go
  core/kogitosupportingservice/jobsservice_reconciler_test.go
  core/kogitosupportingservice/mgmtconsole_reconciler_test.go
  core/kogitosupportingservice/taskconsole_reconciler_test.go
  core/kogitosupportingservice/trustyai_reconciler_test.go
  core/kogitosupportingservice/trustyui_reconciler_test.go
Labels: ready :rocket:

#1169 [KOGITO-3792] Support Topic discovery on Kogito Apps
  RELEASE_NOTES.md
  core/kogitoservice/deployer_test.go
  core/kogitoservice/messaging_kafka.go
  core/kogitoservice/messaging_kafka_test.go
  core/kogitosupportingservice/dataindex_reconciler.go
  core/kogitosupportingservice/explainability_reconciler.go
  core/kogitosupportingservice/jobsservice_reconciler.go
  core/kogitosupportingservice/trustyai_reconciler.go
Labels: needs review :mag:, operator :cloud:

#1210 Fix Prometheus cucumber test
  test/pkg/steps/prometheus.go
Labels: ready :rocket:, bdd-tests 🧪

#1211 [1.13.x] Fix Prometheus cucumber test
  test/pkg/steps/prometheus.go
Labels: ready :rocket:, bdd-tests 🧪

#1212 [RHPAM- 4269] - Fix replaces version with latest one
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  version/rhpam/version.go
Labels: ready :rocket:, operator :cloud:

#1217 Fix wrong replace script for bundle CSV
  hack/rhpam/rhpam-update-bundle.sh
Labels: ready :rocket:

#1214 [1.13.x] KIECLOUD-639 - Remove lookaside cache usage in OSBS
  modules/org.kie.kogito.rhpam.builder.prod/install.sh
  modules/org.kie.kogito.rhpam.builder.prod/module.yaml
  modules/org.kie.kogito.rhpam.builder/install.sh
  rhpam-image-prod.yaml
Labels: ready :rocket:, cherry-pick :cherries:

#1215 KIECLOUD-639 - Remove lookaside cache usage in OSBS
  modules/org.kie.kogito.rhpam.builder.prod/install.sh
  modules/org.kie.kogito.rhpam.builder.prod/module.yaml
  modules/org.kie.kogito.rhpam.builder/install.sh
  rhpam-image-prod.yaml
Labels: ready :rocket:, needs cherry-pick :cherries:

#1213 Cucumber tests: Fix WebHook mapping for both operators
  test/pkg/steps/mappers/create_kogito_build.go
Labels: ready :rocket:

#1225 [1.13.x] Update AMQ streams operator version
  test/pkg/installers/amqstreams_installer.go
Labels: ready :rocket:

#1226 [1.13.x-blue] Update AMQ streams operator version
  test/pkg/installers/amqstreams_installer.go
Labels: ready :rocket:, cherry-pick :cherries:

#1227 Update AMQ streams operator version
  test/pkg/installers/amqstreams_installer.go
Labels: ready :rocket:

#1229 [1.13.x] [KOGITO-7481] - Update ose-kube-rbac-proxy to v4.10.0
  config/full/rhpam/manager_auth_proxy_patch.yaml
  rhpam-operator.yaml
Labels: needs review :mag:, cherry-pick :cherries:
