Repository kiegroup/kogito-operator, pull requests merged in 2022-09, with the labels that each got.

#1266 [1.27.x] Fix Jobs Service BDD tests
  test/features/install_jobs_service.feature
  test/features/keycloak.feature
Labels: needs review :mag:, bdd-tests 🧪

#1267 Fix Jobs Service BDD tests
  test/features/install_jobs_service.feature
  test/features/keycloak.feature
Labels: needs review :mag:, bdd-tests 🧪

#1269 [1.13.x-blue] Correct unit tests
  .github/workflows/Kogito-Operator-OLM-tests.yaml
  README.md
  controllers/rhpam/suite_test.go
Labels: ready :rocket:, needs review :mag:, operator :cloud:

#1271 [1.13.x] Fix CLI build
  go.mod
  go.sum
Labels: needs review :mag:

#1270 [1.13.x] Correct OLM tests
  .github/workflows/Kogito-Operator-OLM-tests.yaml
  README.md
Labels: ready :rocket:

#1273 [1.13.x] [KIECLOUD-654] - prepare RHPAM and RHPAM Kogito operators for 7.13.1 …
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manager/rhpam/kustomization.yaml
  rhpam-operator.yaml
  version/rhpam/version.go
Labels: needs review :mag:

#1275 bump versions to 7.13.1
  modules/org.kie.kogito.rhpam.builder.prod/module.yaml
  modules/org.kie.kogito.rhpam.bundleinstall/module.yaml
  rhpam-image-bundle.yaml
  rhpam-image-prod.yaml
  rhpam-image.yaml
Labels: needs review :mag:

#1272 Fix compilation
  go.mod
  go.sum
  hack/go-build-cli.sh
Labels: ready :rocket:

#1278 [1.27.x] Fix compilation
  go.mod
  go.sum
  hack/go-build-cli.sh
Labels: ready :rocket:

#1274 [1.13.x-blue] [KIECLOUD-654] - prepare RHPAM and RHPAM Kogito operators for 7.13.1 …
  bamoe-operator.yaml
  bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml
  config/manager/bamoe/kustomization.yaml
  config/manifests/bamoe/bases/bamoe-kogito-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/go-build-cli.sh
  version/rhpam/version.go
Labels: needs review :mag:

#1279 [KOGITO-7891] Move s2i to builder-s2i module
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/scripts/helper.groovy
  RELEASE_NOTES.md
  bundle/app/manifests/kogito-operator.clusterserviceversion.yaml
  config/manager/app/manager.yaml
  controllers/app/kogitobuild_controller_test.go
  core/kogitobuild/image_stream.go
  go.tools.mod
  go.tools.sum
  hack/addheaders.sh
  hack/go-lint.sh
  hack/run-tests.sh
  hack/update_test_config.sh.bats
  kogito-operator.yaml
  profiling/kogito-operator-profiling.yaml
  test/.default_config
Labels: cherry-pick :cherries:, bdd-tests 🧪, operator :cloud:

#1284 Remove useless debug commands
  .ci/jenkins/Jenkinsfile
  hack/run-tests.sh
Labels: needs review :mag:

#1277 [1.13.x] [KIECLOUD-654] - bundle replaces points to wrong previous version
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  hack/rhpam/rhpam-update-bundle.sh
  modules/org.kie.kogito.rhpam.builder/module.yaml
Labels: needs review :mag:

#1291 [1.28.x] [KOGITO-7891] Move s2i to builder-s2i module
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/scripts/helper.groovy
  RELEASE_NOTES.md
  bundle/app/manifests/kogito-operator.clusterserviceversion.yaml
  config/manager/app/manager.yaml
  controllers/app/kogitobuild_controller_test.go
  core/kogitobuild/image_stream.go
  go.tools.mod
  go.tools.sum
  hack/addheaders.sh
  hack/go-lint.sh
  hack/run-tests.sh
  hack/update_test_config.sh.bats
  kogito-operator.yaml
  profiling/kogito-operator-profiling.yaml
  test/.default_config
Labels: needs review :mag:, cherry-pick :cherries:, bdd-tests 🧪, operator :cloud:

#1293 KOGITO-8043 Jenkins node master -> built-in
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/Jenkinsfile.init-branch
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/Jenkinsfile.promote
Labels: needs review :mag:

#1294 [1.27.x] KOGITO-8043 Jenkins node master -> built-in
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/Jenkinsfile.init-branch
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/Jenkinsfile.promote
Labels: needs review :mag:

#1295 [1.28.x] KOGITO-8043 Jenkins node master -> built-in
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/Jenkinsfile.init-branch
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/Jenkinsfile.promote
Labels: needs review :mag:

#1296 [1.13.x] KOGITO-8043 Jenkins node master -> built-in
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/Jenkinsfile.promote
  .ci/jenkins/dsl/Jenkinsfile.seed
Labels: needs review :mag:

#1297 [1.13.x-blue] KOGITO-8043 Jenkins node master -> built-in
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/Jenkinsfile.promote
  .ci/jenkins/dsl/Jenkinsfile.seed
Labels: needs review :mag:
