Repository kiegroup/kogito-operator, pull requests merged in 2022-01, with the labels that each got.

#1103 KOGITO-6504 Update kogito-examples paths
  test/features/data_index_performance.feature
  test/features/deploy_kogito_build.feature
  test/features/deploy_kogito_runtime.feature
  test/features/deploy_service_resources.feature
  test/features/deploy_travel_agency.feature
  test/features/grafana.feature
  test/features/install_dataindex.feature
  test/features/install_explainability.feature
  test/features/install_trusty.feature
  test/features/kogito_service_performance.feature
  test/features/prometheus.feature
  test/features/service_discovery.feature
  test/go.mod
  test/go.sum
  test/pkg/steps/kogitobuild.go
  test/pkg/steps/maven.go
Labels: needs review :mag:, bdd-tests 🧪

#1106 KOGITO-6513: add issues template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: ready :rocket:

#1110 Updated Reviewers file to include davidesalerno
  .github/bot-files/reviewers.yml
Labels: ready :rocket:

#1109 [1.11.x] BDD tests: Handle different URL for archetype mirror URL
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/Makefile
  test/features/deploy_source_files.feature
  test/pkg/config/config.go
  test/pkg/steps/deploy_files.go
Labels: needs review :mag:, bdd-tests 🧪

#1117 Setup content_sets for RHPAM images
  content-sets.yaml
  rhpam-image-bundle.yaml
  rhpam-image-prod.yaml
  rhpam-image.yaml
Labels: ready :rocket:

#1119 [KOGITO-6604] Fail fast when Subscription constraint fails
  test/pkg/framework/operator.go
Labels: ready :rocket:, bdd-tests 🧪

#1114 [1.16.x] Corrected BDD tests
  test/features/deploy_source_files.feature
  test/pkg/framework/grafana.go
  test/pkg/installers/grafana_installer.go
  test/pkg/installers/infinispan_installer.go
  test/pkg/steps/deploy_files.go
Labels: needs review :mag:, bdd-tests 🧪

#1115 Corrected BDD tests
  test/features/deploy_source_files.feature
  test/pkg/framework/grafana.go
  test/pkg/installers/grafana_installer.go
  test/pkg/installers/infinispan_installer.go
  test/pkg/steps/deploy_files.go
Labels: ready :rocket:, bdd-tests 🧪

#1116 BDD tests: Handle different URL for archetype mirror URL
  README.md
  hack/run-tests.sh
  hack/run-tests.sh.bats
  test/features/deploy_source_files.feature
  test/pkg/config/config.go
  test/pkg/installers/amqstreams_installer.go
  test/pkg/steps/deploy_files.go
Labels: needs review :mag:, bdd-tests 🧪

#1121 BDD: Added tags to prometheus/grafana tests
  README.md
  test/features/grafana.feature
  test/features/prometheus.feature
Labels: needs review :mag:, bdd-tests 🧪

#1120 BXMSPROD-1579 Send build summary as PR comment
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile-rhpam
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  content_sets.yaml
  rhpam-image-prod.yaml
  rhpam-image.yaml
Labels: needs review :mag:
