Repository kiegroup/kogito-operator, pull requests merged in 2022-10, with the labels that each got.

#1300 [1.13.x-blue] bump versions to 8.0.1
  bamoe-image-bundle.yaml
  bamoe-image-prod.yaml
  bamoe-image.yaml
  modules/org.kie.kogito.rhpam.builder.prod/module.yaml
  modules/org.kie.kogito.rhpam.bundleinstall/module.yaml
Labels: needs review :mag:

#1301 [1.13.x-blue] bundle replaces points to wrong previous version
  bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml
  hack/rhpam/rhpam-update-bundle.sh
Labels: needs review :mag:

#1302 [KOGITO-8088][RHPAM-4437] - Gain All Capabilities Using Unshare
  RELEASE_NOTES.md
  bundle/app/manifests/kogito-operator.clusterserviceversion.yaml
  config/crd/rhpam/bases/rhpam.kiegroup.org_kogitobuilds.yaml
  config/crd/rhpam/bases/rhpam.kiegroup.org_kogitoinfras.yaml
  config/crd/rhpam/bases/rhpam.kiegroup.org_kogitoruntimes.yaml
  config/crd/rhpam/bases/rhpam.kiegroup.org_kogitosupportingservices.yaml
  config/manager/app/manager.yaml
  config/manager/rhpam/manager.yaml
  config/rbac/rhpam/role.yaml
  core/deployment/deployment_processor.go
  core/deployment/deployment_processor_test.go
  go.mod
  kogito-operator.yaml
  profiling/kogito-operator-profiling.yaml
  rhpam-operator.yaml
Labels: needs review :mag:, operator :cloud:

#1303 [1.13.x][RHPAM-4437] - Gain All Capabilities Using Unshare
  RELEASE_NOTES.md
  bundle/app/manifests/kogito-operator.clusterserviceversion.yaml
  config/crd/rhpam/bases/rhpam.kiegroup.org_kogitobuilds.yaml
  config/crd/rhpam/bases/rhpam.kiegroup.org_kogitoinfras.yaml
  config/crd/rhpam/bases/rhpam.kiegroup.org_kogitoruntimes.yaml
  config/crd/rhpam/bases/rhpam.kiegroup.org_kogitosupportingservices.yaml
  config/manager/app/manager.yaml
  config/manager/rhpam/manager.yaml
  config/rbac/rhpam/role.yaml
  core/kogitoservice/kogito_deployment.go
  core/kogitoservice/kogito_deployment_test.go
  go.mod
  kogito-operator.yaml
  profiling/kogito-operator-profiling.yaml
  rhpam-operator.yaml
Labels: needs review :mag:, operator :cloud:

#1304 [1.13.x-blue][RHPAM-4437] - Gain All Capabilities Using Unshare
  RELEASE_NOTES.md
  bamoe-operator.yaml
  bundle/app/manifests/kogito-operator.clusterserviceversion.yaml
  config/manager/app/manager.yaml
  config/manager/bamoe/manager.yaml
  core/kogitoservice/kogito_deployment.go
  core/kogitoservice/kogito_deployment_test.go
  go.mod
  kogito-operator.yaml
  profiling/kogito-operator-profiling.yaml
Labels: on hold :hand:, needs review :mag:, operator :cloud:

#1310 [1.13.x] [RHPAM-4515] - RHPAM Kogito Operator OLM page links should point to R…
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  bundle/rhpam/manifests/rhpam.kiegroup.org_kogitobuilds.yaml
  bundle/rhpam/manifests/rhpam.kiegroup.org_kogitoinfras.yaml
  bundle/rhpam/manifests/rhpam.kiegroup.org_kogitoruntimes.yaml
  bundle/rhpam/manifests/rhpam.kiegroup.org_kogitosupportingservices.yaml
  bundle/rhpam/metadata/annotations.yaml
  config/manifests/rhpam/bases/rhpam-kogito-operator.clusterserviceversion.yaml
  rhpam-operator.yaml
Labels: ready :rocket:

#1309 [RHPAM-4515] - RHPAM Kogito Operator OLM page links should point to R…
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  bundle/rhpam/manifests/rhpam.kiegroup.org_kogitobuilds.yaml
  bundle/rhpam/manifests/rhpam.kiegroup.org_kogitoinfras.yaml
  bundle/rhpam/manifests/rhpam.kiegroup.org_kogitoruntimes.yaml
  bundle/rhpam/manifests/rhpam.kiegroup.org_kogitosupportingservices.yaml
  bundle/rhpam/metadata/annotations.yaml
  config/manifests/rhpam/bases/rhpam-kogito-operator.clusterserviceversion.yaml
  rhpam-operator.yaml
Labels: ready :rocket:, operator :cloud:

#1305 KOGITO-8110 Correct GHA DSL checks
  .ci/jenkins/dsl/test.sh
  .github/workflows/Kogito-Operator-PR-Check.yaml
  .github/workflows/Kogito-Operator-Unit-tests.yaml
  .github/workflows/jenkins-tests-PR.yml
Labels: needs review :mag:

#1312 Correct DSL GHA
  .github/workflows/jenkins-tests-PR.yml
Labels: ready :rocket:

#1315 [1.13.x-blue][RHPAM-4558] - Upgrade oauth proxy image on ba and kogit…
  bamoe-operator.yaml
  config/full/bamoe/manager_auth_proxy_patch.yaml
Labels: ready :rocket:

#1314 [1.13.x][RHPAM-4558] - Upgrade oauth proxy image on ba and kogito ope…
  config/full/rhpam/manager_auth_proxy_patch.yaml
  rhpam-operator.yaml
Labels: needs review :mag:

#1313 [RHPAM-4558] - Upgrade oauth proxy image on ba and kogito operators t…
  config/full/rhpam/manager_auth_proxy_patch.yaml
  rhpam-operator.yaml
Labels: needs review :mag:
