Repository kiegroup/kogito-operator, pull requests merged in 2022-07, with the labels that each got.

#1230 [1.13.x-blue] [KOGITO-7481] - Update ose-kube-rbac-proxy to v4.10.0
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/full/rhpam/manager_auth_proxy_patch.yaml
  rhpam-operator.yaml
Labels: ready :rocket:, cherry-pick :cherries:

#1228 [KOGITO-7481] - Update ose-kube-rbac-proxy to v4.10.0
  RELEASE_NOTES.md
  bundle/app/manifests/kogito-operator.clusterserviceversion.yaml
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/full/app/manager_auth_proxy_patch.yaml
  config/full/rhpam/manager_auth_proxy_patch.yaml
  config/manager/rhpam/kustomization.yaml
  kogito-operator.yaml
  profiling/kogito-operator-profiling.yaml
  rhpam-operator.yaml
Labels: ready :rocket:, needs cherry-pick :cherries:

#1233 clean release_notes.md
  RELEASE_NOTES.md
Labels: needs review :mag:

#1235 Update GHA DSL check to use composite action
  .github/workflows/jenkins-tests-PR.yml
Labels: ready :rocket:

#1239 KOGITO-5780 Set JDK and Maven tools as env vars
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/dsl/jobs.groovy
  .ci/jenkins/dsl/test.sh
Labels: ready :rocket:

#1232 [1.13.x-blue] [KOGITO-7457] - Rebranding changes on the kogito-operator repository
  Makefile.rhpam
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manager/rhpam/kustomization.yaml
  config/manager/rhpam/manager.yaml
  config/manifests/rhpam/bases/rhpam-kogito-operator.clusterserviceversion.yaml
  examples/rhpam/quarkus-jvm.Dockerfile
  hack/run-tests.sh
  modules/org.kie.kogito.rhpam.builder.prod/module.yaml
  modules/org.kie.kogito.rhpam.bundleinstall/module.yaml
  rhpam-image-bundle.yaml
  rhpam-image-prod.yaml
  rhpam-image.yaml
  rhpam-operator.yaml
  test/pkg/config/config.go
  test/pkg/installers/rhpam_kogito_installer.go
  version/rhpam/version.go
Labels: needs review :mag:, bdd-tests 🧪

#1241 [1.13.x-blue] [KOGITO-7457] - Rebranding changes on the kogito-operator repository …
  .ci/jenkins/Jenkinsfile-rhpam
  Makefile.rhpam
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  bundle/rhpam/metadata/annotations.yaml
  config/default/rhpam/kustomization.yaml
  config/manager/rhpam/kustomization.yaml
  config/manager/rhpam/manager.yaml
  config/manifests/rhpam/bases/rhpam-kogito-operator.clusterserviceversion.yaml
  examples/rhpam/quarkus-jvm.Dockerfile
  examples/rhpam/springboot.Dockerfile
  go.tools.mod
  go.tools.sum
  hack/rhpam/rhpam-deploy-operator-on-ocp.sh
  hack/rhpam/rhpam-update-bundle.sh
  rhpam-image-bundle.yaml
  rhpam-image-prod.yaml
  rhpam-image.yaml
  rhpam-operator.yaml
  test/pkg/installers/rhpam_kogito_installer.go
Labels: needs review :mag:, bdd-tests 🧪

#1243 [KOGITO-7457] - Rebranding changes on the kogito-operator repository …
  rhpam-image-bundle.yaml
  rhpam-image-prod.yaml
  rhpam-image.yaml
Labels: needs review :mag:

#1244 [1.13.x-blue] [KIECLOUD-649] - Update the ba and kogito operator icon
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  bundle/rhpam/metadata/annotations.yaml
  config/manifests/rhpam/bases/rhpam-kogito-operator.clusterserviceversion.yaml
Labels: ready :rocket:

#1242 [KOGITO-6297] - Add example in kogito-operator repo
  RELEASE_NOTES.md
  examples/app/user-friendly/process-quarkus-example.yaml
Labels: ready :rocket:, needs review :mag:

#1247 [1.13.x-blue][KOGITO-7457] update csv sources repo
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manager/rhpam/manager.yaml
  config/manifests/rhpam/bases/rhpam-kogito-operator.clusterserviceversion.yaml
Labels: needs review :mag:

#1249 [1.13.x] Set back native checks
  test/features/deploy_kogito_build.feature
  test/features/deploy_kogito_runtime.feature
Labels: ready :rocket:, bdd-tests 🧪

#1248 [1.13.x-blue] Set back native checks
  test/features/deploy_kogito_build.feature
  test/features/deploy_kogito_runtime.feature
Labels: ready :rocket:, bdd-tests 🧪

#1250 [1.13.x-blue][KOGITO-7457] - Rebranding changes on the kogito-operato…
  rhpam-image-bundle.yaml
Labels: ready :rocket:

#1253 [1.25.x] BDD: Update grafana image version
  test/pkg/framework/grafana.go
Labels: ready :rocket:, bdd-tests 🧪

#1254 BDD: Update grafana image version
  test/pkg/framework/grafana.go
Labels: ready :rocket:, bdd-tests 🧪

#1256 [1.13.x] BDD: Update grafana image version (#1254)
  test/pkg/framework/grafana.go
Labels: needs review :mag:, bdd-tests 🧪

#1257 [1.13.x-blue][KIECLOUD-653] - Rename documentation and Product page links on opera…
  bamoe-image-bundle.yaml
  bamoe-image-prod.yaml
  bamoe-image.yaml
  bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml
  config/manifests/bamoe/bases/bamoe-kogito-operator.clusterserviceversion.yaml
Labels: needs review :mag:
