Repository kiegroup/kogito-operator, pull requests merged in 2022-05, with the labels that each got.

#1171 KOGITO-6962 DSL reorganization for flexibility
  .ci/jenkins/dsl/jobs.groovy
  .ci/jenkins/dsl/test.sh
  .github/workflows/jenkins-tests-PR.yml
Labels: WIP :construction_worker_man:, dsl-test

#1180 [1.13.x] fix ppc64le section in content_sets.yaml
  content_sets.yaml
Labels: needs review :mag:

#1181 fix ppc64le section in content_sets.yaml
  content_sets.yaml
Labels: needs review :mag:

#1182 KOGITO-7101 Correct DSL tests
  .ci/jenkins/dsl/test.sh
  .github/workflows/jenkins-tests-PR.yml
Labels: ready :rocket:

#1183 [KOGITO-7100] Jenkinsfiles: Corrected boolean env var handling
  .ci/jenkins/Jenkinsfile.deploy
Labels: ready :rocket:

#1184 KOGITO-7110 Correct nightly DSL generation
  .ci/jenkins/dsl/jobs.groovy
  .ci/jenkins/scripts/helper.groovy
Labels: ready :rocket:

#1186 [1.13.x] [RHPAM-4302] : RHPAM Kogito Operator image does not start
  .github/workflows/Kogito-Operator-OLM-tests.yaml
  Makefile
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manager/rhpam/manager.yaml
  rhpam-operator.yaml
  test/pkg/framework/openshift.go
  test/pkg/installers/rhpam_kogito_installer.go
Labels: needs review :mag:

#1185 [7.13.x] QE fixes
  .gitignore
  test/features/deploy_kogito_build.feature
  test/features/deploy_kogito_runtime.feature
  test/features/deploy_source_files.feature
  test/features/service_discovery.feature
  test/pkg/framework/kafka.go
  test/pkg/framework/maven.go
  test/pkg/framework/openshift.go
  test/pkg/steps/kafka.go
Labels: WIP :construction_worker_man:
