Repository kiegroup/kogito-operator, pull requests merged in 2022-04, with the labels that each got.

#1166 [KOGITO-6948] - Remove s390x arch from rhpam and kogito in kogito-opr…
  content_sets.yaml
  rhpam-image-bundle.yaml
  rhpam-image-prod.yaml
  rhpam-image.yaml
Labels: ready :rocket:, cherry-pick :cherries:

#1165 [KOGITO-6948] - Remove s390x arch from rhpam and kogito in kogito-opr…
  content-sets.yaml
  rhpam-image-bundle.yaml
  rhpam-image-prod.yaml
  rhpam-image.yaml
Labels: ready :rocket:, needs cherry-pick :cherries:

#1173 Added tempo when creating the release...
  .ci/jenkins/scripts/helper.groovy
Labels: needs review :mag:
