Repository kiegroup/kogito-operator, pull requests merged in 2022-03, with the labels that each got.

#1142 Remove OLM tests from daily checks
  .ci/jenkins/Jenkinsfile.deploy
  .github/workflows/Kogito-Operator-OLM-tests.yaml
Labels: needs review :mag:

#1143 [1.11.x] Update Grafana operator/image version
  test/pkg/framework/grafana.go
  test/pkg/installers/grafana_installer.go
Labels: needs review :mag:, bdd-tests 🧪

#1147 [1.13.x] - Fix CSV cmd
  Makefile
Labels: ready :rocket:, cherry-pick :cherries:

#1148 [main] - Fix CSV cmd
  Makefile
Labels: ready :rocket:, needs cherry-pick :cherries:

#1145 [1.18.x] Update Grafana image version to 7.5.15 (#1141)
  test/pkg/framework/grafana.go
Labels: needs review :mag:, bdd-tests 🧪

#1151 BDD: Setup some debug features
  test/debug_features/README.md
  test/debug_features/install.feature
  test/pkg/executor/bdd_executor.go
Labels: needs review :mag:, bdd-tests 🧪

#1152 [1.13.x] Community: Update for productization
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.examples-images.deploy
  go.mod
  go.sum
  hack/go-build-cli.sh
Labels: needs review :mag:

#1146 [KOGITO-6812] - Kogito operator should support label on deployment
  RELEASE_NOTES.md
  controllers/app/kogitoruntime_controller.go
  controllers/app/kogitoruntimedeployment_controller.go
  controllers/app/kogitosupportingservice_controller.go
  controllers/common/runtime_controller.go
  controllers/common/runtimedeployment_controller.go
  controllers/common/supportingservice_controller.go
  controllers/rhpam/kogitoruntime_controller.go
  controllers/rhpam/kogitosupportingservice_controller.go
  core/connector/url_handler_test.go
  core/deployment/deployment_processor.go
  core/framework/util/maps.go
  core/kogitoservice/deployment_reconciler.go
  core/manager/runtime_manager.go
  core/operator/context.go
  core/operator/operator.go
  main.go
Labels: on hold :hand:, needs review :mag:, operator :cloud:

#1137 [KOGITO-3779] Don't create protobuf-files config map when no protobuf files are available
  core/kogitoservice/dashboards_test.go
  core/kogitoservice/kogito_service.go
  core/kogitoservice/messaging_knative_test.go
  core/kogitoservice/messaging_test.go
  core/shared/protobuf.go
  core/shared/protobuf_configmap.go
  core/shared/protobuf_configmap_reconciler.go
  core/shared/protobuf_configmap_reconciler_test.go
  core/shared/protobuf_configmap_test.go
  core/shared/protobuf_test.go
  core/test/mock_svc.go
Labels: needs review :mag:, operator :cloud:

#1158 KOGITO-6888 Corrected scale to 0 of Infinispan
  test/pkg/framework/infinispan.go
  test/pkg/framework/kubernetes.go
  test/pkg/steps/infinispan.go
Labels: needs review :mag:, bdd-tests 🧪

#1162 [KOGITO-6907] - Add subscription annotations to and Kogito operator
  Makefile.rhpam
  RELEASE_NOTES.md
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manifests/rhpam/bases/rhpam-kogito-operator.clusterserviceversion.yaml
Labels: needs review :mag:

#1163 [KOGITO-6907] - Add subscription annotations to and Kogito operator
  Makefile.rhpam
  RELEASE_NOTES.md
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manifests/rhpam/bases/rhpam-kogito-operator.clusterserviceversion.yaml
Labels: ready :rocket:
