Repository kiegroup/kogito-operator, pull requests merged in 2023-02, with the labels that each got.

#1356 [KIECLOUD-687] - Prepare the BAMOE branches for the 8.0.3 release
  RELEASE_NOTES.md
  bamoe-operator.yaml
  bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml
  config/manager/bamoe/kustomization.yaml
  version/rhpam/version.go
Labels: ready :rocket:

#1358 [KOGITO-8598] Golint deprecated migrated to revive
  core/infrastructure/reconciliation_error.go
  core/kogitobuild/utils.go
  core/kogitoinfra/infinispanconfig_reconciler.go
  core/kogitoinfra/infraproperties_reconciler.go
  core/kogitoinfra/kafkaconfig_reconciler.go
  core/kogitoinfra/mongodbconfig_reconciler.go
  core/kogitoservice/config_reconciler.go
  core/kogitoservice/status_test.go
  hack/go-lint.sh
  revive.toml
Labels: needs review :mag:, operator :cloud:, backport-1.33.x

#1364 [KIECLOUD-663] Create pipeline for rhpam-kogito operator
  hack/build-osbs.sh
  modules/org.kie.kogito.rhpam.builder/module.yaml
  modules/org.kie.kogito.rhpam.bundleinstall/module.yaml
  rhpam-image-bundle.yaml
  rhpam-image-prod.yaml
  rhpam-image.yaml
Labels: needs review :mag:

#1366 [KEICLOUD-664]Create pipeline for bamoe-kogito operator
  hack/build-osbs.sh
Labels: needs review :mag:

#1372 [Kiecloud-663] Create pipeline for rhpam-kogito operator
  hack/build-osbs.sh
Labels: needs review :mag:

#1369 add execution permission to osbs script
  hack/build-osbs.sh
Labels: needs review :mag:

#1371 [KIECLOUD-663] Create pipeline for rhpam-kogito operator
  hack/build-osbs.sh
Labels: needs review :mag:

#1375 [KIECLOUD-692] - Update the target dist-git branch with the new ones
  Makefile.rhpam
  hack/build-osbs.sh
Labels: needs review :mag:

#1374 [KIECLOUD-692] - Update the target dist-git branch with the new ones
  Makefile.rhpam
  hack/build-osbs.sh
Labels: needs review :mag:, needs cherry-pick :cherries:, backport-1.13.x

#1373 KIECLOUD-688 Use rhel8 for podman jobs
  .ci/jenkins/Jenkinsfile.examples-images.promote
  .ci/jenkins/Jenkinsfile.promote
Labels: needs review :mag:

#1376 [KIECLOUD-692] - Update the target dist-git branch with the new ones
  Makefile.rhpam
  hack/build-osbs.sh
Labels: needs review :mag:, cherry-pick :cherries:

#1381 [1.34.x] [KOGITO-8708] Infinispan corrections
  core/kogitoinfra/infinispan_reconciler.go
  core/kogitoinfra/infinispancredential_reconciler_test.go
  hack/clean-cluster-operators.sh
Labels: needs review :mag:, operator :cloud:

#1382 Corrections from 1.34 release
  core/kogitoinfra/infinispan_reconciler.go
  core/kogitoinfra/infinispancredential_reconciler_test.go
  hack/clean-cluster-operators.sh
  test/features/install_dataindex.feature
Labels: needs review :mag:, bdd-tests 🧪, operator :cloud:

#1397 KOGITO-8751 BDD: Disable keycloak testing
  test/features/keycloak.feature
Labels: backport-1.35.x

#1398 Correct Setup Branch job
  .ci/jenkins/Jenkinsfile.setup-branch
Labels: needs review :mag:
