Repository kiegroup/kogito-operator, pull requests merged in 2023-06, with the labels that each got.

#1482 Update PR Jenkins node label
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile-rhpam
Labels: backport-1.13.x-blue, backport-1.13.x, backport-1.13.x-next, backport-1.13.x-blue-next, backport-1.39.x

#1493 [1.13.x][KIECLOUD-725] - Update RHPAM and BAMOE bundle for CVE respin
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  version/rhpam/version.go
Labels: needs cherry-pick :cherries:

#1494 [1.13.x-next][KIECLOUD-725] - Update RHPAM and BAMOE bundle for CVE respin
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  version/rhpam/version.go
Labels: cherry-pick :cherries:

#1495 [1.13.x-blue][KIECLOUD-725] - Update RHPAM and BAMOE bundle for CVE respin
  bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml
  version/rhpam/version.go
Labels: needs cherry-pick :cherries:

#1496 [1.13.x-blue-next][KIECLOUD-725] - Update RHPAM and BAMOE bundle for CVE respin
  bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml
  version/rhpam/version.go
Labels: cherry-pick :cherries:
