Repository kiegroup/kogito-operator, pull requests merged in 2023-04, with the labels that each got.

#1434 [RHPAM-4665] - [Kogito] Address the security alerts from Dependabot
  client/go.mod
  client/go.sum
  go.mod
  go.sum
Labels: backport-1.13.x-blue, backport-1.13.x, backport-1.36.x

#1438 [RHPAM-4665] - [Kogito] Address the security alerts from Dependabot
  apis/go.mod
  apis/go.sum
Labels: backport-1.13.x-blue, backport-1.13.x, backport-1.36.x

#1444 [RHPAM-4665] - Kogito] Address the security alerts from Dependabot
  apis/go.mod
  apis/go.sum
Labels: backport-1.13.x-blue, backport-1.13.x, backport-1.36.x

#1448 [KIECLOUD-711] - Add retry mechanism when trying to create the kerber…
  hack/build-osbs.sh
Labels: backport-1.13.x-blue, backport-1.13.x

#1458 [1.13.x] BDD tests: native S2I disabled
  test/features/deploy_kogito_build.feature
Labels: backport-1.13.x-blue
