Repository kiegroup/kogito-operator, pull requests merged in 2023-01, with the labels that each got.

#1342 [1.13.x] BDD: AMQ streams 2.2
  test/pkg/installers/amqstreams_installer.go
Labels: needs review :mag:, bdd-tests 🧪, backport-1.13.x-blue

#1341 [1.13.x-blue] Updated grafana image
  test/pkg/framework/grafana.go
Labels: needs review :mag:, bdd-tests 🧪

#1344 update bamoe-operator.yaml
  bamoe-operator.yaml
Labels: needs review :mag:

#1345 [1.13.x] BDD: Support several image versions for Grafana
  test/pkg/framework/grafana.go
Labels: needs review :mag:, bdd-tests 🧪

#1346 [1.13.x-blue] BDD: Support several image versions for Grafana
  test/pkg/framework/grafana.go
Labels: needs review :mag:, bdd-tests 🧪

#1343 [1.13.x-blue] BDD: AMQ streams 2.2
  test/pkg/installers/amqstreams_installer.go
Labels: needs review :mag:, bdd-tests 🧪

#1347 KOGITO-8393 Clean release notes on branching
  .ci/jenkins/Jenkinsfile.setup-branch
Labels: needs review :mag:

#1348 Pipelines: Update Cekit path
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.profiling
  .ci/jenkins/Jenkinsfile.setup-branch
Labels: backport-1.33.x

#1349 [KOGITO-8495] Bump quarkus version to 2.16.0.Final
  cmd/kogito/command/test/common.go
  core/client/client.go
  core/infrastructure/mongodb/v1/mongodbcommunity_types.go
  core/kogitoinfra/infinispan_reconciler.go
  core/kogitoinfra/infinispanconfig_reconciler.go
  core/kogitoinfra/infinispanconfig_reconciler_test.go
  core/kogitoservice/kogito_service.go
  core/test/mock_svc.go
  test/pkg/installers/infinispan_installer.go
  test/pkg/installers/keycloak_installer.go
Labels: needs review :mag:, bdd-tests 🧪, cli 💻, operator :cloud:, backport-1.33.x
