Repository kiegroup/kogito-operator, pull requests merged in 2023-03, with the labels that each got.

#1402 [BXMSPROD-1976] enable backporting from all branches
  .github/workflows/pr-backporting.yml
Labels: ready :rocket:

#1408 [1.35.x] Fix BDD tests based on release
  test/features/deploy_kogito_runtime.feature
  test/features/install_dataindex.feature
Labels: needs review :mag:, bdd-tests 🧪, backport-main

#1409 Fix BDD tests based on release (#1408)
  test/features/deploy_kogito_runtime.feature
  test/features/install_dataindex.feature
Labels: needs review :mag:, bdd-tests 🧪

#1401 [KIECLOUD-697] - Bump RHPAM/BAMOE Kogito operator bundle version for …
  bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml
  version/rhpam/version.go
Labels: ready :rocket:

#1400 [KIECLOUD-697] - Bump RHPAM Kogito operator bundle version for CVE re…
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  version/rhpam/version.go
Labels: ready :rocket:

#1414 [RHPAM-4629] RHPAM Kogito Operator 7.x installation is failing with OOMKilled and CrashLoopBackOff
  bamoe-operator.yaml
  bundle/app/manifests/kogito-operator.clusterserviceversion.yaml
  bundle/bamoe/manifests/bamoe-kogito-operator.clusterserviceversion.yaml
  config/manager/app/manager.yaml
  config/manager/bamoe/manager.yaml
  kogito-operator.yaml
Labels: needs review :mag:

#1413 [RHPAM-4629] RHPAM Kogito Operator 7.x installation is failing with OOMKilled and CrashLoopBackOff
  bundle/app/manifests/kogito-operator.clusterserviceversion.yaml
  bundle/rhpam/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manager/app/manager.yaml
  config/manager/rhpam/manager.yaml
  kogito-operator.yaml
  rhpam-operator.yaml
Labels: needs review :mag:

#1416 [KIECLOUD-694] - fixes duplicated item in the rhpam-image.yaml
  rhpam-image.yaml
Labels: backport-1.13.x

#1423 [KIECLOUD-702] - RHPAM Kogito Operator - Upgrade OCP EUS to version 4.10
  rhpam-image-bundle.yaml
Labels: backport-1.13.x

#1426 [KIECLOUD-694] - use rhpam-image-prod.yaml descriptor
  Makefile.rhpam
  hack/build-osbs.sh
Labels: backport-1.13.x
